import type { Locale } from '@/lib/LocaleContext';

export const ui = {
  pl: {
    imageLoadError: 'Nie udało się wczytać obrazu.',
    canvasNotSupported: 'Twoja przeglądarka nie obsługuje kontekstu 2D.',
    fileGenerationError: 'Nie udało się wygenerować pliku.',
    addImageFirst: 'Dodaj najpierw zdjęcie.',
    setValidDimensions: 'Ustaw poprawne wymiary docelowe.',
    addImage: 'Dodaj zdjęcie',
    dragDropImage: 'Przeciągnij i upuść zdjęcie tutaj',
    clickToSelect: 'lub kliknij, aby wybrać plik z dysku',
    supportedFormats: 'Obsługiwane: JPG, PNG, WebP',
    currentFile: 'Aktualny plik:',
    imageParams: 'Parametry obrazu',
    noData: 'Brak danych - dodaj zdjęcie.',
    original: 'Oryginalne:',
    aspectRatio: 'Proporcje:',
    target: 'Docelowe:',
    inputFormat: 'Format wejściowy:',
    outputFormat: 'Format wyjściowy:',
    shape: 'Kształt:',
    sourceFile: 'Plik źródłowy:',
    estimatedResult: 'Szacowany wynik:',
    convertAndDownload: 'Konwertuj i pobierz',
    quality: 'Jakość (JPG/WEBP)',
    qualityHelper: 'Niższa wartość oznacza mniejszy plik, ale słabszą jakość obrazu. Dla mediów społecznościowych optymalna wartość to 70–85%.',
    processing: 'Przetwarzanie…',
    resizeAndDownload: 'Zmień rozmiar i pobierz',
    cropTools: 'Narzędzia kadrowania',
    addImageFirstHelper: 'Najpierw dodaj zdjęcie po lewej stronie. Potem pojawią się ustawienia kadru i podgląd.',
    demoOriginal: 'Oryginał: 3000 x 2000 px',
    demoTarget: 'Docelowy: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram post pion · 4:5',
    dimensions: 'Wymiary w px',
    presetsLabel: 'Gotowe formaty',
    shapesLabel: 'Kształty kadru',
    zoom: 'Przybliżenie',
    position: 'Pozycja',
    gridColor: 'Kolor siatki',
    width: 'Szerokość (px)',
    height: 'Wysokość (px)',
    keepAspectRatio: 'Zachowaj proporcje (automatyczny drugi wymiar)',
    category: 'Kategoria',
    format: 'Format',
    selectPreset: 'Wybierz format',
    rectAspect: 'Proporcje prostokąta',
    cropZoom: 'Przybliżenie kadru',
    horizontal: 'Poziom (X)',
    vertical: 'Pion (Y)',
    centerHorizontal: 'Wyśrodkuj poziomo',
    centerVertical: 'Wyśrodkuj pionowo',
    centerCrop: 'Wyśrodkuj kadr',
    cropPreview: 'Podgląd kadru',
    cropPreviewHelper:
      'Jasny obszar pokazuje dokładny kadr, który zostanie zapisany. Zapisany plik będzie miał dokładnie ten rozmiar i fragment obrazu, który widzisz w środku. Dla kształtu koła plik będzie miał przezroczyste tło poza kształtem (PNG / WebP).',
    shapes: {
      rect: 'Prostokąt',
      square: 'Kwadrat',
      circle: 'Koło',
    },
    gridColors: {
      emerald: 'Zielony',
      white: 'Biały',
      black: 'Czarny',
      red: 'Czerwony',
      yellow: 'Żółty',
    },
    categories: {
      social: 'media społecznościowe',
      web: 'WWW',
    },
    presets: {
      igSquare: 'Instagram - post kwadrat (1080x1080)',
      igPortrait: 'Instagram - post pion (1080x1350)',
      igStory: 'Instagram - story / reels (1080x1920)',
      fbPost: 'Facebook - post (1200x630)',
      fbCover: 'Facebook - cover strony (820x360)',
      liPost: 'LinkedIn - post (1200x1200)',
      liBanner: 'LinkedIn - baner profilu (1584x396)',
      ogImage: 'OG image (1200x630)',
      cover: 'Grafika do artykułu (1600x900)',
      banner: 'Baner strony (1920x600)',
      thumb: 'Miniatura artykułu (800x600)',
      hero: 'Hero sekcji (1920x1080)',
      bg: 'Tło sekcji (1920x1280)',
    },
    previewAlt: 'Podgląd',
  },
  en: {
    imageLoadError: 'Failed to load the image.',
    canvasNotSupported: 'Your browser does not support 2D canvas.',
    fileGenerationError: 'Failed to generate the file.',
    addImageFirst: 'Add an image first.',
    setValidDimensions: 'Set valid target dimensions.',
    addImage: 'Add image',
    dragDropImage: 'Drag and drop an image here',
    clickToSelect: 'or click to select a file from your device',
    supportedFormats: 'Supported: JPG, PNG, WebP',
    currentFile: 'Current file:',
    imageParams: 'Image parameters',
    noData: 'No data — add an image.',
    original: 'Original:',
    aspectRatio: 'Aspect ratio:',
    target: 'Target:',
    inputFormat: 'Input format:',
    outputFormat: 'Output format:',
    shape: 'Shape:',
    sourceFile: 'Source file:',
    estimatedResult: 'Estimated result:',
    convertAndDownload: 'Convert and download',
    quality: 'Quality (JPG/WEBP)',
    qualityHelper: 'Lower value means smaller file but lower image quality. For social media, the optimal value is 70–85%.',
    processing: 'Processing…',
    resizeAndDownload: 'Resize and download',
    cropTools: 'Crop tools',
    addImageFirstHelper: 'First add an image on the left. Then crop settings and preview will appear.',
    demoOriginal: 'Original: 3000 x 2000 px',
    demoTarget: 'Target: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram portrait post · 4:5',
    dimensions: 'Dimensions in px',
    presetsLabel: 'Presets',
    shapesLabel: 'Crop shapes',
    zoom: 'Zoom',
    position: 'Position',
    gridColor: 'Grid color',
    width: 'Width (px)',
    height: 'Height (px)',
    keepAspectRatio: 'Keep aspect ratio (auto second dimension)',
    category: 'Category',
    format: 'Format',
    selectPreset: 'Select format',
    rectAspect: 'Rectangle aspect ratio',
    cropZoom: 'Crop zoom',
    horizontal: 'Horizontal (X)',
    vertical: 'Vertical (Y)',
    centerHorizontal: 'Center horizontally',
    centerVertical: 'Center vertically',
    centerCrop: 'Center crop',
    cropPreview: 'Crop preview',
    cropPreviewHelper:
      'The bright area shows the exact crop that will be saved. The saved file will have exactly the size and image fragment you see in the center. For circle shape the file will have a transparent background outside the shape (PNG / WebP).',
    shapes: {
      rect: 'Rectangle',
      square: 'Square',
      circle: 'Circle',
    },
    gridColors: {
      emerald: 'Green',
      white: 'White',
      black: 'Black',
      red: 'Red',
      yellow: 'Yellow',
    },
    categories: {
      social: 'social media',
      web: 'web',
    },
    presets: {
      igSquare: 'Instagram — square post (1080x1080)',
      igPortrait: 'Instagram — portrait post (1080x1350)',
      igStory: 'Instagram — story / reels (1080x1920)',
      fbPost: 'Facebook — post (1200x630)',
      fbCover: 'Facebook — page cover (820x360)',
      liPost: 'LinkedIn — post (1200x1200)',
      liBanner: 'LinkedIn — profile banner (1584x396)',
      ogImage: 'OG image (1200x630)',
      cover: 'Article cover (1600x900)',
      banner: 'Website banner (1920x600)',
      thumb: 'Article thumbnail (800x600)',
      hero: 'Hero section (1920x1080)',
      bg: 'Section background (1920x1280)',
    },
    previewAlt: 'Preview',
  },
} as const satisfies Record<Locale, unknown>;

export type UiLocale = (typeof ui)['pl'] | (typeof ui)['en'];
