import type { Locale } from '@/lib/LocaleContext';

export const ui = {
  pl: {
    imageLoadError: 'Nie udało się wczytać obrazu.',
    canvasNotSupported: 'Twoja przeglądarka nie obsługuje kontekstu 2D.',
    fileGenerationError: 'Nie udało się wygenerować pliku.',
    addImageFirst: 'Dodaj najpierw zdjęcie.',
    setValidDimensions: 'Ustaw poprawne wymiary docelowe.',
    addImage: 'Dodaj zdjęcie',
    dragDropImage: 'Przeciągnij i upuść zdjęcie tutaj',
    clickToSelect: 'lub kliknij, aby wybrać plik z dysku',
    supportedFormats: 'Obsługiwane: JPG, PNG, WebP',
    currentFile: 'Aktualny plik:',
    imageParams: 'Parametry obrazu',
    noData: 'Brak danych - dodaj zdjęcie.',
    original: 'Oryginalne:',
    aspectRatio: 'Proporcje:',
    target: 'Docelowe:',
    inputFormat: 'Format wejściowy:',
    outputFormat: 'Format wyjściowy:',
    shape: 'Kształt:',
    sourceFile: 'Plik źródłowy:',
    estimatedResult: 'Szacowany wynik:',
    convertAndDownload: 'Konwertuj i pobierz',
    quality: 'Jakość (JPG/WEBP)',
    qualityHelper: 'Niższa wartość oznacza mniejszy plik, ale słabszą jakość obrazu. Dla mediów społecznościowych optymalna wartość to 70–85%.',
    processing: 'Przetwarzanie…',
    resizeAndDownload: 'Zmień rozmiar i pobierz',
    cropTools: 'Narzędzia kadrowania',
    addImageFirstHelper: 'Najpierw dodaj zdjęcie po lewej stronie. Potem pojawią się ustawienia kadru i podgląd.',
    demoOriginal: 'Oryginał: 3000 x 2000 px',
    demoTarget: 'Docelowy: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram post pion · 4:5',
    dimensions: 'Wymiary w px',
    presetsLabel: 'Gotowe formaty',
    shapesLabel: 'Kształty kadru',
    zoom: 'Przybliżenie',
    position: 'Pozycja',
    gridColor: 'Kolor siatki',
    width: 'Szerokość (px)',
    height: 'Wysokość (px)',
    keepAspectRatio: 'Zachowaj proporcje (automatyczny drugi wymiar)',
    category: 'Kategoria',
    format: 'Format',
    selectPreset: 'Wybierz format',
    rectAspect: 'Proporcje prostokąta',
    cropZoom: 'Przybliżenie kadru',
    horizontal: 'Poziom (X)',
    vertical: 'Pion (Y)',
    centerHorizontal: 'Wyśrodkuj poziomo',
    centerVertical: 'Wyśrodkuj pionowo',
    centerCrop: 'Wyśrodkuj kadr',
    cropPreview: 'Podgląd kadru',
    cropPreviewHelper:
      'Jasny obszar pokazuje dokładny kadr, który zostanie zapisany. Zapisany plik będzie miał dokładnie ten rozmiar i fragment obrazu, który widzisz w środku. Dla kształtu koła plik będzie miał przezroczyste tło poza kształtem (PNG / WebP).',
    shapes: {
      rect: 'Prostokąt',
      square: 'Kwadrat',
      circle: 'Koło',
    },
    gridColors: {
      emerald: 'Zielony',
      white: 'Biały',
      black: 'Czarny',
      red: 'Czerwony',
      yellow: 'Żółty',
    },
    categories: {
      social: 'media społecznościowe',
      web: 'WWW',
    },
    presets: {
      igSquare: 'Instagram - post kwadrat (1080x1080)',
      igPortrait: 'Instagram - post pion (1080x1350)',
      igStory: 'Instagram - story / reels (1080x1920)',
      fbPost: 'Facebook - post (1200x630)',
      fbCover: 'Facebook - cover strony (820x360)',
      liPost: 'LinkedIn - post (1200x1200)',
      liBanner: 'LinkedIn - baner profilu (1584x396)',
      ogImage: 'OG image (1200x630)',
      cover: 'Grafika do artykułu (1600x900)',
      banner: 'Baner strony (1920x600)',
      thumb: 'Miniatura artykułu (800x600)',
      hero: 'Hero sekcji (1920x1080)',
      bg: 'Tło sekcji (1920x1280)',
    },
    previewAlt: 'Podgląd',
  },
  en: {
    imageLoadError: 'Failed to load the image.',
    canvasNotSupported: 'Your browser does not support 2D canvas.',
    fileGenerationError: 'Failed to generate the file.',
    addImageFirst: 'Add an image first.',
    setValidDimensions: 'Set valid target dimensions.',
    addImage: 'Add image',
    dragDropImage: 'Drag and drop an image here',
    clickToSelect: 'or click to select a file from your device',
    supportedFormats: 'Supported: JPG, PNG, WebP',
    currentFile: 'Current file:',
    imageParams: 'Image parameters',
    noData: 'No data - add an image.',
    original: 'Original:',
    aspectRatio: 'Aspect ratio:',
    target: 'Target:',
    inputFormat: 'Input format:',
    outputFormat: 'Output format:',
    shape: 'Shape:',
    sourceFile: 'Source file:',
    estimatedResult: 'Estimated result:',
    convertAndDownload: 'Convert and download',
    quality: 'Quality (JPG/WEBP)',
    qualityHelper: 'Lower value means smaller file but lower image quality. For social media, the optimal value is 70–85%.',
    processing: 'Processing…',
    resizeAndDownload: 'Resize and download',
    cropTools: 'Crop tools',
    addImageFirstHelper: 'First add an image on the left. Then crop settings and preview will appear.',
    demoOriginal: 'Original: 3000 x 2000 px',
    demoTarget: 'Target: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram portrait post · 4:5',
    dimensions: 'Dimensions in px',
    presetsLabel: 'Presets',
    shapesLabel: 'Crop shapes',
    zoom: 'Zoom',
    position: 'Position',
    gridColor: 'Grid color',
    width: 'Width (px)',
    height: 'Height (px)',
    keepAspectRatio: 'Keep aspect ratio (auto second dimension)',
    category: 'Category',
    format: 'Format',
    selectPreset: 'Select format',
    rectAspect: 'Rectangle aspect ratio',
    cropZoom: 'Crop zoom',
    horizontal: 'Horizontal (X)',
    vertical: 'Vertical (Y)',
    centerHorizontal: 'Center horizontally',
    centerVertical: 'Center vertically',
    centerCrop: 'Center crop',
    cropPreview: 'Crop preview',
    cropPreviewHelper:
      'The bright area shows the exact crop that will be saved. The saved file will have exactly the size and image fragment you see in the center. For circle shape the file will have a transparent background outside the shape (PNG / WebP).',
    shapes: {
      rect: 'Rectangle',
      square: 'Square',
      circle: 'Circle',
    },
    gridColors: {
      emerald: 'Green',
      white: 'White',
      black: 'Black',
      red: 'Red',
      yellow: 'Yellow',
    },
    categories: {
      social: 'social media',
      web: 'web',
    },
    presets: {
      igSquare: 'Instagram - square post (1080x1080)',
      igPortrait: 'Instagram - portrait post (1080x1350)',
      igStory: 'Instagram - story / reels (1080x1920)',
      fbPost: 'Facebook - post (1200x630)',
      fbCover: 'Facebook - page cover (820x360)',
      liPost: 'LinkedIn - post (1200x1200)',
      liBanner: 'LinkedIn - profile banner (1584x396)',
      ogImage: 'OG image (1200x630)',
      cover: 'Article cover (1600x900)',
      banner: 'Website banner (1920x600)',
      thumb: 'Article thumbnail (800x600)',
      hero: 'Hero section (1920x1080)',
      bg: 'Section background (1920x1280)',
    },
    previewAlt: 'Preview',
  },
  de: {
    imageLoadError: 'Das Bild konnte nicht geladen werden.',
    canvasNotSupported: 'Ihr Browser unterstützt kein 2D-Canvas.',
    fileGenerationError: 'Die Datei konnte nicht generiert werden.',
    addImageFirst: 'Fügen Sie zuerst ein Bild hinzu.',
    setValidDimensions: 'Geben Sie gültige Zielmaße ein.',
    addImage: 'Bild hinzufügen',
    dragDropImage: 'Bild hierher ziehen und ablegen',
    clickToSelect: 'oder klicken, um eine Datei auszuwählen',
    supportedFormats: 'Unterstützt: JPG, PNG, WebP',
    currentFile: 'Aktuelle Datei:',
    imageParams: 'Bildparameter',
    noData: 'Keine Daten — fügen Sie ein Bild hinzu.',
    original: 'Original:',
    aspectRatio: 'Seitenverhältnis:',
    target: 'Ziel:',
    inputFormat: 'Eingabeformat:',
    outputFormat: 'Ausgabeformat:',
    shape: 'Form:',
    sourceFile: 'Quelldatei:',
    estimatedResult: 'Geschätztes Ergebnis:',
    convertAndDownload: 'Konvertieren und herunterladen',
    quality: 'Qualität (JPG/WEBP)',
    qualityHelper: 'Ein niedrigerer Wert ergibt eine kleinere Datei, aber geringere Bildqualität. Für Social Media ist 70–85\u00a0% optimal.',
    processing: 'Verarbeitung\u2026',
    resizeAndDownload: 'Größe ändern und herunterladen',
    cropTools: 'Zuschnittwerkzeuge',
    addImageFirstHelper: 'Fügen Sie zuerst links ein Bild hinzu. Dann erscheinen die Zuschnitteinstellungen und die Vorschau.',
    demoOriginal: 'Original: 3000 x 2000 px',
    demoTarget: 'Ziel: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram Hochformat · 4:5',
    dimensions: 'Maße in px',
    presetsLabel: 'Vorlagen',
    shapesLabel: 'Zuschnittsformen',
    zoom: 'Zoom',
    position: 'Position',
    gridColor: 'Rasterfarbe',
    width: 'Breite (px)',
    height: 'Höhe (px)',
    keepAspectRatio: 'Seitenverhältnis beibehalten (zweiter Wert automatisch)',
    category: 'Kategorie',
    format: 'Format',
    selectPreset: 'Vorlage wählen',
    rectAspect: 'Seitenverhältnis des Rechtecks',
    cropZoom: 'Zuschnittzoom',
    horizontal: 'Horizontal (X)',
    vertical: 'Vertikal (Y)',
    centerHorizontal: 'Horizontal zentrieren',
    centerVertical: 'Vertikal zentrieren',
    centerCrop: 'Zuschnitt zentrieren',
    cropPreview: 'Zuschnittvorschau',
    cropPreviewHelper:
      'Der helle Bereich zeigt den genauen Zuschnitt, der gespeichert wird. Die gespeicherte Datei hat genau die Größe und den Bildausschnitt, den Sie in der Mitte sehen. Bei Kreisform wird der Bereich außerhalb des Kreises transparent (PNG / WebP).',
    shapes: {
      rect: 'Rechteck',
      square: 'Quadrat',
      circle: 'Kreis',
    },
    gridColors: {
      emerald: 'Grün',
      white: 'Weiß',
      black: 'Schwarz',
      red: 'Rot',
      yellow: 'Gelb',
    },
    categories: {
      social: 'Social Media',
      web: 'Web',
    },
    presets: {
      igSquare: 'Instagram – Quadrat (1080x1080)',
      igPortrait: 'Instagram – Hochformat (1080x1350)',
      igStory: 'Instagram – Story / Reels (1080x1920)',
      fbPost: 'Facebook – Post (1200x630)',
      fbCover: 'Facebook – Seitencover (820x360)',
      liPost: 'LinkedIn – Post (1200x1200)',
      liBanner: 'LinkedIn – Profilbanner (1584x396)',
      ogImage: 'OG Image (1200x630)',
      cover: 'Artikelbild (1600x900)',
      banner: 'Website-Banner (1920x600)',
      thumb: 'Artikel-Thumbnail (800x600)',
      hero: 'Hero-Bereich (1920x1080)',
      bg: 'Hintergrundbild (1920x1280)',
    },
    previewAlt: 'Vorschau',
  },
  es: {
    imageLoadError: 'No se pudo cargar la imagen.',
    canvasNotSupported: 'Su navegador no admite canvas 2D.',
    fileGenerationError: 'No se pudo generar el archivo.',
    addImageFirst: 'Añada primero una imagen.',
    setValidDimensions: 'Establezca dimensiones de destino válidas.',
    addImage: 'Añadir imagen',
    dragDropImage: 'Arrastre y suelte una imagen aquí',
    clickToSelect: 'o haga clic para seleccionar un archivo',
    supportedFormats: 'Compatibles: JPG, PNG, WebP',
    currentFile: 'Archivo actual:',
    imageParams: 'Parámetros de imagen',
    noData: 'Sin datos \u2014 añada una imagen.',
    original: 'Original:',
    aspectRatio: 'Relación de aspecto:',
    target: 'Destino:',
    inputFormat: 'Formato de entrada:',
    outputFormat: 'Formato de salida:',
    shape: 'Forma:',
    sourceFile: 'Archivo de origen:',
    estimatedResult: 'Resultado estimado:',
    convertAndDownload: 'Convertir y descargar',
    quality: 'Calidad (JPG/WEBP)',
    qualityHelper: 'Un valor más bajo genera un archivo menor pero con menos calidad. Para redes sociales, lo óptimo es 70\u201385\u00a0%.',
    processing: 'Procesando\u2026',
    resizeAndDownload: 'Redimensionar y descargar',
    cropTools: 'Herramientas de recorte',
    addImageFirstHelper: 'Primero añada una imagen a la izquierda. Luego aparecerán los ajustes de recorte y la vista previa.',
    demoOriginal: 'Original: 3000 x 2000 px',
    demoTarget: 'Destino: 1080 x 1350 px',
    demoFormat: 'Formato: WebP',
    demoPreset: 'Instagram vertical \u00b7 4:5',
    dimensions: 'Dimensiones en px',
    presetsLabel: 'Formatos predefinidos',
    shapesLabel: 'Formas de recorte',
    zoom: 'Zoom',
    position: 'Posición',
    gridColor: 'Color de cuadrícula',
    width: 'Ancho (px)',
    height: 'Alto (px)',
    keepAspectRatio: 'Mantener relación de aspecto (segunda dimensión automática)',
    category: 'Categoría',
    format: 'Formato',
    selectPreset: 'Seleccionar formato',
    rectAspect: 'Relación de aspecto del rectángulo',
    cropZoom: 'Zoom del recorte',
    horizontal: 'Horizontal (X)',
    vertical: 'Vertical (Y)',
    centerHorizontal: 'Centrar horizontalmente',
    centerVertical: 'Centrar verticalmente',
    centerCrop: 'Centrar recorte',
    cropPreview: 'Vista previa del recorte',
    cropPreviewHelper:
      'El área iluminada muestra el recorte exacto que se guardará. El archivo guardado tendrá exactamente el tamaño y el fragmento de imagen que ve en el centro. Para la forma circular, el archivo tendrá fondo transparente fuera de la forma (PNG / WebP).',
    shapes: {
      rect: 'Rectángulo',
      square: 'Cuadrado',
      circle: 'Círculo',
    },
    gridColors: {
      emerald: 'Verde',
      white: 'Blanco',
      black: 'Negro',
      red: 'Rojo',
      yellow: 'Amarillo',
    },
    categories: {
      social: 'Redes sociales',
      web: 'Web',
    },
    presets: {
      igSquare: 'Instagram \u2013 cuadrado (1080x1080)',
      igPortrait: 'Instagram \u2013 vertical (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 publicación (1200x630)',
      fbCover: 'Facebook \u2013 portada (820x360)',
      liPost: 'LinkedIn \u2013 publicación (1200x1200)',
      liBanner: 'LinkedIn \u2013 banner de perfil (1584x396)',
      ogImage: 'Imagen OG (1200x630)',
      cover: 'Portada de artículo (1600x900)',
      banner: 'Banner del sitio web (1920x600)',
      thumb: 'Miniatura de artículo (800x600)',
      hero: 'Sección hero (1920x1080)',
      bg: 'Fondo de sección (1920x1280)',
    },
    previewAlt: 'Vista previa',
  },
  fr: {
    imageLoadError: "Impossible de charger l'image.",
    canvasNotSupported: 'Votre navigateur ne prend pas en charge le canvas 2D.',
    fileGenerationError: 'Impossible de générer le fichier.',
    addImageFirst: "Ajoutez d'abord une image.",
    setValidDimensions: 'Définissez des dimensions cibles valides.',
    addImage: 'Ajouter une image',
    dragDropImage: 'Glissez-déposez une image ici',
    clickToSelect: 'ou cliquez pour sélectionner un fichier',
    supportedFormats: 'Formats pris en charge\u00a0: JPG, PNG, WebP',
    currentFile: 'Fichier actuel\u00a0:',
    imageParams: "Paramètres de l'image",
    noData: 'Aucune donnée \u2014 ajoutez une image.',
    original: 'Original\u00a0:',
    aspectRatio: "Rapport d'aspect\u00a0:",
    target: 'Cible\u00a0:',
    inputFormat: "Format d'entrée\u00a0:",
    outputFormat: 'Format de sortie\u00a0:',
    shape: 'Forme\u00a0:',
    sourceFile: 'Fichier source\u00a0:',
    estimatedResult: 'Résultat estimé\u00a0:',
    convertAndDownload: 'Convertir et télécharger',
    quality: 'Qualité (JPG/WEBP)',
    qualityHelper: 'Une valeur plus basse donne un fichier plus léger mais de moindre qualité. Pour les réseaux sociaux, 70\u201385\u00a0% est optimal.',
    processing: 'Traitement en cours\u2026',
    resizeAndDownload: 'Redimensionner et télécharger',
    cropTools: 'Outils de recadrage',
    addImageFirstHelper: "Ajoutez d'abord une image à gauche. Les paramètres de recadrage et l'aperçu apparaîtront ensuite.",
    demoOriginal: 'Original\u00a0: 3000 x 2000 px',
    demoTarget: 'Cible\u00a0: 1080 x 1350 px',
    demoFormat: 'Format\u00a0: WebP',
    demoPreset: 'Instagram vertical \u00b7 4:5',
    dimensions: 'Dimensions en px',
    presetsLabel: 'Formats prédéfinis',
    shapesLabel: 'Formes de recadrage',
    zoom: 'Zoom',
    position: 'Position',
    gridColor: 'Couleur de la grille',
    width: 'Largeur (px)',
    height: 'Hauteur (px)',
    keepAspectRatio: "Conserver le rapport d'aspect (seconde dimension automatique)",
    category: 'Catégorie',
    format: 'Format',
    selectPreset: 'Sélectionner un format',
    rectAspect: "Rapport d'aspect du rectangle",
    cropZoom: 'Zoom du recadrage',
    horizontal: 'Horizontal (X)',
    vertical: 'Vertical (Y)',
    centerHorizontal: 'Centrer horizontalement',
    centerVertical: 'Centrer verticalement',
    centerCrop: 'Centrer le recadrage',
    cropPreview: 'Aperçu du recadrage',
    cropPreviewHelper:
      "La zone éclairée montre le recadrage exact qui sera enregistré. Le fichier aura exactement la taille et le fragment d'image visibles au centre. Pour la forme circulaire, le fichier aura un fond transparent hors de la forme (PNG / WebP).",
    shapes: {
      rect: 'Rectangle',
      square: 'Carré',
      circle: 'Cercle',
    },
    gridColors: {
      emerald: 'Vert',
      white: 'Blanc',
      black: 'Noir',
      red: 'Rouge',
      yellow: 'Jaune',
    },
    categories: {
      social: 'Réseaux sociaux',
      web: 'Web',
    },
    presets: {
      igSquare: 'Instagram \u2013 carré (1080x1080)',
      igPortrait: 'Instagram \u2013 portrait (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 publication (1200x630)',
      fbCover: 'Facebook \u2013 couverture (820x360)',
      liPost: 'LinkedIn \u2013 publication (1200x1200)',
      liBanner: 'LinkedIn \u2013 bannière de profil (1584x396)',
      ogImage: 'Image OG (1200x630)',
      cover: "Couverture d'article (1600x900)",
      banner: 'Bannière du site (1920x600)',
      thumb: "Miniature d'article (800x600)",
      hero: 'Section hero (1920x1080)',
      bg: 'Fond de section (1920x1280)',
    },
    previewAlt: 'Aperçu',
  },
  pt: {
    imageLoadError: 'Não foi possível carregar a imagem.',
    canvasNotSupported: 'O seu navegador não suporta canvas 2D.',
    fileGenerationError: 'Não foi possível gerar o ficheiro.',
    addImageFirst: 'Adicione primeiro uma imagem.',
    setValidDimensions: 'Defina dimensões de destino válidas.',
    addImage: 'Adicionar imagem',
    dragDropImage: 'Arraste e largue uma imagem aqui',
    clickToSelect: 'ou clique para selecionar um ficheiro',
    supportedFormats: 'Suportados: JPG, PNG, WebP',
    currentFile: 'Ficheiro atual:',
    imageParams: 'Parâmetros da imagem',
    noData: 'Sem dados — adicione uma imagem.',
    original: 'Original:',
    aspectRatio: 'Proporção:',
    target: 'Destino:',
    inputFormat: 'Formato de entrada:',
    outputFormat: 'Formato de saída:',
    shape: 'Forma:',
    sourceFile: 'Ficheiro de origem:',
    estimatedResult: 'Resultado estimado:',
    convertAndDownload: 'Converter e transferir',
    quality: 'Qualidade (JPG/WEBP)',
    qualityHelper: 'Um valor mais baixo gera um ficheiro menor mas com menos qualidade. Para redes sociais, o ideal é 70–85\u00a0%.',
    processing: 'A processar\u2026',
    resizeAndDownload: 'Redimensionar e transferir',
    cropTools: 'Ferramentas de recorte',
    addImageFirstHelper: 'Primeiro adicione uma imagem à esquerda. Depois aparecerão as definições de recorte e a pré-visualização.',
    demoOriginal: 'Original: 3000 x 2000 px',
    demoTarget: 'Destino: 1080 x 1350 px',
    demoFormat: 'Formato: WebP',
    demoPreset: 'Instagram vertical \u00b7 4:5',
    dimensions: 'Dimensões em px',
    presetsLabel: 'Formatos predefinidos',
    shapesLabel: 'Formas de recorte',
    zoom: 'Zoom',
    position: 'Posição',
    gridColor: 'Cor da grelha',
    width: 'Largura (px)',
    height: 'Altura (px)',
    keepAspectRatio: 'Manter proporção (segunda dimensão automática)',
    category: 'Categoria',
    format: 'Formato',
    selectPreset: 'Selecionar formato',
    rectAspect: 'Proporção do retângulo',
    cropZoom: 'Zoom do recorte',
    horizontal: 'Horizontal (X)',
    vertical: 'Vertical (Y)',
    centerHorizontal: 'Centrar horizontalmente',
    centerVertical: 'Centrar verticalmente',
    centerCrop: 'Centrar recorte',
    cropPreview: 'Pré-visualização do recorte',
    cropPreviewHelper:
      'A área iluminada mostra o recorte exato que será guardado. O ficheiro guardado terá exatamente o tamanho e o fragmento de imagem que vê no centro. Para a forma circular, o ficheiro terá fundo transparente fora da forma (PNG / WebP).',
    shapes: {
      rect: 'Retângulo',
      square: 'Quadrado',
      circle: 'Círculo',
    },
    gridColors: {
      emerald: 'Verde',
      white: 'Branco',
      black: 'Preto',
      red: 'Vermelho',
      yellow: 'Amarelo',
    },
    categories: {
      social: 'Redes sociais',
      web: 'Web',
    },
    presets: {
      igSquare: 'Instagram \u2013 quadrado (1080x1080)',
      igPortrait: 'Instagram \u2013 vertical (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 publicação (1200x630)',
      fbCover: 'Facebook \u2013 capa (820x360)',
      liPost: 'LinkedIn \u2013 publicação (1200x1200)',
      liBanner: 'LinkedIn \u2013 banner de perfil (1584x396)',
      ogImage: 'Imagem OG (1200x630)',
      cover: 'Capa de artigo (1600x900)',
      banner: 'Banner do site (1920x600)',
      thumb: 'Miniatura de artigo (800x600)',
      hero: 'Secção hero (1920x1080)',
      bg: 'Fundo de secção (1920x1280)',
    },
    previewAlt: 'Pré-visualização',
  },
  it: {
    imageLoadError: "Impossibile caricare l'immagine.",
    canvasNotSupported: 'Il tuo browser non supporta il canvas 2D.',
    fileGenerationError: 'Impossibile generare il file.',
    addImageFirst: "Aggiungi prima un'immagine.",
    setValidDimensions: 'Imposta dimensioni di destinazione valide.',
    addImage: 'Aggiungi immagine',
    dragDropImage: "Trascina e rilascia un'immagine qui",
    clickToSelect: 'oppure clicca per selezionare un file',
    supportedFormats: 'Supportati: JPG, PNG, WebP',
    currentFile: 'File attuale:',
    imageParams: "Parametri dell'immagine",
    noData: "Nessun dato \u2014 aggiungi un'immagine.",
    original: 'Originale:',
    aspectRatio: 'Proporzioni:',
    target: 'Destinazione:',
    inputFormat: 'Formato di ingresso:',
    outputFormat: 'Formato di uscita:',
    shape: 'Forma:',
    sourceFile: 'File di origine:',
    estimatedResult: 'Risultato stimato:',
    convertAndDownload: 'Converti e scarica',
    quality: 'Qualit\u00e0 (JPG/WEBP)',
    qualityHelper: 'Un valore pi\u00f9 basso genera un file pi\u00f9 piccolo ma con meno qualit\u00e0. Per i social media, l\u2019ideale \u00e8 70\u201385\u00a0%.',
    processing: 'Elaborazione\u2026',
    resizeAndDownload: 'Ridimensiona e scarica',
    cropTools: 'Strumenti di ritaglio',
    addImageFirstHelper: "Prima aggiungi un'immagine a sinistra. Poi appariranno le impostazioni di ritaglio e l'anteprima.",
    demoOriginal: 'Originale: 3000 x 2000 px',
    demoTarget: 'Destinazione: 1080 x 1350 px',
    demoFormat: 'Formato: WebP',
    demoPreset: 'Instagram verticale \u00b7 4:5',
    dimensions: 'Dimensioni in px',
    presetsLabel: 'Formati predefiniti',
    shapesLabel: 'Forme di ritaglio',
    zoom: 'Zoom',
    position: 'Posizione',
    gridColor: 'Colore griglia',
    width: 'Larghezza (px)',
    height: 'Altezza (px)',
    keepAspectRatio: 'Mantieni proporzioni (seconda dimensione automatica)',
    category: 'Categoria',
    format: 'Formato',
    selectPreset: 'Seleziona formato',
    rectAspect: 'Proporzioni del rettangolo',
    cropZoom: 'Zoom del ritaglio',
    horizontal: 'Orizzontale (X)',
    vertical: 'Verticale (Y)',
    centerHorizontal: 'Centra orizzontalmente',
    centerVertical: 'Centra verticalmente',
    centerCrop: 'Centra ritaglio',
    cropPreview: 'Anteprima del ritaglio',
    cropPreviewHelper:
      "L'area illuminata mostra il ritaglio esatto che verr\u00e0 salvato. Il file salvato avr\u00e0 esattamente le dimensioni e il frammento di immagine visibili al centro. Per la forma circolare, il file avr\u00e0 sfondo trasparente al di fuori della forma (PNG / WebP).",
    shapes: {
      rect: 'Rettangolo',
      square: 'Quadrato',
      circle: 'Cerchio',
    },
    gridColors: {
      emerald: 'Verde',
      white: 'Bianco',
      black: 'Nero',
      red: 'Rosso',
      yellow: 'Giallo',
    },
    categories: {
      social: 'Social media',
      web: 'Web',
    },
    presets: {
      igSquare: 'Instagram \u2013 quadrato (1080x1080)',
      igPortrait: 'Instagram \u2013 verticale (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 post (1200x630)',
      fbCover: 'Facebook \u2013 copertina (820x360)',
      liPost: 'LinkedIn \u2013 post (1200x1200)',
      liBanner: 'LinkedIn \u2013 banner profilo (1584x396)',
      ogImage: 'Immagine OG (1200x630)',
      cover: 'Copertina articolo (1600x900)',
      banner: 'Banner sito (1920x600)',
      thumb: 'Miniatura articolo (800x600)',
      hero: 'Sezione hero (1920x1080)',
      bg: 'Sfondo sezione (1920x1280)',
    },
    previewAlt: 'Anteprima',
  },
  ro: {
    imageLoadError: 'Nu s-a putut incarca imaginea.',
    canvasNotSupported: 'Browserul dvs. nu accepta canvas 2D.',
    fileGenerationError: 'Nu s-a putut genera fisierul.',
    addImageFirst: 'Adaugati mai intai o imagine.',
    setValidDimensions: 'Setati dimensiuni tinta valide.',
    addImage: 'Adaugati imagine',
    dragDropImage: 'Trageti si plasati o imagine aici',
    clickToSelect: 'sau faceti clic pentru a selecta un fisier',
    supportedFormats: 'Acceptate: JPG, PNG, WebP',
    currentFile: 'Fisier curent:',
    imageParams: 'Parametrii imaginii',
    noData: 'Fara date - adaugati o imagine.',
    original: 'Original:',
    aspectRatio: 'Raport de aspect:',
    target: 'Tinta:',
    inputFormat: 'Format de intrare:',
    outputFormat: 'Format de iesire:',
    shape: 'Forma:',
    sourceFile: 'Fisier sursa:',
    estimatedResult: 'Rezultat estimat:',
    convertAndDownload: 'Convertiti si descarcati',
    quality: 'Calitate (JPG/WEBP)',
    qualityHelper: 'O valoare mai mica inseamna un fisier mai mic, dar o calitate mai scazuta. Pentru retelele sociale, valoarea optima este 70\u201385%.',
    processing: 'Procesare\u2026',
    resizeAndDownload: 'Redimensionati si descarcati',
    cropTools: 'Instrumente de decupare',
    addImageFirstHelper: 'Mai intai adaugati o imagine in stanga. Apoi vor aparea setarile de decupare si previzualizarea.',
    demoOriginal: 'Original: 3000 x 2000 px',
    demoTarget: 'Tinta: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram portret \u00b7 4:5',
    dimensions: 'Dimensiuni in px',
    presetsLabel: 'Formate predefinite',
    shapesLabel: 'Forme de decupare',
    zoom: 'Zoom',
    position: 'Pozitie',
    gridColor: 'Culoare grila',
    width: 'Latime (px)',
    height: 'Inaltime (px)',
    keepAspectRatio: 'Pastrati raportul de aspect (a doua dimensiune automata)',
    category: 'Categorie',
    format: 'Format',
    selectPreset: 'Selectati formatul',
    rectAspect: 'Raportul de aspect al dreptunghiului',
    cropZoom: 'Zoom decupare',
    horizontal: 'Orizontal (X)',
    vertical: 'Vertical (Y)',
    centerHorizontal: 'Centrati orizontal',
    centerVertical: 'Centrati vertical',
    centerCrop: 'Centrati decuparea',
    cropPreview: 'Previzualizare decupare',
    cropPreviewHelper:
      'Zona luminoasa arata decupajul exact care va fi salvat. Fisierul salvat va avea exact dimensiunea si fragmentul de imagine pe care il vedeti in centru. Pentru forma de cerc, fisierul va avea un fundal transparent in afara formei (PNG / WebP).',
    shapes: {
      rect: 'Dreptunghi',
      square: 'Patrat',
      circle: 'Cerc',
    },
    gridColors: {
      emerald: 'Verde',
      white: 'Alb',
      black: 'Negru',
      red: 'Rosu',
      yellow: 'Galben',
    },
    categories: {
      social: 'retele sociale',
      web: 'web',
    },
    presets: {
      igSquare: 'Instagram \u2013 postare patrata (1080x1080)',
      igPortrait: 'Instagram \u2013 postare portret (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 postare (1200x630)',
      fbCover: 'Facebook \u2013 coperta paginii (820x360)',
      liPost: 'LinkedIn \u2013 postare (1200x1200)',
      liBanner: 'LinkedIn \u2013 banner profil (1584x396)',
      ogImage: 'Imagine OG (1200x630)',
      cover: 'Coperta articol (1600x900)',
      banner: 'Banner site (1920x600)',
      thumb: 'Miniatura articol (800x600)',
      hero: 'Sectiune hero (1920x1080)',
      bg: 'Fundal sectiune (1920x1280)',
    },
    previewAlt: 'Previzualizare',
  },
  nl: {
    imageLoadError: 'Kan de afbeelding niet laden.',
    canvasNotSupported: 'Uw browser ondersteunt geen 2D-canvas.',
    fileGenerationError: 'Kan het bestand niet genereren.',
    addImageFirst: 'Voeg eerst een afbeelding toe.',
    setValidDimensions: 'Stel geldige doelafmetingen in.',
    addImage: 'Afbeelding toevoegen',
    dragDropImage: 'Sleep een afbeelding hierheen',
    clickToSelect: 'of klik om een bestand te selecteren',
    supportedFormats: 'Ondersteund: JPG, PNG, WebP',
    currentFile: 'Huidig bestand:',
    imageParams: 'Afbeeldingsparameters',
    noData: 'Geen gegevens - voeg een afbeelding toe.',
    original: 'Origineel:',
    aspectRatio: 'Beeldverhouding:',
    target: 'Doel:',
    inputFormat: 'Invoerformaat:',
    outputFormat: 'Uitvoerformaat:',
    shape: 'Vorm:',
    sourceFile: 'Bronbestand:',
    estimatedResult: 'Geschat resultaat:',
    convertAndDownload: 'Converteren en downloaden',
    quality: 'Kwaliteit (JPG/WEBP)',
    qualityHelper: 'Een lagere waarde betekent een kleiner bestand maar lagere beeldkwaliteit. Voor sociale media is de optimale waarde 70\u201385%.',
    processing: 'Verwerken\u2026',
    resizeAndDownload: 'Formaat wijzigen en downloaden',
    cropTools: 'Bijsnijdgereedschap',
    addImageFirstHelper: 'Voeg eerst links een afbeelding toe. Daarna verschijnen de bijsnijdinstellingen en het voorbeeld.',
    demoOriginal: 'Origineel: 3000 x 2000 px',
    demoTarget: 'Doel: 1080 x 1350 px',
    demoFormat: 'Formaat: WebP',
    demoPreset: 'Instagram portret \u00b7 4:5',
    dimensions: 'Afmetingen in px',
    presetsLabel: 'Voorinstellingen',
    shapesLabel: 'Bijsnijdvormen',
    zoom: 'Zoom',
    position: 'Positie',
    gridColor: 'Rasterkleur',
    width: 'Breedte (px)',
    height: 'Hoogte (px)',
    keepAspectRatio: 'Beeldverhouding behouden (automatische tweede dimensie)',
    category: 'Categorie',
    format: 'Formaat',
    selectPreset: 'Formaat selecteren',
    rectAspect: 'Beeldverhouding rechthoek',
    cropZoom: 'Bijsnijdzoom',
    horizontal: 'Horizontaal (X)',
    vertical: 'Verticaal (Y)',
    centerHorizontal: 'Horizontaal centreren',
    centerVertical: 'Verticaal centreren',
    centerCrop: 'Bijsnijden centreren',
    cropPreview: 'Bijsnijdvoorbeeld',
    cropPreviewHelper:
      'Het heldere gebied toont het exacte bijsnijdresultaat dat wordt opgeslagen. Het opgeslagen bestand heeft precies het formaat en het beeldfragment dat u in het midden ziet. Bij een cirkelvorm heeft het bestand een transparante achtergrond buiten de vorm (PNG / WebP).',
    shapes: {
      rect: 'Rechthoek',
      square: 'Vierkant',
      circle: 'Cirkel',
    },
    gridColors: {
      emerald: 'Groen',
      white: 'Wit',
      black: 'Zwart',
      red: 'Rood',
      yellow: 'Geel',
    },
    categories: {
      social: 'sociale media',
      web: 'web',
    },
    presets: {
      igSquare: 'Instagram \u2013 vierkant (1080x1080)',
      igPortrait: 'Instagram \u2013 portret (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 bericht (1200x630)',
      fbCover: 'Facebook \u2013 omslagfoto (820x360)',
      liPost: 'LinkedIn \u2013 bericht (1200x1200)',
      liBanner: 'LinkedIn \u2013 profielbanner (1584x396)',
      ogImage: 'OG-afbeelding (1200x630)',
      cover: 'Artikelomslag (1600x900)',
      banner: 'Websitebanner (1920x600)',
      thumb: 'Artikelminiatuur (800x600)',
      hero: 'Hero-sectie (1920x1080)',
      bg: 'Sectieachtergrond (1920x1280)',
    },
    previewAlt: 'Voorbeeld',
  },
  hu: {
    imageLoadError: 'Nem sikerult betolteni a kepet.',
    canvasNotSupported: 'A bongeszo nem tamogatja a 2D vaszon funkcioit.',
    fileGenerationError: 'Nem sikerult a fajl generalasa.',
    addImageFirst: 'Eloszor adjon hozza egy kepet.',
    setValidDimensions: 'Allitson be ervenyes celmereteket.',
    addImage: 'Kep hozzaadasa',
    dragDropImage: 'Huzzon ide egy kepet',
    clickToSelect: 'vagy kattintson egy fajl kivalasztasahoz',
    supportedFormats: 'Tamogatott: JPG, PNG, WebP',
    currentFile: 'Aktualis fajl:',
    imageParams: 'Kep parameterei',
    noData: 'Nincs adat \u2014 adjon hozza egy kepet.',
    original: 'Eredeti:',
    aspectRatio: 'Kepoldalarany:',
    target: 'Cel:',
    inputFormat: 'Bemeneti formatum:',
    outputFormat: 'Kimeneti formatum:',
    shape: 'Alak:',
    sourceFile: 'Forrasfajl:',
    estimatedResult: 'Becsult eredmeny:',
    convertAndDownload: 'Konvertalas es letoltes',
    quality: 'Minoseg (JPG/WEBP)',
    qualityHelper: 'Az alacsonyabb ertek kisebb fajlt eredmenyez, de gyengebb kepminoseget. A kozossegi mediahoz az optimalis ertek 70\u201385%.',
    processing: 'Feldolgozas\u2026',
    resizeAndDownload: 'Atmeretezem es letoltem',
    cropTools: 'Kivagasi eszkozok',
    addImageFirstHelper: 'Eloszor adjon hozza egy kepet bal oldalon. Ezutan megjelennek a kivagasi beallitasok es az elonezet.',
    demoOriginal: 'Eredeti: 3000 x 2000 px',
    demoTarget: 'Cel: 1080 x 1350 px',
    demoFormat: 'Formatum: WebP',
    demoPreset: 'Instagram allo \u00b7 4:5',
    dimensions: 'Meretek pixelben',
    presetsLabel: 'Elore beallitott formak',
    shapesLabel: 'Kivagasi formak',
    zoom: 'Nagyitas',
    position: 'Pozicio',
    gridColor: 'Racs szine',
    width: 'Szelesseg (px)',
    height: 'Magassag (px)',
    keepAspectRatio: 'Kepoldalarany megtartasa (automatikus masodik meret)',
    category: 'Kategoria',
    format: 'Formatum',
    selectPreset: 'Formatum kivalasztasa',
    rectAspect: 'Teglalap kepoldalaranya',
    cropZoom: 'Kivagasi nagyitas',
    horizontal: 'Vizszintes (X)',
    vertical: 'Fuggoleges (Y)',
    centerHorizontal: 'Kozepre vizszintesen',
    centerVertical: 'Kozepre fuggolegesem',
    centerCrop: 'Kivagas kozepre',
    cropPreview: 'Kivagas elonezete',
    cropPreviewHelper:
      'A vilagos terulet a pontos kivagast mutatja, amely mentesre kerul. A mentett fajl pontosan azzal a merettel es keptoredekkel rendelkezik, amelyet kozepen lat. Kor alak eseten a fajl atlatszo hatteret kap a forman kivul (PNG / WebP).',
    shapes: {
      rect: 'Teglalap',
      square: 'Negyzet',
      circle: 'Kor',
    },
    gridColors: {
      emerald: 'Zold',
      white: 'Feher',
      black: 'Fekete',
      red: 'Piros',
      yellow: 'Sarga',
    },
    categories: {
      social: 'kozossegi media',
      web: 'web',
    },
    presets: {
      igSquare: 'Instagram \u2013 negyzetes (1080x1080)',
      igPortrait: 'Instagram \u2013 allo (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 bejegyzes (1200x630)',
      fbCover: 'Facebook \u2013 boritokep (820x360)',
      liPost: 'LinkedIn \u2013 bejegyzes (1200x1200)',
      liBanner: 'LinkedIn \u2013 profilbanner (1584x396)',
      ogImage: 'OG kep (1200x630)',
      cover: 'Cikk boritokep (1600x900)',
      banner: 'Weboldal banner (1920x600)',
      thumb: 'Cikk belyegkep (800x600)',
      hero: 'Hero szekcios (1920x1080)',
      bg: 'Szekcios hatter (1920x1280)',
    },
    previewAlt: 'Elonezet',
  },
  id: {
    imageLoadError: 'Gagal memuat gambar.',
    canvasNotSupported: 'Browser Anda tidak mendukung canvas 2D.',
    fileGenerationError: 'Gagal menghasilkan file.',
    addImageFirst: 'Tambahkan gambar terlebih dahulu.',
    setValidDimensions: 'Atur dimensi target yang valid.',
    addImage: 'Tambah gambar',
    dragDropImage: 'Seret dan lepas gambar di sini',
    clickToSelect: 'atau klik untuk memilih file',
    supportedFormats: 'Didukung: JPG, PNG, WebP',
    currentFile: 'File saat ini:',
    imageParams: 'Parameter gambar',
    noData: 'Tidak ada data - tambahkan gambar.',
    original: 'Asli:',
    aspectRatio: 'Rasio aspek:',
    target: 'Target:',
    inputFormat: 'Format input:',
    outputFormat: 'Format output:',
    shape: 'Bentuk:',
    sourceFile: 'File sumber:',
    estimatedResult: 'Hasil perkiraan:',
    convertAndDownload: 'Konversi dan unduh',
    quality: 'Kualitas (JPG/WEBP)',
    qualityHelper: 'Nilai lebih rendah berarti file lebih kecil tetapi kualitas gambar lebih rendah. Untuk media sosial, nilai optimal adalah 70\u201385%.',
    processing: 'Memproses\u2026',
    resizeAndDownload: 'Ubah ukuran dan unduh',
    cropTools: 'Alat potong',
    addImageFirstHelper: 'Tambahkan gambar di sebelah kiri terlebih dahulu. Kemudian pengaturan potong dan pratinjau akan muncul.',
    demoOriginal: 'Asli: 3000 x 2000 px',
    demoTarget: 'Target: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram potret \u00b7 4:5',
    dimensions: 'Dimensi dalam px',
    presetsLabel: 'Preset',
    shapesLabel: 'Bentuk potong',
    zoom: 'Zoom',
    position: 'Posisi',
    gridColor: 'Warna grid',
    width: 'Lebar (px)',
    height: 'Tinggi (px)',
    keepAspectRatio: 'Pertahankan rasio aspek (dimensi kedua otomatis)',
    category: 'Kategori',
    format: 'Format',
    selectPreset: 'Pilih format',
    rectAspect: 'Rasio aspek persegi panjang',
    cropZoom: 'Zoom potong',
    horizontal: 'Horizontal (X)',
    vertical: 'Vertikal (Y)',
    centerHorizontal: 'Tengahkan horizontal',
    centerVertical: 'Tengahkan vertikal',
    centerCrop: 'Tengahkan potongan',
    cropPreview: 'Pratinjau potongan',
    cropPreviewHelper:
      'Area terang menunjukkan potongan tepat yang akan disimpan. File yang disimpan akan memiliki ukuran dan fragmen gambar yang Anda lihat di tengah. Untuk bentuk lingkaran, file akan memiliki latar belakang transparan di luar bentuk (PNG / WebP).',
    shapes: { rect: 'Persegi panjang', square: 'Persegi', circle: 'Lingkaran' },
    gridColors: { emerald: 'Hijau', white: 'Putih', black: 'Hitam', red: 'Merah', yellow: 'Kuning' },
    categories: { social: 'media sosial', web: 'web' },
    presets: {
      igSquare: 'Instagram \u2013 persegi (1080x1080)',
      igPortrait: 'Instagram \u2013 potret (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 postingan (1200x630)',
      fbCover: 'Facebook \u2013 sampul (820x360)',
      liPost: 'LinkedIn \u2013 postingan (1200x1200)',
      liBanner: 'LinkedIn \u2013 banner profil (1584x396)',
      ogImage: 'Gambar OG (1200x630)',
      cover: 'Sampul artikel (1600x900)',
      banner: 'Banner situs (1920x600)',
      thumb: 'Thumbnail artikel (800x600)',
      hero: 'Bagian hero (1920x1080)',
      bg: 'Latar belakang bagian (1920x1280)',
    },
    previewAlt: 'Pratinjau',
  },
  vi: {
    imageLoadError: 'Không thể tải hình ảnh.',
    canvasNotSupported: 'Trình duyệt của bạn không hỗ trợ canvas 2D.',
    fileGenerationError: 'Không thể tạo file.',
    addImageFirst: 'Thêm hình ảnh trước.',
    setValidDimensions: 'Đặt kích thước mục tiêu hợp lệ.',
    addImage: 'Thêm hình ảnh',
    dragDropImage: 'Kéo và thả hình ảnh vào đây',
    clickToSelect: 'hoặc nhấn để chọn file',
    supportedFormats: 'Hỗ trợ: JPG, PNG, WebP',
    currentFile: 'File hiện tại:',
    imageParams: 'Thông số hình ảnh',
    noData: 'Không có dữ liệu – thêm hình ảnh.',
    original: 'Gốc:',
    aspectRatio: 'Tỉ lệ khung hình:',
    target: 'Mục tiêu:',
    inputFormat: 'Định dạng đầu vào:',
    outputFormat: 'Định dạng đầu ra:',
    shape: 'Hình dạng:',
    sourceFile: 'File nguồn:',
    estimatedResult: 'Kết quả ước tính:',
    convertAndDownload: 'Chuyển đổi và tải xuống',
    quality: 'Chất lượng (JPG/WEBP)',
    qualityHelper: 'Giá trị thấp hơn nghĩa là file nhỏ hơn nhưng chất lượng hình ảnh thấp hơn. Cho mạng xã hội, giá trị tối ưu là 70–85%.',
    processing: 'Đang xử lý…',
    resizeAndDownload: 'Thay đổi kích thước và tải xuống',
    cropTools: 'Công cụ cắt',
    addImageFirstHelper: 'Thêm hình ảnh bên trái trước. Sau đó cài đặt cắt và xem trước sẽ xuất hiện.',
    demoOriginal: 'Gốc: 3000 x 2000 px',
    demoTarget: 'Mục tiêu: 1080 x 1350 px',
    demoFormat: 'Định dạng: WebP',
    demoPreset: 'Instagram dọc · 4:5',
    dimensions: 'Kích thước tính bằng px',
    presetsLabel: 'Cài đặt sẵn',
    shapesLabel: 'Hình dạng cắt',
    zoom: 'Phóng to',
    position: 'Vị trí',
    gridColor: 'Màu lưới',
    width: 'Chiều rộng (px)',
    height: 'Chiều cao (px)',
    keepAspectRatio: 'Giữ tỉ lệ khung hình (kích thước thứ hai tự động)',
    category: 'Danh mục',
    format: 'Định dạng',
    selectPreset: 'Chọn định dạng',
    rectAspect: 'Tỉ lệ khung hình chữ nhật',
    cropZoom: 'Phóng to cắt',
    horizontal: 'Ngang (X)',
    vertical: 'Dọc (Y)',
    centerHorizontal: 'Căn giữa ngang',
    centerVertical: 'Căn giữa dọc',
    centerCrop: 'Căn giữa cắt',
    cropPreview: 'Xem trước cắt',
    cropPreviewHelper:
      'Vùng sáng cho thấy phần cắt chính xác sẽ được lưu. File được lưu sẽ có kích thước và phần hình ảnh bạn thấy ở giữa. Với hình tròn, file sẽ có nền trong suốt bên ngoài hình dạng (PNG / WebP).',
    shapes: { rect: 'Hình chữ nhật', square: 'Hình vuông', circle: 'Hình tròn' },
    gridColors: { emerald: 'Xanh lá', white: 'Trắng', black: 'Đen', red: 'Đỏ', yellow: 'Vàng' },
    categories: { social: 'mạng xã hội', web: 'web' },
    presets: {
      igSquare: 'Instagram – vuông (1080x1080)',
      igPortrait: 'Instagram – dọc (1080x1350)',
      igStory: 'Instagram – story / reels (1080x1920)',
      fbPost: 'Facebook – bài đăng (1200x630)',
      fbCover: 'Facebook – ảnh bìa (820x360)',
      liPost: 'LinkedIn – bài đăng (1200x1200)',
      liBanner: 'LinkedIn – banner hồ sơ (1584x396)',
      ogImage: 'Hình OG (1200x630)',
      cover: 'Ảnh bìa bài viết (1600x900)',
      banner: 'Banner trang web (1920x600)',
      thumb: 'Hình thu nhỏ bài viết (800x600)',
      hero: 'Phần hero (1920x1080)',
      bg: 'Nền phần (1920x1280)',
    },
    previewAlt: 'Xem trước',
  },
  tr: {
    imageLoadError: 'Görsel yüklenemedi.',
    canvasNotSupported: 'Tarayıcınız 2D canvas desteklemiyor.',
    fileGenerationError: 'Dosya oluşturulamadı.',
    addImageFirst: 'Önce bir görsel ekleyin.',
    setValidDimensions: 'Geçerli hedef boyutları ayarlayın.',
    addImage: 'Görsel ekle',
    dragDropImage: 'Bir görseli buraya sürükleyip bırakın',
    clickToSelect: 'veya bir dosya seçmek için tıklayın',
    supportedFormats: 'Desteklenen: JPG, PNG, WebP',
    currentFile: 'Mevcut dosya:',
    imageParams: 'Görsel parametreleri',
    noData: 'Veri yok – bir görsel ekleyin.',
    original: 'Orijinal:',
    aspectRatio: 'En boy oranı:',
    target: 'Hedef:',
    inputFormat: 'Giriş formatı:',
    outputFormat: 'Çıkış formatı:',
    shape: 'Şekil:',
    sourceFile: 'Kaynak dosya:',
    estimatedResult: 'Tahmini sonuç:',
    convertAndDownload: 'Dönüştür ve indir',
    quality: 'Kalite (JPG/WEBP)',
    qualityHelper: 'Düşük değer daha küçük dosya ama daha düşük görsel kalitesi demektir. Sosyal medya için ideal değer 70–85% arasıdır.',
    processing: 'İşleniyor…',
    resizeAndDownload: 'Boyutlandır ve indir',
    cropTools: 'Kırpma araçları',
    addImageFirstHelper: 'Önce sol tarafa bir görsel ekleyin. Ardından kırpma ayarları ve önizleme görünecektir.',
    demoOriginal: 'Orijinal: 3000 x 2000 px',
    demoTarget: 'Hedef: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram dikey · 4:5',
    dimensions: 'Piksel cinsinden boyutlar',
    presetsLabel: 'Ön ayarlar',
    shapesLabel: 'Kırpma şekilleri',
    zoom: 'Yakınlaştırma',
    position: 'Konum',
    gridColor: 'Izgara rengi',
    width: 'Genişlik (px)',
    height: 'Yükseklik (px)',
    keepAspectRatio: 'En boy oranını koru (otomatik ikinci boyut)',
    category: 'Kategori',
    format: 'Format',
    selectPreset: 'Format seç',
    rectAspect: 'Dikdörtgen en boy oranı',
    cropZoom: 'Kırpma yakınlaştırma',
    horizontal: 'Yatay (X)',
    vertical: 'Dikey (Y)',
    centerHorizontal: 'Yatay ortala',
    centerVertical: 'Dikey ortala',
    centerCrop: 'Kırpmayı ortala',
    cropPreview: 'Kırpma önizleme',
    cropPreviewHelper:
      'Aydınlık alan kaydedilecek tam kırpmayı gösterir. Kaydedilen dosya tam olarak ortada gördüğünüz boyut ve görsel parçasına sahip olacaktır. Daire şekli için dosya şeklin dışında şeffaf arka plana sahip olacaktır (PNG / WebP).',
    shapes: { rect: 'Dikdörtgen', square: 'Kare', circle: 'Daire' },
    gridColors: { emerald: 'Yeşil', white: 'Beyaz', black: 'Siyah', red: 'Kırmızı', yellow: 'Sarı' },
    categories: { social: 'sosyal medya', web: 'web' },
    presets: {
      igSquare: 'Instagram – kare (1080x1080)',
      igPortrait: 'Instagram – dikey (1080x1350)',
      igStory: 'Instagram – story / reels (1080x1920)',
      fbPost: 'Facebook – gönderi (1200x630)',
      fbCover: 'Facebook – kapak (820x360)',
      liPost: 'LinkedIn – gönderi (1200x1200)',
      liBanner: 'LinkedIn – profil banner (1584x396)',
      ogImage: 'OG görseli (1200x630)',
      cover: 'Makale kapağı (1600x900)',
      banner: 'Site banner (1920x600)',
      thumb: 'Makale küçük resmi (800x600)',
      hero: 'Hero bölümü (1920x1080)',
      bg: 'Bölüm arka planı (1920x1280)',
    },
    previewAlt: 'Önizleme',
  },
  tl: {
    imageLoadError: 'Hindi nai-load ang larawan.',
    canvasNotSupported: 'Hindi sinusuportahan ng browser mo ang 2D canvas.',
    fileGenerationError: 'Hindi nagawa ang file.',
    addImageFirst: 'Magdagdag muna ng larawan.',
    setValidDimensions: 'Magtakda ng wastong target na sukat.',
    addImage: 'Magdagdag ng larawan',
    dragDropImage: 'I-drag at i-drop ang larawan dito',
    clickToSelect: 'o mag-click para pumili ng file',
    supportedFormats: 'Sinusuportahan: JPG, PNG, WebP',
    currentFile: 'Kasalukuyang file:',
    imageParams: 'Mga parameter ng larawan',
    noData: 'Walang data \u2014 magdagdag ng larawan.',
    original: 'Orihinal:',
    aspectRatio: 'Proporsyon:',
    target: 'Target:',
    inputFormat: 'Format ng input:',
    outputFormat: 'Format ng output:',
    shape: 'Hugis:',
    sourceFile: 'Source file:',
    estimatedResult: 'Tinatayang resulta:',
    convertAndDownload: 'I-convert at i-download',
    quality: 'Kalidad (JPG/WEBP)',
    qualityHelper: 'Mas mababang halaga ay mas maliit na file ngunit mas mababang kalidad. Para sa social media, ang optimal na halaga ay 70\u201385%.',
    processing: 'Pinoproseso\u2026',
    resizeAndDownload: 'Baguhin ang sukat at i-download',
    cropTools: 'Mga tool sa pag-crop',
    addImageFirstHelper: 'Magdagdag muna ng larawan sa kaliwa. Pagkatapos ay lalabas ang mga setting ng crop at preview.',
    demoOriginal: 'Orihinal: 3000 x 2000 px',
    demoTarget: 'Target: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram portrait \u00b7 4:5',
    dimensions: 'Sukat sa px',
    presetsLabel: 'Mga preset',
    shapesLabel: 'Mga hugis ng crop',
    zoom: 'Zoom',
    position: 'Posisyon',
    gridColor: 'Kulay ng grid',
    width: 'Lapad (px)',
    height: 'Taas (px)',
    keepAspectRatio: 'Panatilihin ang proporsyon (awtomatikong pangalawang sukat)',
    category: 'Kategorya',
    format: 'Format',
    selectPreset: 'Pumili ng format',
    rectAspect: 'Proporsyon ng parihaba',
    cropZoom: 'Zoom ng crop',
    horizontal: 'Pahalang (X)',
    vertical: 'Patayo (Y)',
    centerHorizontal: 'I-center nang pahalang',
    centerVertical: 'I-center nang patayo',
    centerCrop: 'I-center ang crop',
    cropPreview: 'Preview ng crop',
    cropPreviewHelper:
      'Ang maliwanag na bahagi ang eksaktong crop na ise-save. Ang naka-save na file ay magkakaroon ng eksaktong sukat at fragment ng larawan na nakikita sa gitna. Para sa hugis na bilog, ang file ay magkakaroon ng transparent na background sa labas ng hugis (PNG / WebP).',
    shapes: { rect: 'Parihaba', square: 'Parisukat', circle: 'Bilog' },
    gridColors: { emerald: 'Berde', white: 'Puti', black: 'Itim', red: 'Pula', yellow: 'Dilaw' },
    categories: { social: 'social media', web: 'web' },
    presets: {
      igSquare: 'Instagram \u2013 parisukat (1080x1080)',
      igPortrait: 'Instagram \u2013 portrait (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 post (1200x630)',
      fbCover: 'Facebook \u2013 cover (820x360)',
      liPost: 'LinkedIn \u2013 post (1200x1200)',
      liBanner: 'LinkedIn \u2013 profile banner (1584x396)',
      ogImage: 'OG image (1200x630)',
      cover: 'Cover ng artikulo (1600x900)',
      banner: 'Banner ng website (1920x600)',
      thumb: 'Thumbnail ng artikulo (800x600)',
      hero: 'Hero section (1920x1080)',
      bg: 'Background ng section (1920x1280)',
    },
    previewAlt: 'Preview',
  },
  sw: {
    imageLoadError: 'Imeshindwa kupakia picha.',
    canvasNotSupported: 'Kivinjari chako hakitumii canvas ya 2D.',
    fileGenerationError: 'Imeshindwa kutengeneza faili.',
    addImageFirst: 'Ongeza picha kwanza.',
    setValidDimensions: 'Weka vipimo halali vya lengo.',
    addImage: 'Ongeza picha',
    dragDropImage: 'Buruta na udondoshe picha hapa',
    clickToSelect: 'au bofya kuchagua faili',
    supportedFormats: 'Zinazotumika: JPG, PNG, WebP',
    currentFile: 'Faili ya sasa:',
    imageParams: 'Vigezo vya picha',
    noData: 'Hakuna data \u2014 ongeza picha.',
    original: 'Asili:',
    aspectRatio: 'Uwiano wa pande:',
    target: 'Lengo:',
    inputFormat: 'Muundo wa kuingiza:',
    outputFormat: 'Muundo wa kutoa:',
    shape: 'Umbo:',
    sourceFile: 'Faili chanzo:',
    estimatedResult: 'Matokeo ya kukadiriwa:',
    convertAndDownload: 'Badilisha na pakua',
    quality: 'Ubora (JPG/WEBP)',
    qualityHelper: 'Thamani ya chini inamaanisha faili ndogo lakini ubora wa chini wa picha. Kwa mitandao ya kijamii, thamani bora ni 70\u201385%.',
    processing: 'Inashughulika\u2026',
    resizeAndDownload: 'Badilisha ukubwa na pakua',
    cropTools: 'Zana za kukata',
    addImageFirstHelper: 'Kwanza ongeza picha upande wa kushoto. Kisha mipangilio ya kukata na hakikisho vitaonekana.',
    demoOriginal: 'Asili: 3000 x 2000 px',
    demoTarget: 'Lengo: 1080 x 1350 px',
    demoFormat: 'Muundo: WebP',
    demoPreset: 'Instagram wima \u00b7 4:5',
    dimensions: 'Vipimo kwa px',
    presetsLabel: 'Mipangilio tayari',
    shapesLabel: 'Maumbo ya kukata',
    zoom: 'Kukuza',
    position: 'Nafasi',
    gridColor: 'Rangi ya gridi',
    width: 'Upana (px)',
    height: 'Urefu (px)',
    keepAspectRatio: 'Hifadhi uwiano wa pande (kipimo cha pili kiotomatiki)',
    category: 'Kategoria',
    format: 'Muundo',
    selectPreset: 'Chagua muundo',
    rectAspect: 'Uwiano wa pande za mstatili',
    cropZoom: 'Kukuza kukata',
    horizontal: 'Mlalo (X)',
    vertical: 'Wima (Y)',
    centerHorizontal: 'Katikisha mlalo',
    centerVertical: 'Katikisha wima',
    centerCrop: 'Katikisha kukata',
    cropPreview: 'Hakikisho la kukata',
    cropPreviewHelper:
      'Eneo angavu linaonyesha sehemu halisi itakayohifadhiwa. Faili itakayohifadhiwa itakuwa na ukubwa na sehemu ya picha unayoiona katikati. Kwa umbo la duara, faili itakuwa na mandharinyuma ya uwazi nje ya umbo (PNG / WebP).',
    shapes: { rect: 'Mstatili', square: 'Mraba', circle: 'Duara' },
    gridColors: { emerald: 'Kijani', white: 'Nyeupe', black: 'Nyeusi', red: 'Nyekundu', yellow: 'Njano' },
    categories: { social: 'mitandao ya kijamii', web: 'wavuti' },
    presets: {
      igSquare: 'Instagram \u2013 mraba (1080x1080)',
      igPortrait: 'Instagram \u2013 wima (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 chapisho (1200x630)',
      fbCover: 'Facebook \u2013 jalada (820x360)',
      liPost: 'LinkedIn \u2013 chapisho (1200x1200)',
      liBanner: 'LinkedIn \u2013 bango la wasifu (1584x396)',
      ogImage: 'Picha ya OG (1200x630)',
      cover: 'Jalada la makala (1600x900)',
      banner: 'Bango la tovuti (1920x600)',
      thumb: 'Picha ndogo ya makala (800x600)',
      hero: 'Sehemu ya hero (1920x1080)',
      bg: 'Mandharinyuma ya sehemu (1920x1280)',
    },
    previewAlt: 'Hakikisho',
  },
  ms: {
    imageLoadError: 'Gagal memuatkan imej.',
    canvasNotSupported: 'Pelayar anda tidak menyokong kanvas 2D.',
    fileGenerationError: 'Gagal menjana fail.',
    addImageFirst: 'Tambah imej dahulu.',
    setValidDimensions: 'Tetapkan dimensi sasaran yang sah.',
    addImage: 'Tambah imej',
    dragDropImage: 'Seret dan lepaskan imej di sini',
    clickToSelect: 'atau klik untuk memilih fail',
    supportedFormats: 'Disokong: JPG, PNG, WebP',
    currentFile: 'Fail semasa:',
    imageParams: 'Parameter imej',
    noData: 'Tiada data \u2014 tambah imej.',
    original: 'Asal:',
    aspectRatio: 'Nisbah aspek:',
    target: 'Sasaran:',
    inputFormat: 'Format input:',
    outputFormat: 'Format output:',
    shape: 'Bentuk:',
    sourceFile: 'Fail sumber:',
    estimatedResult: 'Anggaran hasil:',
    convertAndDownload: 'Tukar dan muat turun',
    quality: 'Kualiti (JPG/WEBP)',
    qualityHelper: 'Nilai rendah bermakna fail lebih kecil tetapi kualiti imej lebih rendah. Untuk media sosial, nilai optimum ialah 70\u201385%.',
    processing: 'Memproses\u2026',
    resizeAndDownload: 'Ubah saiz dan muat turun',
    cropTools: 'Alat pangkas',
    addImageFirstHelper: 'Tambah imej di sebelah kiri dahulu. Kemudian tetapan pangkas dan pratonton akan muncul.',
    demoOriginal: 'Asal: 3000 x 2000 px',
    demoTarget: 'Sasaran: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram potret \u00b7 4:5',
    dimensions: 'Dimensi dalam px',
    presetsLabel: 'Pratetap',
    shapesLabel: 'Bentuk pangkas',
    zoom: 'Zum',
    position: 'Posisi',
    gridColor: 'Warna grid',
    width: 'Lebar (px)',
    height: 'Tinggi (px)',
    keepAspectRatio: 'Kekalkan nisbah aspek (dimensi kedua automatik)',
    category: 'Kategori',
    format: 'Format',
    selectPreset: 'Pilih format',
    rectAspect: 'Nisbah aspek segi empat tepat',
    cropZoom: 'Zum pangkas',
    horizontal: 'Mendatar (X)',
    vertical: 'Menegak (Y)',
    centerHorizontal: 'Tengahkan mendatar',
    centerVertical: 'Tengahkan menegak',
    centerCrop: 'Tengahkan pangkas',
    cropPreview: 'Pratonton pangkas',
    cropPreviewHelper:
      'Kawasan terang menunjukkan pangkasan tepat yang akan disimpan. Fail yang disimpan akan mempunyai saiz dan serpihan imej yang anda lihat di tengah. Untuk bentuk bulat, fail akan mempunyai latar belakang lutsinar di luar bentuk (PNG / WebP).',
    shapes: { rect: 'Segi empat tepat', square: 'Segi empat sama', circle: 'Bulatan' },
    gridColors: { emerald: 'Hijau', white: 'Putih', black: 'Hitam', red: 'Merah', yellow: 'Kuning' },
    categories: { social: 'media sosial', web: 'web' },
    presets: {
      igSquare: 'Instagram \u2013 segi empat (1080x1080)',
      igPortrait: 'Instagram \u2013 potret (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 siaran (1200x630)',
      fbCover: 'Facebook \u2013 muka depan (820x360)',
      liPost: 'LinkedIn \u2013 siaran (1200x1200)',
      liBanner: 'LinkedIn \u2013 sepanduk profil (1584x396)',
      ogImage: 'Imej OG (1200x630)',
      cover: 'Muka depan artikel (1600x900)',
      banner: 'Sepanduk laman web (1920x600)',
      thumb: 'Lakaran kecil artikel (800x600)',
      hero: 'Bahagian hero (1920x1080)',
      bg: 'Latar belakang bahagian (1920x1280)',
    },
    previewAlt: 'Pratonton',
  },
  cs: {
    imageLoadError: 'Nepoda\u0159ilo se na\u010d\u00edst obr\u00e1zek.',
    canvasNotSupported: 'V\u00e1\u0161 prohl\u00ed\u017ee\u010d nepodporuje 2D canvas.',
    fileGenerationError: 'Nepoda\u0159ilo se vygenerovat soubor.',
    addImageFirst: 'Nejprve p\u0159idejte obr\u00e1zek.',
    setValidDimensions: 'Nastavte platn\u00e9 c\u00edlov\u00e9 rozm\u011bry.',
    addImage: 'P\u0159idat obr\u00e1zek',
    dragDropImage: 'P\u0159et\u00e1hn\u011bte obr\u00e1zek sem',
    clickToSelect: 'nebo klikn\u011bte pro v\u00fdb\u011br souboru',
    supportedFormats: 'Podporovan\u00e9: JPG, PNG, WebP',
    currentFile: 'Aktu\u00e1ln\u00ed soubor:',
    imageParams: 'Parametry obr\u00e1zku',
    noData: '\u017d\u00e1dn\u00e1 data \u2014 p\u0159idejte obr\u00e1zek.',
    original: 'Origin\u00e1l:',
    aspectRatio: 'Pom\u011br stran:',
    target: 'C\u00edl:',
    inputFormat: 'Vstupn\u00ed form\u00e1t:',
    outputFormat: 'V\u00fdstupn\u00ed form\u00e1t:',
    shape: 'Tvar:',
    sourceFile: 'Zdrojov\u00fd soubor:',
    estimatedResult: 'Odhadovan\u00fd v\u00fdsledek:',
    convertAndDownload: 'Konvertovat a st\u00e1hnout',
    quality: 'Kvalita (JPG/WEBP)',
    qualityHelper:
      'Ni\u017e\u0161\u00ed hodnota znamen\u00e1 men\u0161\u00ed soubor, ale ni\u017e\u0161\u00ed kvalitu obr\u00e1zku. Pro soci\u00e1ln\u00ed s\u00edt\u011b je optim\u00e1ln\u00ed hodnota 70\u201385\u00a0%.',
    processing: 'Zpracov\u00e1v\u00e1n\u00ed\u2026',
    resizeAndDownload: 'Zm\u011bnit velikost a st\u00e1hnout',
    cropTools: 'N\u00e1stroje o\u0159ezu',
    addImageFirstHelper: 'Nejprve p\u0159idejte obr\u00e1zek vlevo. Pot\u00e9 se zobraz\u00ed nastaven\u00ed o\u0159ezu a n\u00e1hled.',
    demoOriginal: 'Origin\u00e1l: 3000 x 2000 px',
    demoTarget: 'C\u00edl: 1080 x 1350 px',
    demoFormat: 'Form\u00e1t: WebP',
    demoPreset: 'Instagram portr\u00e9t \u00b7 4:5',
    dimensions: 'Rozm\u011bry v px',
    presetsLabel: 'P\u0159edvolby',
    shapesLabel: 'Tvary o\u0159ezu',
    zoom: 'P\u0159ibl\u00ed\u017een\u00ed',
    position: 'Pozice',
    gridColor: 'Barva m\u0159\u00ed\u017eky',
    width: '\u0160\u00ed\u0159ka (px)',
    height: 'V\u00fd\u0161ka (px)',
    keepAspectRatio: 'Zachovat pom\u011br stran (druh\u00fd rozm\u011br automaticky)',
    category: 'Kategorie',
    format: 'Form\u00e1t',
    selectPreset: 'Vybrat form\u00e1t',
    rectAspect: 'Pom\u011br stran obd\u00e9ln\u00edku',
    cropZoom: 'P\u0159ibl\u00ed\u017een\u00ed o\u0159ezu',
    horizontal: 'Vodorovn\u011b (X)',
    vertical: 'Svisle (Y)',
    centerHorizontal: 'Vycentrovat vodorovn\u011b',
    centerVertical: 'Vycentrovat svisle',
    centerCrop: 'Vycentrovat o\u0159ez',
    cropPreview: 'N\u00e1hled o\u0159ezu',
    cropPreviewHelper:
      'Sv\u011btl\u00e1 oblast ukazuje p\u0159esn\u00fd o\u0159ez, kter\u00fd bude ulo\u017een. Ulo\u017een\u00fd soubor bude m\u00edt p\u0159esn\u011b tu velikost a fragment obr\u00e1zku, kter\u00fd vid\u00edte uprost\u0159ed. Pro tvar kruhu bude soubor m\u00edt pr\u016fhledn\u00e9 pozad\u00ed mimo tvar (PNG / WebP).',
    shapes: { rect: 'Obd\u00e9ln\u00edk', square: '\u010ctverec', circle: 'Kruh' },
    gridColors: { emerald: 'Zelen\u00e1', white: 'B\u00edl\u00e1', black: '\u010cern\u00e1', red: '\u010cerven\u00e1', yellow: '\u017dlut\u00e1' },
    categories: { social: 'soci\u00e1ln\u00ed s\u00edt\u011b', web: 'web' },
    presets: {
      igSquare: 'Instagram \u2013 \u010dtverec (1080x1080)',
      igPortrait: 'Instagram \u2013 portr\u00e9t (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 p\u0159\u00edsp\u011bvek (1200x630)',
      fbCover: 'Facebook \u2013 \u00favodn\u00ed fotka (820x360)',
      liPost: 'LinkedIn \u2013 p\u0159\u00edsp\u011bvek (1200x1200)',
      liBanner: 'LinkedIn \u2013 banner profilu (1584x396)',
      ogImage: 'OG obr\u00e1zek (1200x630)',
      cover: 'Ob\u00e1lka \u010dl\u00e1nku (1600x900)',
      banner: 'Banner webu (1920x600)',
      thumb: 'N\u00e1hled \u010dl\u00e1nku (800x600)',
      hero: 'Hero sekce (1920x1080)',
      bg: 'Pozad\u00ed sekce (1920x1280)',
    },
    previewAlt: 'N\u00e1hled',
  },
  sv: {
    imageLoadError: 'Kunde inte ladda bilden.',
    canvasNotSupported: 'Din webbl\u00e4sare st\u00f6der inte 2D-canvas.',
    fileGenerationError: 'Kunde inte generera filen.',
    addImageFirst: 'L\u00e4gg till en bild f\u00f6rst.',
    setValidDimensions: 'Ange giltiga m\u00e5lm\u00e5tt.',
    addImage: 'L\u00e4gg till bild',
    dragDropImage: 'Dra och sl\u00e4pp en bild h\u00e4r',
    clickToSelect: 'eller klicka f\u00f6r att v\u00e4lja en fil',
    supportedFormats: 'St\u00f6ds: JPG, PNG, WebP',
    currentFile: 'Aktuell fil:',
    imageParams: 'Bildparametrar',
    noData: 'Inga data \u2014 l\u00e4gg till en bild.',
    original: 'Original:',
    aspectRatio: 'Bildproportioner:',
    target: 'M\u00e5l:',
    inputFormat: 'Indataformat:',
    outputFormat: 'Utdataformat:',
    shape: 'Form:',
    sourceFile: 'K\u00e4llfil:',
    estimatedResult: 'Uppskattat resultat:',
    convertAndDownload: 'Konvertera och ladda ned',
    quality: 'Kvalitet (JPG/WEBP)',
    qualityHelper: 'L\u00e4gre v\u00e4rde ger en mindre fil men l\u00e4gre bildkvalitet. F\u00f6r sociala medier \u00e4r 70\u201385\u00a0% optimalt.',
    processing: 'Bearbetar\u2026',
    resizeAndDownload: '\u00c4ndra storlek och ladda ned',
    cropTools: 'Beskärningsverktyg',
    addImageFirstHelper: 'L\u00e4gg f\u00f6rst till en bild till v\u00e4nster. D\u00e4refter visas besk\u00e4rningsinst\u00e4llningar och f\u00f6rhandsgranskning.',
    demoOriginal: 'Original: 3000 x 2000 px',
    demoTarget: 'M\u00e5l: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram portr\u00e4tt \u00b7 4:5',
    dimensions: 'M\u00e5tt i px',
    presetsLabel: 'F\u00f6rinst\u00e4llningar',
    shapesLabel: 'Besk\u00e4rningsformer',
    zoom: 'Zoom',
    position: 'Position',
    gridColor: 'Rutn\u00e4tsf\u00e4rg',
    width: 'Bredd (px)',
    height: 'H\u00f6jd (px)',
    keepAspectRatio: 'Beh\u00e5ll proportioner (automatiskt andra m\u00e5tt)',
    category: 'Kategori',
    format: 'Format',
    selectPreset: 'V\u00e4lj format',
    rectAspect: 'Rektangelns proportioner',
    cropZoom: 'Besk\u00e4rningszoom',
    horizontal: 'Horisontell (X)',
    vertical: 'Vertikal (Y)',
    centerHorizontal: 'Centrera horisontellt',
    centerVertical: 'Centrera vertikalt',
    centerCrop: 'Centrera besk\u00e4rning',
    cropPreview: 'F\u00f6rhandsgranskning',
    cropPreviewHelper:
      'Det ljusa omr\u00e5det visar den exakta besk\u00e4rning som sparas. Den sparade filen f\u00e5r exakt den storlek och det bildfragment du ser i mitten. F\u00f6r cirkelform f\u00e5r filen transparent bakgrund utanf\u00f6r formen (PNG / WebP).',
    shapes: { rect: 'Rektangel', square: 'Kvadrat', circle: 'Cirkel' },
    gridColors: { emerald: 'Gr\u00f6n', white: 'Vit', black: 'Svart', red: 'R\u00f6d', yellow: 'Gul' },
    categories: { social: 'sociala medier', web: 'webb' },
    presets: {
      igSquare: 'Instagram \u2013 kvadrat (1080x1080)',
      igPortrait: 'Instagram \u2013 portr\u00e4tt (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 inl\u00e4gg (1200x630)',
      fbCover: 'Facebook \u2013 omslagsbild (820x360)',
      liPost: 'LinkedIn \u2013 inl\u00e4gg (1200x1200)',
      liBanner: 'LinkedIn \u2013 profilbanner (1584x396)',
      ogImage: 'OG-bild (1200x630)',
      cover: 'Artikelomslag (1600x900)',
      banner: 'Webbplatsbanner (1920x600)',
      thumb: 'Artikelminiatyr (800x600)',
      hero: 'Hero-sektion (1920x1080)',
      bg: 'Sektionsbakgrund (1920x1280)',
    },
    previewAlt: 'F\u00f6rhandsgranskning',
  },
  sq: {
    imageLoadError: 'Nuk u ngarkua imazhi.',
    canvasNotSupported: 'Shfletuesi juaj nuk mb\u00ebshtet kanvas\u00ebn 2D.',
    fileGenerationError: 'Nuk u gjenerua skedari.',
    addImageFirst: 'Shto nj\u00eb imazh s\u00eb pari.',
    setValidDimensions: 'Cakto dimensionet e vlefshme t\u00eb objektivit.',
    addImage: 'Shto imazh',
    dragDropImage: 'T\u00ebrheq dhe l\u00ebsho nj\u00eb imazh k\u00ebtu',
    clickToSelect: 'ose kliko p\u00ebr t\u00eb zgjedhur nj\u00eb skedar',
    supportedFormats: 'T\u00eb mb\u00ebshtetura: JPG, PNG, WebP',
    currentFile: 'Skedari aktual:',
    imageParams: 'Parametrat e imazhit',
    noData: 'Asnj\u00eb e dh\u00ebn\u00eb \u2014 shto nj\u00eb imazh.',
    original: 'Origjinal:',
    aspectRatio: 'Raporti i an\u00ebs:',
    target: 'Objektivi:',
    inputFormat: 'Formati i hyrjes:',
    outputFormat: 'Formati i daljes:',
    shape: 'Forma:',
    sourceFile: 'Skedari burimor:',
    estimatedResult: 'Rezultati i p\u00ebrllgaritur:',
    convertAndDownload: 'Konverto dhe shkarko',
    quality: 'Cil\u00ebsia (JPG/WEBP)',
    qualityHelper:
      'Vlera m\u00eb e ul\u00ebt do t\u00eb thot\u00eb skedar m\u00eb i vog\u00ebl por cil\u00ebsi m\u00eb t\u00eb ul\u00ebt imazhi. P\u00ebr rrjete sociale, vlera optimale \u00ebsht\u00eb 70\u201385%.',
    processing: 'Duke p\u00ebrpunuar\u2026',
    resizeAndDownload: 'Ndrysho madh\u00ebsin\u00eb dhe shkarko',
    cropTools: 'Mjete prerjeje',
    addImageFirstHelper: 'S\u00eb pari shto nj\u00eb imazh n\u00eb t\u00eb majt\u00eb. Past\u00e9j do t\u00eb shfaqen cilësimet e prerjes dhe pamja paraprake.',
    demoOriginal: 'Origjinal: 3000 x 2000 px',
    demoTarget: 'Objektivi: 1080 x 1350 px',
    demoFormat: 'Formati: WebP',
    demoPreset: 'Instagram portret \u00b7 4:5',
    dimensions: 'Dimensionet n\u00eb px',
    presetsLabel: 'Paramet\u00ebr t\u00eb paracaktuara',
    shapesLabel: 'Format e prerjes',
    zoom: 'Zmadhim',
    position: 'Pozicioni',
    gridColor: 'Ngjyra e rrjet\u00ebs',
    width: 'Gjer\u00ebsia (px)',
    height: 'Lart\u00ebsia (px)',
    keepAspectRatio: 'Ruaj raportin e an\u00ebs (dimensioni i dyt\u00eb automatik)',
    category: 'Kategoria',
    format: 'Formati',
    selectPreset: 'Zgjidh formatin',
    rectAspect: 'Raporti i an\u00ebs i drejt\u00ebk\u00ebndëshit',
    cropZoom: 'Zmadhimi i prerjes',
    horizontal: 'Horizontal (X)',
    vertical: 'Vertikal (Y)',
    centerHorizontal: 'Q\u00ebndroje horizontalisht',
    centerVertical: 'Q\u00ebndroje vertikalisht',
    centerCrop: 'Q\u00ebndroje prerjen',
    cropPreview: 'Pamja paraprake e prerjes',
    cropPreviewHelper:
      'Zona e ndri\u00e7uar tregon prerjen e sakt\u00eb q\u00eb do t\u00eb ruhet. Skedari i ruajtur do t\u00eb ket\u00eb sakt\u00ebsisht at\u00eb madh\u00ebsi dhe at\u00eb fragment imazhi q\u00eb e shihni n\u00eb q\u00ebnd\u00ebr. P\u00ebr form\u00ebn e rrethit, skedari do t\u00eb ket\u00eb sfond transparent jasht\u00eb form\u00ebs (PNG / WebP).',
    shapes: { rect: 'Drejt\u00ebk\u00ebnd\u00ebsh', square: 'Katror', circle: 'Rreth' },
    gridColors: { emerald: 'E gjelbër', white: 'E bardh\u00eb', black: 'E zez\u00eb', red: 'E kuqe', yellow: 'E verdh\u00eb' },
    categories: { social: 'rrjete sociale', web: 'web' },
    presets: {
      igSquare: 'Instagram \u2013 katror (1080x1080)',
      igPortrait: 'Instagram \u2013 portret (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 postim (1200x630)',
      fbCover: 'Facebook \u2013 kopertina (820x360)',
      liPost: 'LinkedIn \u2013 postim (1200x1200)',
      liBanner: 'LinkedIn \u2013 baner profili (1584x396)',
      ogImage: 'Imazh OG (1200x630)',
      cover: 'Kopertina e artikullit (1600x900)',
      banner: 'Baner i faqes (1920x600)',
      thumb: 'Miniatur\u00eb artikulli (800x600)',
      hero: 'Seksioni hero (1920x1080)',
      bg: 'Sfondi i seksionit (1920x1280)',
    },
    previewAlt: 'Pamja paraprake',
  },
  da: {
    imageLoadError: 'Kunne ikke indl\u00e6se billedet.',
    canvasNotSupported: 'Din browser underst\u00f8tter ikke 2D-canvas.',
    fileGenerationError: 'Kunne ikke generere filen.',
    addImageFirst: 'Tilf\u00f8j f\u00f8rst et billede.',
    setValidDimensions: 'Angiv gyldige m\u00e5ldimensioner.',
    addImage: 'Tilf\u00f8j billede',
    dragDropImage: 'Tr\u00e6k og slip et billede her',
    clickToSelect: 'eller klik for at v\u00e6lge en fil',
    supportedFormats: 'Underst\u00f8ttet: JPG, PNG, WebP',
    currentFile: 'Aktuel fil:',
    imageParams: 'Billedparametre',
    noData: 'Ingen data \u2014 tilf\u00f8j et billede.',
    original: 'Original:',
    aspectRatio: 'Billedformat:',
    target: 'M\u00e5l:',
    inputFormat: 'Inputformat:',
    outputFormat: 'Outputformat:',
    shape: 'Form:',
    sourceFile: 'Kildefil:',
    estimatedResult: 'Estimeret resultat:',
    convertAndDownload: 'Konvert\u00e9r og download',
    quality: 'Kvalitet (JPG/WEBP)',
    qualityHelper: 'Lavere v\u00e6rdi giver en mindre fil men lavere billedkvalitet. Til sociale medier er den optimale v\u00e6rdi 70\u201385\u00a0%.',
    processing: 'Behandler\u2026',
    resizeAndDownload: '\u00c6ndr st\u00f8rrelse og download',
    cropTools: 'Besk\u00e6ringsv\u00e6rkt\u00f8jer',
    addImageFirstHelper: 'Tilf\u00f8j f\u00f8rst et billede til venstre. Derefter vises besk\u00e6ringsindstillinger og forh\u00e5ndsvisning.',
    demoOriginal: 'Original: 3000 x 2000 px',
    demoTarget: 'M\u00e5l: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram portr\u00e6t \u00b7 4:5',
    dimensions: 'Dimensioner i px',
    presetsLabel: 'Forindstillinger',
    shapesLabel: 'Besk\u00e6ringsformer',
    zoom: 'Zoom',
    position: 'Position',
    gridColor: 'Gitterfarve',
    width: 'Bredde (px)',
    height: 'H\u00f8jde (px)',
    keepAspectRatio: 'Bevar billedformat (automatisk anden dimension)',
    category: 'Kategori',
    format: 'Format',
    selectPreset: 'V\u00e6lg format',
    rectAspect: 'Rektanglens billedformat',
    cropZoom: 'Besk\u00e6ringszoom',
    horizontal: 'Vandret (X)',
    vertical: 'Lodret (Y)',
    centerHorizontal: 'Centr\u00e9r vandret',
    centerVertical: 'Centr\u00e9r lodret',
    centerCrop: 'Centr\u00e9r besk\u00e6ring',
    cropPreview: 'Forh\u00e5ndsvisning',
    cropPreviewHelper:
      'Det lyse omr\u00e5de viser den n\u00f8jagtige besk\u00e6ring, der gemmes. Den gemte fil vil have pr\u00e6cis den st\u00f8rrelse og det billedfragment, du ser i midten. For cirkelform vil filen have transparent baggrund uden for formen (PNG / WebP).',
    shapes: { rect: 'Rektangel', square: 'Kvadrat', circle: 'Cirkel' },
    gridColors: { emerald: 'Gr\u00f8n', white: 'Hvid', black: 'Sort', red: 'R\u00f8d', yellow: 'Gul' },
    categories: { social: 'sociale medier', web: 'web' },
    presets: {
      igSquare: 'Instagram \u2013 kvadrat (1080x1080)',
      igPortrait: 'Instagram \u2013 portr\u00e6t (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 opslag (1200x630)',
      fbCover: 'Facebook \u2013 forside (820x360)',
      liPost: 'LinkedIn \u2013 opslag (1200x1200)',
      liBanner: 'LinkedIn \u2013 profilbanner (1584x396)',
      ogImage: 'OG-billede (1200x630)',
      cover: 'Artikelforside (1600x900)',
      banner: 'Hjemmesidebanner (1920x600)',
      thumb: 'Artikelminiature (800x600)',
      hero: 'Hero-sektion (1920x1080)',
      bg: 'Sektionsbaggrund (1920x1280)',
    },
    previewAlt: 'Forh\u00e5ndsvisning',
  },
} as const satisfies Record<Locale, unknown>;

export type UiLocale =
  | (typeof ui)['pl']
  | (typeof ui)['en']
  | (typeof ui)['de']
  | (typeof ui)['es']
  | (typeof ui)['fr']
  | (typeof ui)['pt']
  | (typeof ui)['it']
  | (typeof ui)['ro']
  | (typeof ui)['nl']
  | (typeof ui)['hu']
  | (typeof ui)['id']
  | (typeof ui)['vi']
  | (typeof ui)['tr']
  | (typeof ui)['tl']
  | (typeof ui)['sw']
  | (typeof ui)['ms']
  | (typeof ui)['cs']
  | (typeof ui)['sv']
  | (typeof ui)['sq']
  | (typeof ui)['da'];
