import type { Locale } from '@/lib/LocaleContext';

export const ui = {
  pl: {
    imageLoadError: 'Nie udało się wczytać obrazu.',
    canvasNotSupported: 'Twoja przeglądarka nie obsługuje kontekstu 2D.',
    fileGenerationError: 'Nie udało się wygenerować pliku.',
    addImageFirst: 'Dodaj najpierw zdjęcie.',
    setValidDimensions: 'Ustaw poprawne wymiary docelowe.',
    addImage: 'Dodaj zdjęcie',
    dragDropImage: 'Przeciągnij i upuść zdjęcie tutaj',
    clickToSelect: 'lub kliknij, aby wybrać plik z dysku',
    supportedFormats: 'Obsługiwane: JPG, PNG, WebP',
    currentFile: 'Aktualny plik:',
    imageParams: 'Parametry obrazu',
    noData: 'Brak danych - dodaj zdjęcie.',
    original: 'Oryginalne:',
    aspectRatio: 'Proporcje:',
    target: 'Docelowe:',
    inputFormat: 'Format wejściowy:',
    outputFormat: 'Format wyjściowy:',
    shape: 'Kształt:',
    sourceFile: 'Plik źródłowy:',
    estimatedResult: 'Szacowany wynik:',
    convertAndDownload: 'Konwertuj i pobierz',
    quality: 'Jakość (JPG/WEBP)',
    qualityHelper: 'Niższa wartość oznacza mniejszy plik, ale słabszą jakość obrazu. Dla mediów społecznościowych optymalna wartość to 70–85%.',
    processing: 'Przetwarzanie…',
    resizeAndDownload: 'Zmień rozmiar i pobierz',
    cropTools: 'Narzędzia kadrowania',
    addImageFirstHelper: 'Najpierw dodaj zdjęcie po lewej stronie. Potem pojawią się ustawienia kadru i podgląd.',
    demoOriginal: 'Oryginał: 3000 x 2000 px',
    demoTarget: 'Docelowy: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram post pion · 4:5',
    dimensions: 'Wymiary w px',
    presetsLabel: 'Gotowe formaty',
    shapesLabel: 'Kształty kadru',
    zoom: 'Przybliżenie',
    position: 'Pozycja',
    gridColor: 'Kolor siatki',
    width: 'Szerokość (px)',
    height: 'Wysokość (px)',
    keepAspectRatio: 'Zachowaj proporcje (automatyczny drugi wymiar)',
    category: 'Kategoria',
    format: 'Format',
    selectPreset: 'Wybierz format',
    rectAspect: 'Proporcje prostokąta',
    cropZoom: 'Przybliżenie kadru',
    horizontal: 'Poziom (X)',
    vertical: 'Pion (Y)',
    centerHorizontal: 'Wyśrodkuj poziomo',
    centerVertical: 'Wyśrodkuj pionowo',
    centerCrop: 'Wyśrodkuj kadr',
    cropPreview: 'Podgląd kadru',
    cropPreviewHelper:
      'Jasny obszar pokazuje dokładny kadr, który zostanie zapisany. Zapisany plik będzie miał dokładnie ten rozmiar i fragment obrazu, który widzisz w środku. Dla kształtu koła plik będzie miał przezroczyste tło poza kształtem (PNG / WebP).',
    shapes: {
      rect: 'Prostokąt',
      square: 'Kwadrat',
      circle: 'Koło',
    },
    gridColors: {
      emerald: 'Zielony',
      white: 'Biały',
      black: 'Czarny',
      red: 'Czerwony',
      yellow: 'Żółty',
    },
    categories: {
      social: 'media społecznościowe',
      web: 'WWW',
    },
    presets: {
      igSquare: 'Instagram - post kwadrat (1080x1080)',
      igPortrait: 'Instagram - post pion (1080x1350)',
      igStory: 'Instagram - story / reels (1080x1920)',
      fbPost: 'Facebook - post (1200x630)',
      fbCover: 'Facebook - cover strony (820x360)',
      liPost: 'LinkedIn - post (1200x1200)',
      liBanner: 'LinkedIn - baner profilu (1584x396)',
      ogImage: 'OG image (1200x630)',
      cover: 'Grafika do artykułu (1600x900)',
      banner: 'Baner strony (1920x600)',
      thumb: 'Miniatura artykułu (800x600)',
      hero: 'Hero sekcji (1920x1080)',
      bg: 'Tło sekcji (1920x1280)',
    },
    previewAlt: 'Podgląd',
  },
  en: {
    imageLoadError: 'Failed to load the image.',
    canvasNotSupported: 'Your browser does not support 2D canvas.',
    fileGenerationError: 'Failed to generate the file.',
    addImageFirst: 'Add an image first.',
    setValidDimensions: 'Set valid target dimensions.',
    addImage: 'Add image',
    dragDropImage: 'Drag and drop an image here',
    clickToSelect: 'or click to select a file from your device',
    supportedFormats: 'Supported: JPG, PNG, WebP',
    currentFile: 'Current file:',
    imageParams: 'Image parameters',
    noData: 'No data - add an image.',
    original: 'Original:',
    aspectRatio: 'Aspect ratio:',
    target: 'Target:',
    inputFormat: 'Input format:',
    outputFormat: 'Output format:',
    shape: 'Shape:',
    sourceFile: 'Source file:',
    estimatedResult: 'Estimated result:',
    convertAndDownload: 'Convert and download',
    quality: 'Quality (JPG/WEBP)',
    qualityHelper: 'Lower value means smaller file but lower image quality. For social media, the optimal value is 70–85%.',
    processing: 'Processing…',
    resizeAndDownload: 'Resize and download',
    cropTools: 'Crop tools',
    addImageFirstHelper: 'First add an image on the left. Then crop settings and preview will appear.',
    demoOriginal: 'Original: 3000 x 2000 px',
    demoTarget: 'Target: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram portrait post · 4:5',
    dimensions: 'Dimensions in px',
    presetsLabel: 'Presets',
    shapesLabel: 'Crop shapes',
    zoom: 'Zoom',
    position: 'Position',
    gridColor: 'Grid color',
    width: 'Width (px)',
    height: 'Height (px)',
    keepAspectRatio: 'Keep aspect ratio (auto second dimension)',
    category: 'Category',
    format: 'Format',
    selectPreset: 'Select format',
    rectAspect: 'Rectangle aspect ratio',
    cropZoom: 'Crop zoom',
    horizontal: 'Horizontal (X)',
    vertical: 'Vertical (Y)',
    centerHorizontal: 'Center horizontally',
    centerVertical: 'Center vertically',
    centerCrop: 'Center crop',
    cropPreview: 'Crop preview',
    cropPreviewHelper:
      'The bright area shows the exact crop that will be saved. The saved file will have exactly the size and image fragment you see in the center. For circle shape the file will have a transparent background outside the shape (PNG / WebP).',
    shapes: {
      rect: 'Rectangle',
      square: 'Square',
      circle: 'Circle',
    },
    gridColors: {
      emerald: 'Green',
      white: 'White',
      black: 'Black',
      red: 'Red',
      yellow: 'Yellow',
    },
    categories: {
      social: 'social media',
      web: 'web',
    },
    presets: {
      igSquare: 'Instagram - square post (1080x1080)',
      igPortrait: 'Instagram - portrait post (1080x1350)',
      igStory: 'Instagram - story / reels (1080x1920)',
      fbPost: 'Facebook - post (1200x630)',
      fbCover: 'Facebook - page cover (820x360)',
      liPost: 'LinkedIn - post (1200x1200)',
      liBanner: 'LinkedIn - profile banner (1584x396)',
      ogImage: 'OG image (1200x630)',
      cover: 'Article cover (1600x900)',
      banner: 'Website banner (1920x600)',
      thumb: 'Article thumbnail (800x600)',
      hero: 'Hero section (1920x1080)',
      bg: 'Section background (1920x1280)',
    },
    previewAlt: 'Preview',
  },
  de: {
    imageLoadError: 'Das Bild konnte nicht geladen werden.',
    canvasNotSupported: 'Ihr Browser unterstützt kein 2D-Canvas.',
    fileGenerationError: 'Die Datei konnte nicht generiert werden.',
    addImageFirst: 'Fügen Sie zuerst ein Bild hinzu.',
    setValidDimensions: 'Geben Sie gültige Zielmaße ein.',
    addImage: 'Bild hinzufügen',
    dragDropImage: 'Bild hierher ziehen und ablegen',
    clickToSelect: 'oder klicken, um eine Datei auszuwählen',
    supportedFormats: 'Unterstützt: JPG, PNG, WebP',
    currentFile: 'Aktuelle Datei:',
    imageParams: 'Bildparameter',
    noData: 'Keine Daten — fügen Sie ein Bild hinzu.',
    original: 'Original:',
    aspectRatio: 'Seitenverhältnis:',
    target: 'Ziel:',
    inputFormat: 'Eingabeformat:',
    outputFormat: 'Ausgabeformat:',
    shape: 'Form:',
    sourceFile: 'Quelldatei:',
    estimatedResult: 'Geschätztes Ergebnis:',
    convertAndDownload: 'Konvertieren und herunterladen',
    quality: 'Qualität (JPG/WEBP)',
    qualityHelper: 'Ein niedrigerer Wert ergibt eine kleinere Datei, aber geringere Bildqualität. Für Social Media ist 70–85\u00a0% optimal.',
    processing: 'Verarbeitung\u2026',
    resizeAndDownload: 'Größe ändern und herunterladen',
    cropTools: 'Zuschnittwerkzeuge',
    addImageFirstHelper: 'Fügen Sie zuerst links ein Bild hinzu. Dann erscheinen die Zuschnitteinstellungen und die Vorschau.',
    demoOriginal: 'Original: 3000 x 2000 px',
    demoTarget: 'Ziel: 1080 x 1350 px',
    demoFormat: 'Format: WebP',
    demoPreset: 'Instagram Hochformat · 4:5',
    dimensions: 'Maße in px',
    presetsLabel: 'Vorlagen',
    shapesLabel: 'Zuschnittsformen',
    zoom: 'Zoom',
    position: 'Position',
    gridColor: 'Rasterfarbe',
    width: 'Breite (px)',
    height: 'Höhe (px)',
    keepAspectRatio: 'Seitenverhältnis beibehalten (zweiter Wert automatisch)',
    category: 'Kategorie',
    format: 'Format',
    selectPreset: 'Vorlage wählen',
    rectAspect: 'Seitenverhältnis des Rechtecks',
    cropZoom: 'Zuschnittzoom',
    horizontal: 'Horizontal (X)',
    vertical: 'Vertikal (Y)',
    centerHorizontal: 'Horizontal zentrieren',
    centerVertical: 'Vertikal zentrieren',
    centerCrop: 'Zuschnitt zentrieren',
    cropPreview: 'Zuschnittvorschau',
    cropPreviewHelper:
      'Der helle Bereich zeigt den genauen Zuschnitt, der gespeichert wird. Die gespeicherte Datei hat genau die Größe und den Bildausschnitt, den Sie in der Mitte sehen. Bei Kreisform wird der Bereich außerhalb des Kreises transparent (PNG / WebP).',
    shapes: {
      rect: 'Rechteck',
      square: 'Quadrat',
      circle: 'Kreis',
    },
    gridColors: {
      emerald: 'Grün',
      white: 'Weiß',
      black: 'Schwarz',
      red: 'Rot',
      yellow: 'Gelb',
    },
    categories: {
      social: 'Social Media',
      web: 'Web',
    },
    presets: {
      igSquare: 'Instagram – Quadrat (1080x1080)',
      igPortrait: 'Instagram – Hochformat (1080x1350)',
      igStory: 'Instagram – Story / Reels (1080x1920)',
      fbPost: 'Facebook – Post (1200x630)',
      fbCover: 'Facebook – Seitencover (820x360)',
      liPost: 'LinkedIn – Post (1200x1200)',
      liBanner: 'LinkedIn – Profilbanner (1584x396)',
      ogImage: 'OG Image (1200x630)',
      cover: 'Artikelbild (1600x900)',
      banner: 'Website-Banner (1920x600)',
      thumb: 'Artikel-Thumbnail (800x600)',
      hero: 'Hero-Bereich (1920x1080)',
      bg: 'Hintergrundbild (1920x1280)',
    },
    previewAlt: 'Vorschau',
  },
  es: {
    imageLoadError: 'No se pudo cargar la imagen.',
    canvasNotSupported: 'Su navegador no admite canvas 2D.',
    fileGenerationError: 'No se pudo generar el archivo.',
    addImageFirst: 'Añada primero una imagen.',
    setValidDimensions: 'Establezca dimensiones de destino válidas.',
    addImage: 'Añadir imagen',
    dragDropImage: 'Arrastre y suelte una imagen aquí',
    clickToSelect: 'o haga clic para seleccionar un archivo',
    supportedFormats: 'Compatibles: JPG, PNG, WebP',
    currentFile: 'Archivo actual:',
    imageParams: 'Parámetros de imagen',
    noData: 'Sin datos \u2014 añada una imagen.',
    original: 'Original:',
    aspectRatio: 'Relación de aspecto:',
    target: 'Destino:',
    inputFormat: 'Formato de entrada:',
    outputFormat: 'Formato de salida:',
    shape: 'Forma:',
    sourceFile: 'Archivo de origen:',
    estimatedResult: 'Resultado estimado:',
    convertAndDownload: 'Convertir y descargar',
    quality: 'Calidad (JPG/WEBP)',
    qualityHelper: 'Un valor más bajo genera un archivo menor pero con menos calidad. Para redes sociales, lo óptimo es 70\u201385\u00a0%.',
    processing: 'Procesando\u2026',
    resizeAndDownload: 'Redimensionar y descargar',
    cropTools: 'Herramientas de recorte',
    addImageFirstHelper: 'Primero añada una imagen a la izquierda. Luego aparecerán los ajustes de recorte y la vista previa.',
    demoOriginal: 'Original: 3000 x 2000 px',
    demoTarget: 'Destino: 1080 x 1350 px',
    demoFormat: 'Formato: WebP',
    demoPreset: 'Instagram vertical \u00b7 4:5',
    dimensions: 'Dimensiones en px',
    presetsLabel: 'Formatos predefinidos',
    shapesLabel: 'Formas de recorte',
    zoom: 'Zoom',
    position: 'Posición',
    gridColor: 'Color de cuadrícula',
    width: 'Ancho (px)',
    height: 'Alto (px)',
    keepAspectRatio: 'Mantener relación de aspecto (segunda dimensión automática)',
    category: 'Categoría',
    format: 'Formato',
    selectPreset: 'Seleccionar formato',
    rectAspect: 'Relación de aspecto del rectángulo',
    cropZoom: 'Zoom del recorte',
    horizontal: 'Horizontal (X)',
    vertical: 'Vertical (Y)',
    centerHorizontal: 'Centrar horizontalmente',
    centerVertical: 'Centrar verticalmente',
    centerCrop: 'Centrar recorte',
    cropPreview: 'Vista previa del recorte',
    cropPreviewHelper:
      'El área iluminada muestra el recorte exacto que se guardará. El archivo guardado tendrá exactamente el tamaño y el fragmento de imagen que ve en el centro. Para la forma circular, el archivo tendrá fondo transparente fuera de la forma (PNG / WebP).',
    shapes: {
      rect: 'Rectángulo',
      square: 'Cuadrado',
      circle: 'Círculo',
    },
    gridColors: {
      emerald: 'Verde',
      white: 'Blanco',
      black: 'Negro',
      red: 'Rojo',
      yellow: 'Amarillo',
    },
    categories: {
      social: 'Redes sociales',
      web: 'Web',
    },
    presets: {
      igSquare: 'Instagram \u2013 cuadrado (1080x1080)',
      igPortrait: 'Instagram \u2013 vertical (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 publicación (1200x630)',
      fbCover: 'Facebook \u2013 portada (820x360)',
      liPost: 'LinkedIn \u2013 publicación (1200x1200)',
      liBanner: 'LinkedIn \u2013 banner de perfil (1584x396)',
      ogImage: 'Imagen OG (1200x630)',
      cover: 'Portada de artículo (1600x900)',
      banner: 'Banner del sitio web (1920x600)',
      thumb: 'Miniatura de artículo (800x600)',
      hero: 'Sección hero (1920x1080)',
      bg: 'Fondo de sección (1920x1280)',
    },
    previewAlt: 'Vista previa',
  },
  fr: {
    imageLoadError: "Impossible de charger l'image.",
    canvasNotSupported: 'Votre navigateur ne prend pas en charge le canvas 2D.',
    fileGenerationError: 'Impossible de générer le fichier.',
    addImageFirst: "Ajoutez d'abord une image.",
    setValidDimensions: 'Définissez des dimensions cibles valides.',
    addImage: 'Ajouter une image',
    dragDropImage: 'Glissez-déposez une image ici',
    clickToSelect: 'ou cliquez pour sélectionner un fichier',
    supportedFormats: 'Formats pris en charge\u00a0: JPG, PNG, WebP',
    currentFile: 'Fichier actuel\u00a0:',
    imageParams: "Paramètres de l'image",
    noData: 'Aucune donnée \u2014 ajoutez une image.',
    original: 'Original\u00a0:',
    aspectRatio: "Rapport d'aspect\u00a0:",
    target: 'Cible\u00a0:',
    inputFormat: "Format d'entrée\u00a0:",
    outputFormat: 'Format de sortie\u00a0:',
    shape: 'Forme\u00a0:',
    sourceFile: 'Fichier source\u00a0:',
    estimatedResult: 'Résultat estimé\u00a0:',
    convertAndDownload: 'Convertir et télécharger',
    quality: 'Qualité (JPG/WEBP)',
    qualityHelper: 'Une valeur plus basse donne un fichier plus léger mais de moindre qualité. Pour les réseaux sociaux, 70\u201385\u00a0% est optimal.',
    processing: 'Traitement en cours\u2026',
    resizeAndDownload: 'Redimensionner et télécharger',
    cropTools: 'Outils de recadrage',
    addImageFirstHelper: "Ajoutez d'abord une image à gauche. Les paramètres de recadrage et l'aperçu apparaîtront ensuite.",
    demoOriginal: 'Original\u00a0: 3000 x 2000 px',
    demoTarget: 'Cible\u00a0: 1080 x 1350 px',
    demoFormat: 'Format\u00a0: WebP',
    demoPreset: 'Instagram vertical \u00b7 4:5',
    dimensions: 'Dimensions en px',
    presetsLabel: 'Formats prédéfinis',
    shapesLabel: 'Formes de recadrage',
    zoom: 'Zoom',
    position: 'Position',
    gridColor: 'Couleur de la grille',
    width: 'Largeur (px)',
    height: 'Hauteur (px)',
    keepAspectRatio: "Conserver le rapport d'aspect (seconde dimension automatique)",
    category: 'Catégorie',
    format: 'Format',
    selectPreset: 'Sélectionner un format',
    rectAspect: "Rapport d'aspect du rectangle",
    cropZoom: 'Zoom du recadrage',
    horizontal: 'Horizontal (X)',
    vertical: 'Vertical (Y)',
    centerHorizontal: 'Centrer horizontalement',
    centerVertical: 'Centrer verticalement',
    centerCrop: 'Centrer le recadrage',
    cropPreview: 'Aperçu du recadrage',
    cropPreviewHelper:
      "La zone éclairée montre le recadrage exact qui sera enregistré. Le fichier aura exactement la taille et le fragment d'image visibles au centre. Pour la forme circulaire, le fichier aura un fond transparent hors de la forme (PNG / WebP).",
    shapes: {
      rect: 'Rectangle',
      square: 'Carré',
      circle: 'Cercle',
    },
    gridColors: {
      emerald: 'Vert',
      white: 'Blanc',
      black: 'Noir',
      red: 'Rouge',
      yellow: 'Jaune',
    },
    categories: {
      social: 'Réseaux sociaux',
      web: 'Web',
    },
    presets: {
      igSquare: 'Instagram \u2013 carré (1080x1080)',
      igPortrait: 'Instagram \u2013 portrait (1080x1350)',
      igStory: 'Instagram \u2013 story / reels (1080x1920)',
      fbPost: 'Facebook \u2013 publication (1200x630)',
      fbCover: 'Facebook \u2013 couverture (820x360)',
      liPost: 'LinkedIn \u2013 publication (1200x1200)',
      liBanner: 'LinkedIn \u2013 bannière de profil (1584x396)',
      ogImage: 'Image OG (1200x630)',
      cover: "Couverture d'article (1600x900)",
      banner: 'Bannière du site (1920x600)',
      thumb: "Miniature d'article (800x600)",
      hero: 'Section hero (1920x1080)',
      bg: 'Fond de section (1920x1280)',
    },
    previewAlt: 'Aperçu',
  },
} as const satisfies Record<Locale, unknown>;

export type UiLocale = (typeof ui)['pl'] | (typeof ui)['en'] | (typeof ui)['de'] | (typeof ui)['es'] | (typeof ui)['fr'];
