import type { HeaderNavItem, AboutNavItem, OfferSection } from '@/types/navigation';
import type { ToolsSection } from '@/types/tools/common';
export type { HeaderNavItemKey, HeaderNavItem, AboutItemKey, AboutNavItem, OfferSectionKey, OfferItemKey, OfferSectionItem, OfferSection, LegalLinkKey } from '@/types/navigation';
export type { ToolsSectionKey, ToolItemKey, ToolSectionItem, ToolsSection } from '@/types/tools/common';

import {
  NavAppsLine as RiAppsLine,
  NavArticleLine as RiArticleLine,
  NavBookletLine as RiBookletLine,
  NavBrushLine as RiBrushLine,
  NavCodeSSlashFill as RiCodeSSlashFill,
  NavContrast2Line as RiContrast2Line,
  NavCoupon2Line as RiCoupon2Line,
  NavCropLine as RiCropLine,
  NavFileEditLine as RiFileEditLine,
  NavFileList2Line as RiFileList2Line,
  NavFileTextLine as RiFileTextLine,
  NavFolderOpenLine as RiFolderOpenLine,
  NavGlobalLine as RiGlobalLine,
  NavIdCardLine as RiIdCardLine,
  NavImageEditLine as RiImageEditLine,
  NavLayoutLine as RiLayoutLine,
  NavLineChartLine as RiLineChartLine,
  NavLoopLeftLine as RiLoopLeftLine,
  NavMailLine as RiMailLine,
  NavMegaphoneLine as RiMegaphoneLine,
  NavPaletteLine as RiPaletteLine,
  NavPantoneLine as RiPantoneLine,
  NavPriceTag3Line as RiPriceTag3Line,
  NavQrCodeLine as RiQrCodeLine,
  NavQuillPenLine as RiQuillPenLine,
  NavRestaurant2Line as RiRestaurant2Line,
  NavSearchLine as RiSearchLine,
  NavShoppingCartLine as RiShoppingCartLine,
  NavTeamLine as RiTeamLine,
  NavTShirt2Line as RiTShirt2Line,
} from '@/components/ui/icons/NavIcons';

export const DESKTOP_NAV_ITEMS_PL: HeaderNavItem[] = [
  { key: 'realizacje', href: '/realizacje', label: 'Realizacje', exact: true },
  { key: 'uslugi', href: '/uslugi', label: 'Usługi' },
  { key: 'oNas', href: '/o-nas', label: 'O nas' },
  { key: 'edukacja', href: '/edukacja', label: 'Edukacja' },
  { key: 'narzedzia', href: '/narzedzia', label: 'Narzędzia' },
  { key: 'kontakt', href: '/kontakt', label: 'Kontakt' },
];

export const MOBILE_NAV_ITEMS_PL: HeaderNavItem[] = DESKTOP_NAV_ITEMS_PL.filter((it) => it.key !== 'uslugi');

export const ABOUT_NAV_ITEMS_PL: AboutNavItem[] = [
  { key: 'faq', href: '/o-nas/faq', title: 'FAQ', icon: RiFileList2Line },
  { key: 'joinNetwork', href: '/o-nas/dolacz-do-sieci', title: 'Dołącz do sieci', icon: RiTeamLine },
];

export const OFFER_SECTIONS_PL: OfferSection[] = [
  {
    key: 'witryny',
    title: 'Witryny',
    icon: RiGlobalLine,
    items: [
      {
        key: 'websites',
        href: '/uslugi/tworzenie-stron-wordpress',
        title: 'Strony WordPress',
        icon: RiCodeSSlashFill,
      },
      {
        key: 'shops',
        href: '/uslugi/sklepy-internetowe',
        title: 'Sklepy internetowe',
        icon: RiShoppingCartLine,
      },
      {
        key: 'blogs',
        href: '/uslugi/blogi-internetowe',
        title: 'Blogi internetowe',
        icon: RiArticleLine,
      },
    ],
  },
  {
    key: 'marketing',
    title: 'Marketing',
    hubHref: '/uslugi/marketing',
    icon: RiLineChartLine,
    items: [
      {
        key: 'auditSeo',
        href: '/uslugi/marketing/audyt-seo',
        title: 'Audyt SEO',
        desc: 'Diagnostyka i priorytety działań',
        icon: RiSearchLine,
      },
      {
        key: 'optimizationSeo',
        href: '/uslugi/marketing/optymalizacja-seo',
        title: 'Optymalizacja SEO',
        icon: RiPriceTag3Line,
      },
      {
        key: 'positioning',
        href: '/uslugi/marketing/pozycjonowanie-stron',
        title: 'Pozycjonowanie stron',
        icon: RiMegaphoneLine,
      },
    ],
  },
  {
    key: 'grafika',
    title: 'Projekty graficzne',
    hubHref: '/uslugi/projekty-graficzne',
    icon: RiBrushLine,
    items: [
      { key: 'priceList', href: '/uslugi/projekty-graficzne/projekt-cennika', title: 'Cenniki', icon: RiPriceTag3Line },
      {
        key: 'visualIdentity',
        href: '/uslugi/projekty-graficzne/projekt-identyfikacji-wizualnej',
        title: 'Identyfikacja wizualna',
        icon: RiPantoneLine,
      },
      { key: 'loyaltyCard', href: '/uslugi/projekty-graficzne/projekt-karty-lojalnosciowej', title: 'Karty lojalnościowe', icon: RiPriceTag3Line },
      { key: 'catalogs', href: '/uslugi/projekty-graficzne/projekt-katalogu', title: 'Katalogi', icon: RiBookletLine },
      { key: 'coupons', href: '/uslugi/projekty-graficzne/projekt-kuponu-rabatowego-i-vouchera', title: 'Kupony i vouchery', icon: RiCoupon2Line },
      { key: 'websiteDesign', href: '/uslugi/projekty-graficzne/projekt-graficzny-strony', title: 'Projekt graficzny strony', icon: RiLayoutLine },
      { key: 'logo', href: '/uslugi/projekty-graficzne/projekt-logo', title: 'Logo', icon: RiQuillPenLine },
      { key: 'restaurantMenu', href: '/uslugi/projekty-graficzne/projekt-menu-restauracji', title: 'Menu restauracji', icon: RiRestaurant2Line },
      { key: 'companyClothing', href: '/uslugi/projekty-graficzne/projekt-odziezy-firmowej', title: 'Odzież firmowa', icon: RiTShirt2Line },
      { key: 'companyPaper', href: '/uslugi/projekty-graficzne/projekt-papieru-firmowego', title: 'Papier firmowy', icon: RiFileTextLine },
      { key: 'socialTemplates', href: '/uslugi/projekty-graficzne/szablony-postow-media-spolecznosciowe', title: 'Szablony do mediów społecznościowych', icon: RiLayoutLine },
      { key: 'offerFolder', href: '/uslugi/projekty-graficzne/projekt-teczki-ofertowej', title: 'Teczki ofertowe', icon: RiFolderOpenLine },
      { key: 'flyers', href: '/uslugi/projekty-graficzne/projekt-ulotki', title: 'Ulotki', icon: RiFileList2Line },
      { key: 'businessCards', href: '/uslugi/projekty-graficzne/projekt-wizytowki', title: 'Wizytówki', icon: RiIdCardLine },
    ],
  },
  {
    key: 'tresc',
    title: 'Tworzenie treści',
    hubHref: '/uslugi/tworzenie-tresci',
    icon: RiFileEditLine,
    items: [
      {
        key: 'contentCreation',
        href: '/uslugi/tworzenie-tresci',
        title: 'Tworzenie treści',
        desc: 'Teksty na strony, blog, oferty',
        icon: RiFileTextLine,
      },
    ],
  },
];

export const TOOLS_SECTIONS_PL: ToolsSection[] = [
  {
    key: 'obrazy',
    title: 'Obrazy i favicony',
    icon: RiImageEditLine,
    items: [
      {
        key: 'imageResize',
        href: '/narzedzia/edytor-zdjec-online',
        title: 'Edytor zdjęć online',
        description: 'Przygotuj idealny kadr pod media społecznościowe lub stronę WWW. Wybierz gotowy format lub wpisz własne wymiary.',
        image: '/assets/tools/narzedzia-zmiana-rozmiaru-i-kadrowanie-zdjecia.webp',
        icon: RiCropLine,
      },
      {
        key: 'favicon',
        href: '/narzedzia/darmowy-generator-favicon-ico',
        title: 'Generator favicon',
        description: 'Z jednego obrazu wygeneruj favicon.ico oraz ikony PNG zgodne z wymaganiami przeglądarek i Lighthouse.',
        image: '/assets/tools/narzedzia-darmowy-generator-favicon-ico.webp',
        icon: RiAppsLine,
      },
      {
        key: 'jpgToWebpSimple',
        href: '/narzedzia/konwerter-jpg-na-webp',
        title: 'Konwerter JPG na WebP',
        description: 'Zamień zdjęcia JPG na lekki WebP. Zmniejsz wagę obrazów nawet o 35%.',
        image: '/assets/tools/jpg-png-to-webp-converter/jpg-png-na-webp-bez-limitu-pl.webp',
        icon: RiLoopLeftLine,
      },
      {
        key: 'pngToJpg',
        href: '/narzedzia/konwerter-png-na-jpg',
        title: 'Konwerter PNG na JPG',
        description: 'Zamień pliki PNG na JPG. Konwersja w przeglądarce, bez limitu plików i rejestracji.',
        image: '/assets/tools/jpg-png-to-webp-converter/jpg-png-na-webp-bez-limitu-pl.webp',
        icon: RiLoopLeftLine,
      },
      {
        key: 'webpToJpg',
        href: '/narzedzia/konwerter-webp-na-jpg',
        title: 'Konwerter WebP na JPG',
        description: 'Zamień pliki WebP na JPG. Kompatybilność z każdym programem i platformą.',
        image: '/assets/tools/jpg-png-to-webp-converter/jpg-png-na-webp-bez-limitu-pl.webp',
        icon: RiLoopLeftLine,
      },
    ],
  },
  {
    key: 'seo',
    title: 'Meta i SEO',
    icon: RiSearchLine,
    items: [
      {
        key: 'metaCounter',
        href: '/narzedzia/licznik-dlugosci-meta-title-i-description',
        title: 'Licznik meta title i description',
        description: 'Sprawdź liczbę znaków i podgląd wyniku w Google. Uniknij uciętych tytułów i opisów w wynikach wyszukiwania.',
        image: '/assets/tools/narzedzia-licznik-dlugosci-meta-title-i-description.webp',
        icon: RiFileTextLine,
      },
      {
        key: 'wordCounter',
        href: '/narzedzia/licznik-slow-i-znakow',
        title: 'Licznik słów i znaków',
        description: 'Sprawdź długość tekstu i oceń, czy jest odpowiednia dla strony głównej, opisu usługi, artykułu czy opisu produktu.',
        image: '/assets/tools/narzedzia-licznik-slow-i-znakow.webp',
        icon: RiArticleLine,
      },
    ],
  },
  {
    key: 'email',
    title: 'E-mail i komunikacja',
    icon: RiMailLine,
    items: [
      {
        key: 'emailSignature',
        href: '/narzedzia/darmowy-generator-stopki-mailowej',
        title: 'Generator stopki mailowej',
        description: 'Zbuduj profesjonalny podpis e-mail w kilka minut. Skopiuj gotowy kod HTML do Gmaila lub Outlooka.',
        image: '/assets/tools/narzedzia-darmowy-generator-stopki-mailowej.webp',
        icon: RiMailLine,
      },
    ],
  },
  {
    key: 'kolory',
    title: 'Kolory i dostępność',
    icon: RiPaletteLine,
    items: [
      {
        key: 'contrastChecker',
        href: '/narzedzia/sprawdz-czytelnosc-kolorow',
        title: 'Kontrast i czytelność kolorów',
        description: 'Sprawdź czy kolory tekstu i tła są czytelne. Narzędzie oblicza kontrast według WCAG i pomoże dobrać odpowiedni kolor.',
        image: '/assets/tools/narzedzia-tester-kontrastu-kolorow-wcag.webp',
        icon: RiContrast2Line,
      },
      {
        key: 'paletteExtractor',
        href: '/narzedzia/ekstraktor-kolorow-z-obrazu',
        title: 'Ekstraktor kolorów z obrazu',
        description: 'Wgraj zdjęcie lub logo, a narzędzie wyciągnie dominujące kolory. Skopiuj kody wygenerowanych kolorów jednym kliknięciem.',
        image: '/assets/tools/narzedzia-generator-palety-kolorow-z-obrazu.webp',
        icon: RiPantoneLine,
      },
      {
        key: 'colorPalette',
        href: '/narzedzia/generator-palet-kolorow',
        title: 'Generator palet kolorów',
        description: 'Wybierz jeden kolor i wygeneruj 9 palet kolorów: monochromatyczną, komplementarną, triadyczną i inne.',
        image: '/assets/tools/narzedzia-generator-palet-kolorow-online.webp',
        icon: RiPaletteLine,
      },
    ],
  },
  {
    key: 'druk',
    title: 'Druk i materiały',
    icon: RiQrCodeLine,
    items: [
      {
        key: 'qrCode',
        href: '/narzedzia/darmowy-generator-kodow-qr',
        title: 'Darmowy generator kodów QR',
        description: 'Stwórz kod QR do strony, wizytówki vCard, menu lub ulotki. Eksport PNG i SVG, bez logowania, bez limitu.',
        image: '/assets/tools/narzedzia-generator-kodu-qr.webp',
        icon: RiQrCodeLine,
      },
    ],
  },
  {
    key: 'konwertery',
    title: 'Konwertery formatów',
    icon: RiLoopLeftLine,
    items: [
      {
        key: 'jpgToPng',
        href: '/narzedzia/konwerter-jpg-na-png',
        title: 'Konwerter JPG na PNG',
        description: 'Zamień pliki JPG na bezstratny PNG. Konwersja w przeglądarce, bez limitu.',
        image: '/assets/tools/jpg-png-to-webp-converter/jpg-png-na-webp-bez-limitu-pl.webp',
        icon: RiLoopLeftLine,
      },
      {
        key: 'webpToPng',
        href: '/narzedzia/konwerter-webp-na-png',
        title: 'Konwerter WebP na PNG',
        description: 'Zamień pliki WebP na bezstratny PNG. Konwersja lokalna, bez wysyłania na serwer.',
        image: '/assets/tools/jpg-png-to-webp-converter/jpg-png-na-webp-bez-limitu-pl.webp',
        icon: RiLoopLeftLine,
      },
      {
        key: 'svgToPng',
        href: '/narzedzia/konwerter-svg-na-png',
        title: 'Konwerter SVG na PNG',
        description: 'Zamień grafikę wektorową SVG na rastrowy PNG.',
        image: '/assets/tools/jpg-png-to-webp-converter/jpg-png-na-webp-bez-limitu-pl.webp',
        icon: RiLoopLeftLine,
      },
      {
        key: 'svgToJpg',
        href: '/narzedzia/konwerter-svg-na-jpg',
        title: 'Konwerter SVG na JPG',
        description: 'Zamień grafikę wektorową SVG na JPG. Mniejszy plik, pełna kompatybilność.',
        image: '/assets/tools/jpg-png-to-webp-converter/jpg-png-na-webp-bez-limitu-pl.webp',
        icon: RiLoopLeftLine,
      },
      {
        key: 'bmpToJpg',
        href: '/narzedzia/konwerter-bmp-na-jpg',
        title: 'Konwerter BMP na JPG',
        description: 'Zamień nieskompresowane pliki BMP na lekki JPG.',
        image: '/assets/tools/jpg-png-to-webp-converter/jpg-png-na-webp-bez-limitu-pl.webp',
        icon: RiLoopLeftLine,
      },
      {
        key: 'bmpToPng',
        href: '/narzedzia/konwerter-bmp-na-png',
        title: 'Konwerter BMP na PNG',
        description: 'Zamień pliki BMP na bezstratny PNG.',
        image: '/assets/tools/jpg-png-to-webp-converter/jpg-png-na-webp-bez-limitu-pl.webp',
        icon: RiLoopLeftLine,
      },
      {
        key: 'gifToPng',
        href: '/narzedzia/konwerter-gif-na-png',
        title: 'Konwerter GIF na PNG',
        description: 'Wyeksportuj pierwszą klatkę GIF-a jako statyczny obraz PNG.',
        image: '/assets/tools/jpg-png-to-webp-converter/jpg-png-na-webp-bez-limitu-pl.webp',
        icon: RiLoopLeftLine,
      },
      {
        key: 'gifToJpg',
        href: '/narzedzia/konwerter-gif-na-jpg',
        title: 'Konwerter GIF na JPG',
        description: 'Wyeksportuj pierwszą klatkę GIF-a jako JPG.',
        image: '/assets/tools/jpg-png-to-webp-converter/jpg-png-na-webp-bez-limitu-pl.webp',
        icon: RiLoopLeftLine,
      },
      {
        key: 'pngToWebpSimple',
        href: '/narzedzia/konwerter-png-na-webp',
        title: 'Konwerter PNG na WebP',
        description: 'Zamień grafiki PNG na WebP. Mniejsze pliki przy zachowaniu przezroczystości.',
        image: '/assets/tools/jpg-png-to-webp-converter/jpg-png-na-webp-bez-limitu-pl.webp',
        icon: RiLoopLeftLine,
      },
    ],
  },
];
