import { rgbToHex } from '@/lib/tools/color/convert';
import type { LayoutType, SignatureConfig, SpacingConfig, SpacingKey, StyleConfig, TextStyleConfig, ThemePreset } from '@/types/tools/email';
import type { Locale } from '@/lib/LocaleContext';
import { ui } from '@/lib/i18n/tools/email-signature';

export const STORAGE_KEY_BASE = 'arteon-email-signature-generator';

const SIGNATURE_COLOR_DARK = rgbToHex({ r: 17, g: 24, b: 39 });
const SIGNATURE_COLOR_WHITE = rgbToHex({ r: 255, g: 255, b: 255 });
const SIGNATURE_COLOR_BLUE = rgbToHex({ r: 37, g: 99, b: 235 });
const SIGNATURE_COLOR_PURPLE = rgbToHex({ r: 124, g: 58, b: 237 });
const SIGNATURE_COLOR_GREEN = rgbToHex({ r: 22, g: 163, b: 74 });
const SIGNATURE_COLOR_GRAY = rgbToHex({ r: 75, g: 85, b: 99 });

export const DEFAULT_STYLE: StyleConfig = {
  accentColor: SIGNATURE_COLOR_DARK,
  textColor: SIGNATURE_COLOR_DARK,
  backgroundColor: SIGNATURE_COLOR_WHITE,
  fontFamily: 'Arial, sans-serif',
  fontSize: 'normal',
  padding: 'medium',
  ctaRadius: 'full',
  showDivider: true,
  border: { left: false, right: false, top: false, bottom: false },
  socialIcons: { showIcons: false, iconSize: 'medium', colorMode: 'platform' },
  avatarShape: 'circle',
  avatarSize: 'medium',
  dividerStyle: 'solid',
  dividerWidth: 1,
  dividerColor: '',
};

export const DEFAULT_SPACING: SpacingConfig = {
  afterName: 4,
  afterTitle: 4,
  afterExtra: 6,
  afterContact: 4,
  afterSocials: 8,
  afterCta: 10,
  beforeLegal: 12,
};

export const DEFAULT_TEXT_STYLE: TextStyleConfig = {
  name: { color: null, sizeOffset: 0 },
  jobTitle: { color: null, sizeOffset: 0 },
  company: { color: null, sizeOffset: 0 },
  contact: { color: null, sizeOffset: 0 },
  socials: { color: null, sizeOffset: 0 },
  legal: { color: null, sizeOffset: 0 },
  customColors: [],
};

export const LAYOUT_SPACING_MAP: Record<LayoutType, SpacingKey[]> = {
  standard: ['afterName', 'afterTitle', 'afterExtra', 'afterContact', 'afterSocials', 'afterCta', 'beforeLegal'],
  'top-banner': ['afterExtra', 'afterContact', 'afterSocials', 'afterCta', 'beforeLegal'],
  'label-column': ['afterName', 'afterTitle', 'afterExtra', 'afterSocials', 'afterCta', 'beforeLegal'],
  centered: ['afterName', 'afterTitle', 'afterExtra', 'afterContact', 'afterSocials', 'afterCta', 'beforeLegal'],
  compact: ['afterSocials', 'beforeLegal'],
  'two-column': ['afterName', 'afterTitle', 'afterExtra', 'afterSocials', 'afterCta', 'beforeLegal'],
  minimal: ['afterName', 'afterTitle'],
  'bottom-bar': ['afterName', 'afterTitle', 'afterExtra', 'afterContact', 'afterSocials', 'beforeLegal'],
};

export const FONT_OPTIONS = [
  { value: 'Arial, sans-serif', label: 'Arial' },
  { value: 'Verdana, sans-serif', label: 'Verdana' },
  { value: 'Tahoma, sans-serif', label: 'Tahoma' },
  { value: '"Trebuchet MS", sans-serif', label: 'Trebuchet MS' },
  { value: 'Georgia, serif', label: 'Georgia' },
];

export function getSignatureLabels(locale: Locale) {
  const t = ui[locale];
  return {
    tel: t.labels.tel,
    email: t.labels.email,
    website: t.labels.website,
  };
}

export function getDefaultSignature(locale: Locale): SignatureConfig {
  if (locale === 'en') {
    return {
      fullName: 'John Smith',
      jobTitle: 'Web Developer',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'john.smith@example.com',
      phone: '+1 600 000 000',
      website: 'https://www.yoursite.com',
      address: '123 Main St, New York, NY 10001',
      extraLine: 'I build fast and functional websites.',
      ctaLabel: 'Book a free consultation',
      ctaUrl: 'https://www.yoursite.com',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/johnsmith',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'This message may contain confidential information. If you are not the intended recipient, please notify the sender and delete this message.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'de') {
    return {
      fullName: 'Max Mustermann',
      jobTitle: 'Web Developer',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'max.mustermann@example.com',
      phone: '+49 160 000 0000',
      website: 'https://www.ihreseite.de',
      address: 'Musterstraße 3, 10115 Berlin',
      extraLine: 'Ich entwickle schnelle und funktionale Websites.',
      ctaLabel: 'Kostenlose Beratung buchen',
      ctaUrl: 'https://www.ihreseite.de',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/maxmustermann',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Diese Nachricht kann vertrauliche Informationen enthalten. Wenn Sie nicht der beabsichtigte Empfänger sind, informieren Sie bitte den Absender und löschen Sie diese Nachricht.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'fr') {
    return {
      fullName: 'Pierre Dupont',
      jobTitle: 'Développeur Web',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'pierre.dupont@example.com',
      phone: '+33 6 00 00 00 00',
      website: 'https://www.votresite.fr',
      address: '3 rue de Rivoli, 75001 Paris',
      extraLine: 'Je conçois des sites web rapides et fonctionnels.',
      ctaLabel: 'Réserver une consultation gratuite',
      ctaUrl: 'https://www.votresite.fr',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/pierredupont',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: "Ce message peut contenir des informations confidentielles. Si vous n'êtes pas le destinataire prévu, veuillez en informer l'expéditeur et supprimer ce message.",
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'it') {
    return {
      fullName: 'Mario Rossi',
      jobTitle: 'Sviluppatore Web',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'mario.rossi@example.com',
      phone: '+39 333 123 4567',
      website: 'https://www.iltuosito.it',
      address: 'Via Roma 1, 00100 Roma',
      extraLine: 'Creo siti web veloci e funzionali.',
      ctaLabel: 'Prenota consulenza gratuita',
      ctaUrl: 'https://www.iltuosito.it',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/mariorossi',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Questo messaggio potrebbe contenere informazioni riservate. Se non sei il destinatario previsto, informa il mittente ed elimina questo messaggio.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'es') {
    return {
      fullName: 'Juan García',
      jobTitle: 'Desarrollador Web',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'juan.garcia@example.com',
      phone: '+34 600 000 000',
      website: 'https://www.susitio.com',
      address: 'C/ Mayor 3, 28001 Madrid',
      extraLine: 'Diseño sitios web rápidos y funcionales.',
      ctaLabel: 'Reservar consulta gratuita',
      ctaUrl: 'https://www.susitio.com',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/juangarcia',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Este mensaje puede contener información confidencial. Si no es el destinatario previsto, informe al remitente y elimine este mensaje.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'pt') {
    return {
      fullName: 'João Silva',
      jobTitle: 'Programador Web',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'joao.silva@example.com',
      phone: '+351 912 345 678',
      website: 'https://www.oseusite.pt',
      address: 'Rua Augusta 100, 1100-053 Lisboa',
      extraLine: 'Crio sites rápidos e funcionais.',
      ctaLabel: 'Marcar consulta gratuita',
      ctaUrl: 'https://www.oseusite.pt',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/joaosilva',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Esta mensagem pode conter informações confidenciais. Se não for o destinatário pretendido, por favor informe o remetente e elimine esta mensagem.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'ro') {
    return {
      fullName: 'Ion Popescu',
      jobTitle: 'Dezvoltator Web',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'ion.popescu@example.com',
      phone: '+40 721 234 567',
      website: 'https://www.site-ul-dvs.ro',
      address: 'Str. Exemplu 1, București',
      extraLine: 'Creez site-uri web rapide și funcționale.',
      ctaLabel: 'Rezervați consultanță gratuită',
      ctaUrl: 'https://www.site-ul-dvs.ro',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/ionpopescu',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Acest mesaj poate conține informații confidențiale. Dacă nu sunteți destinatarul prevăzut, vă rugăm să informați expeditorul și să ștergeți acest mesaj.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'nl') {
    return {
      fullName: 'Jan de Vries',
      jobTitle: 'Webontwikkelaar',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'jan.devries@example.com',
      phone: '+31 6 12345678',
      website: 'https://www.uwwebsite.nl',
      address: 'Voorbeeldstraat 1, 1000 AA Amsterdam',
      extraLine: 'Ik maak snelle en functionele websites.',
      ctaLabel: 'Gratis adviesgesprek boeken',
      ctaUrl: 'https://www.uwwebsite.nl',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/jandevries',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Dit bericht kan vertrouwelijke informatie bevatten. Als u niet de beoogde ontvanger bent, informeer dan de afzender en verwijder dit bericht.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'hu') {
    return {
      fullName: 'Kovács János',
      jobTitle: 'Webfejlesztő',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'kovacs.janos@example.com',
      phone: '+36 30 123 4567',
      website: 'https://www.azweboldala.hu',
      address: 'Példa utca 1, 1000 Budapest',
      extraLine: 'Gyors és funkcionális weboldalakat készítek.',
      ctaLabel: 'Ingyenes konzultáció foglalása',
      ctaUrl: 'https://www.azweboldala.hu',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/kovacsjanos',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Ez az üzenet bizalmas információkat tartalmazhat. Ha nem Ön a címzett, kérjük, értesítse a feladót és törölje ezt az üzenetet.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'tr') {
    return {
      fullName: 'Ahmet Yılmaz',
      jobTitle: 'Web Geliştirici',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'ahmet.yilmaz@ornek.com',
      phone: '+90 532 123 4567',
      website: 'https://www.siteniz.com',
      address: 'Atatürk Cad. No:1, İstanbul 34000',
      extraLine: 'Hızlı ve işlevsel web siteleri geliştiriyorum.',
      ctaLabel: 'Ücretsiz danışmanlık alın',
      ctaUrl: 'https://www.siteniz.com',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/ahmetyilmaz',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Bu mesaj gizli bilgi içerebilir. Hedeflenen alıcı değilseniz lütfen göndereni bilgilendirin ve bu mesajı silin.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'cs') {
    return {
      fullName: 'Jan Nov\u00e1k',
      jobTitle: 'Webov\u00fd v\u00fdvoj\u00e1\u0159',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'jan.novak@priklad.cz',
      phone: '+420 601 234 567',
      website: 'https://www.vasedomena.cz',
      address: 'V\u00e1clavsk\u00e9 n\u00e1m. 1, 110 00 Praha',
      extraLine: 'Tvo\u0159\u00edm rychl\u00e9 a funk\u010dn\u00ed webov\u00e9 str\u00e1nky.',
      ctaLabel: 'Objednejte si bezplatnou konzultaci',
      ctaUrl: 'https://www.vasedomena.cz',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/jannovak',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote:
        'Tato zpr\u00e1va m\u016f\u017ee obsahovat d\u016fv\u011brn\u00e9 informace. Pokud nejste zam\u00fd\u0161len\u00fdm p\u0159\u00edjemcem, informujte odes\u00edlatele a tuto zpr\u00e1vu sma\u017ete.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'sv') {
    return {
      fullName: 'Erik Johansson',
      jobTitle: 'Webbutvecklare',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'erik.johansson@exempel.se',
      phone: '+46 70 123 45 67',
      website: 'https://www.dinwebbplats.se',
      address: 'Kungsgatan 10, 111 43 Stockholm',
      extraLine: 'Jag bygger snabba och funktionella webbplatser.',
      ctaLabel: 'Boka en gratis konsultation',
      ctaUrl: 'https://www.dinwebbplats.se',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/erikjohansson',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Detta meddelande kan inneh\u00e5lla konfidentiell information. Om du inte \u00e4r den avsedda mottagaren, v\u00e4nligen meddela avs\u00e4ndaren och radera detta meddelande.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'sq') {
    return {
      fullName: 'Arben Hoxha',
      jobTitle: 'Zhvillues Uebi',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'arben.hoxha@shembull.al',
      phone: '+355 69 123 4567',
      website: 'https://www.faqjajuaj.al',
      address: 'Rruga e Durr\u00ebsit 15, Tiran\u00eb 1001',
      extraLine: 'Nd\u00ebrtoj faqe interneti t\u00eb shpejta dhe funksionale.',
      ctaLabel: 'Rezervoni nj\u00eb konsultim falas',
      ctaUrl: 'https://www.faqjajuaj.al',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/arbenhoxha',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Ky mesazh mund t\u00eb p\u00ebrmbaj\u00eb informacion konfidencial. N\u00ebse nuk jeni marr\u00ebsi i synuar, ju lutem njoftoni d\u00ebrgu esin dhe fshini k\u00ebt\u00eb mesazh.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'da') {
    return {
      fullName: 'Lars Nielsen',
      jobTitle: 'Webudvikler',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'lars.nielsen@eksempel.dk',
      phone: '+45 12 34 56 78',
      website: 'https://www.dinhjemmeside.dk',
      address: 'Str\u00f8get 1, 1000 K\u00f8benhavn',
      extraLine: 'Jeg bygger hurtige og funktionelle hjemmesider.',
      ctaLabel: 'Book en gratis konsultation',
      ctaUrl: 'https://www.dinhjemmeside.dk',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/larsnielsen',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Denne besked kan indeholde fortrolige oplysninger. Hvis du ikke er den tilsigtede modtager, bedes du informere afsenderen og slette denne besked.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'fi') {
    return {
      fullName: 'Matti Meik\u00e4l\u00e4inen',
      jobTitle: 'Verkkokehitt\u00e4j\u00e4',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'matti.meikalainen@esimerkki.fi',
      phone: '+358 40 123 4567',
      website: 'https://www.sivustosi.fi',
      address: 'Mannerheimintie 10, 00100 Helsinki',
      extraLine: 'Rakennan nopeita ja toimivia verkkosivuja.',
      ctaLabel: 'Varaa ilmainen konsultaatio',
      ctaUrl: 'https://www.sivustosi.fi',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/mattimeikalainen',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote:
        'T\u00e4m\u00e4 viesti voi sis\u00e4lt\u00e4\u00e4 luottamuksellista tietoa. Jos et ole tarkoitettu vastaanottaja, ilmoita l\u00e4hett\u00e4j\u00e4lle ja poista t\u00e4m\u00e4 viesti.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'no') {
    return {
      fullName: 'Ola Nordmann',
      jobTitle: 'Webutvikler',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'ola.nordmann@eksempel.no',
      phone: '+47 40 12 34 56',
      website: 'https://www.dinside.no',
      address: 'Karl Johans gate 10, 0154 Oslo',
      extraLine: 'Jeg lager raske og funksjonelle nettsider.',
      ctaLabel: 'Book en gratis konsultasjon',
      ctaUrl: 'https://www.dinside.no',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/olanordmann',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Denne meldingen kan inneholde konfidensiell informasjon. Hvis du ikke er den tiltenkte mottakeren, vennligst informer avsenderen og slett denne meldingen.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'sk') {
    return {
      fullName: 'J\u00e1n Nov\u00e1k',
      jobTitle: 'Web Developer',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'jan.novak@priklad.sk',
      phone: '+421 900 123 456',
      website: 'https://www.vasastranka.sk',
      address: 'Hlavn\u00e1 1, 811 01 Bratislava',
      extraLine: 'Vytv\u00e1ram r\u00fdchle a funk\u010dn\u00e9 webov\u00e9 str\u00e1nky.',
      ctaLabel: 'Rezervova\u0165 bezplatn\u00fa konzult\u00e1ciu',
      ctaUrl: 'https://www.vasastranka.sk',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/jannovak',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote:
        'T\u00e1to spr\u00e1va m\u00f4\u017ee obsahova\u0165 d\u00f4vern\u00e9 inform\u00e1cie. Ak nie ste ur\u010den\u00fdm pr\u00edjemcom, informujte odosielate\u013ea a t\u00fato spr\u00e1vu vyma\u017ete.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'hr') {
    return {
      fullName: 'Ivan Horvat',
      jobTitle: 'Web Developer',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'ivan.horvat@primjer.hr',
      phone: '+385 91 123 4567',
      website: 'https://www.vasastranica.hr',
      address: 'Ilica 1, 10000 Zagreb',
      extraLine: 'Izra\u0111ujem brze i funkcionalne web stranice.',
      ctaLabel: 'Rezervirajte besplatnu konzultaciju',
      ctaUrl: 'https://www.vasastranica.hr',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/ivanhorvat',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'Ova poruka mo\u017ee sadr\u017eavati povjerljive informacije. Ako niste predvi\u0111eni primatelj, obavijestite po\u0161iljatelja i izbri\u0161ite ovu poruku.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'lt') {
    return {
      fullName: 'Jonas Kazlauskas',
      jobTitle: 'Web Developer',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'jonas.kazlauskas@pavyzdys.lt',
      phone: '+370 600 12345',
      website: 'https://www.jusu-svetaine.lt',
      address: 'Gedimino pr. 1, 01103 Vilnius',
      extraLine: 'Kuriu greitas ir funkcionalias svetaines.',
      ctaLabel: 'Rezervuoti nemokam\u0105 konsultacij\u0105',
      ctaUrl: 'https://www.jusu-svetaine.lt',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/jonaskazlauskas',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote:
        '\u0160is prane\u0161imas gali tur\u0117ti konfidencialios informacijos. Jei nesate numatytas gav\u0117jas, prane\u0161kite siunt\u0117jui ir i\u0161trinkite \u0161\u012f prane\u0161im\u0105.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'sl') {
    return {
      fullName: 'Janez Novak',
      jobTitle: 'Web Developer',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'janez.novak@primer.si',
      phone: '+386 40 123 456',
      website: 'https://www.vasastran.si',
      address: 'Pre\u0161ernov trg 1, 1000 Ljubljana',
      extraLine: 'Izdelujem hitre in funkcionalne spletne strani.',
      ctaLabel: 'Rezervirajte brezpla\u010den posvet',
      ctaUrl: 'https://www.vasastran.si',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/janeznovak',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote: 'To sporo\u010dilo lahko vsebuje zaupne informacije. \u010ce niste predvideni prejemnik, obvestite po\u0161iljatelja in izbri\u0161ite to sporo\u010dilo.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'uk') {
    return {
      fullName: '\u041e\u043b\u0435\u043d\u0430 \u041a\u043e\u0432\u0430\u043b\u0435\u043d\u043a\u043e',
      jobTitle: '\u0412\u0435\u0431-\u0440\u043e\u0437\u0440\u043e\u0431\u043d\u0438\u043a',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'olena.kovalenko@priklad.ua',
      phone: '+380 50 123 4567',
      website: 'https://www.vashsait.ua',
      address: '\u0432\u0443\u043b. \u0425\u0440\u0435\u0449\u0430\u0442\u0438\u043a 1, \u041a\u0438\u0457\u0432, 01001',
      extraLine:
        '\u0421\u0442\u0432\u043e\u0440\u044e\u044e \u0448\u0432\u0438\u0434\u043a\u0456 \u0442\u0430 \u0444\u0443\u043d\u043a\u0446\u0456\u043e\u043d\u0430\u043b\u044c\u043d\u0456 \u0432\u0435\u0431\u0441\u0430\u0439\u0442\u0438.',
      ctaLabel:
        '\u0417\u0430\u043c\u043e\u0432\u0438\u0442\u0438 \u0431\u0435\u0437\u043a\u043e\u0448\u0442\u043e\u0432\u043d\u0443 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u0446\u0456\u044e',
      ctaUrl: 'https://www.vashsait.ua',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/olenakovalenko',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote:
        '\u0426\u0435\u0439 \u043b\u0438\u0441\u0442 \u043c\u043e\u0436\u0435 \u043c\u0456\u0441\u0442\u0438\u0442\u0438 \u043a\u043e\u043d\u0444\u0456\u0434\u0435\u043d\u0446\u0456\u0439\u043d\u0443 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044e. \u042f\u043a\u0449\u043e \u0432\u0438 \u043d\u0435 \u0454 \u0430\u0434\u0440\u0435\u0441\u0430\u0442\u043e\u043c, \u043f\u043e\u0432\u0456\u0434\u043e\u043c\u0442\u0435 \u0432\u0456\u0434\u043f\u0440\u0430\u0432\u043d\u0438\u043a\u0430 \u0442\u0430 \u0432\u0438\u0434\u0430\u043b\u0456\u0442\u044c \u0446\u0435\u0439 \u043b\u0438\u0441\u0442.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'bg') {
    return {
      fullName: '\u0418\u0432\u0430\u043d \u041f\u0435\u0442\u0440\u043e\u0432',
      jobTitle: '\u0423\u0435\u0431 \u0440\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u0447\u0438\u043a',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'ivan.petrov@primer.bg',
      phone: '+359 88 123 4567',
      website: 'https://www.vashiyatsait.bg',
      address: '\u0443\u043b. \u0412\u0438\u0442\u043e\u0448\u0430 15, \u0421\u043e\u0444\u0438\u044f, 1000',
      extraLine:
        '\u0421\u044a\u0437\u0434\u0430\u0432\u0430\u043c \u0431\u044a\u0440\u0437\u0438 \u0438 \u0444\u0443\u043d\u043a\u0446\u0438\u043e\u043d\u0430\u043b\u043d\u0438 \u0443\u0435\u0431\u0441\u0430\u0439\u0442\u043e\u0432\u0435.',
      ctaLabel: '\u0417\u0430\u043f\u0430\u0437\u0435\u0442\u0435 \u0431\u0435\u0437\u043f\u043b\u0430\u0442\u043d\u0430 \u043a\u043e\u043d\u0441\u0443\u043b\u0442\u0430\u0446\u0438\u044f',
      ctaUrl: 'https://www.vashiyatsait.bg',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/ivanpetrov',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote:
        '\u0422\u043e\u0432\u0430 \u0441\u044a\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u043c\u043e\u0436\u0435 \u0434\u0430 \u0441\u044a\u0434\u044a\u0440\u0436\u0430 \u043f\u043e\u0432\u0435\u0440\u0438\u0442\u0435\u043b\u043d\u0430 \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f. \u0410\u043a\u043e \u043d\u0435 \u0441\u0442\u0435 \u043f\u0440\u0435\u0434\u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f\u0442 \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b, \u043c\u043e\u043b\u044f \u0443\u0432\u0435\u0434\u043e\u043c\u0435\u0442\u0435 \u043f\u043e\u0434\u0430\u0442\u0435\u043b\u044f \u0438 \u0438\u0437\u0442\u0440\u0438\u0439\u0442\u0435 \u0442\u043e\u0432\u0430 \u0441\u044a\u043e\u0431\u0449\u0435\u043d\u0438\u0435.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  if (locale === 'el') {
    return {
      fullName: '\u0393\u03b9\u03ac\u03bd\u03bd\u03b7\u03c2 \u03a0\u03b1\u03c0\u03b1\u03b4\u03cc\u03c0\u03bf\u03c5\u03bb\u03bf\u03c2',
      jobTitle: '\u03a0\u03c1\u03bf\u03b3\u03c1\u03b1\u03bc\u03bc\u03b1\u03c4\u03b9\u03c3\u03c4\u03ae\u03c2 \u0399\u03c3\u03c4\u03bf\u03cd',
      company: 'Arteon Agency',
      topLine: '',
      nameTag: '',
      email: 'giannis.papadopoulos@paradeigma.gr',
      phone: '+30 210 123 4567',
      website: 'https://www.istoselida-sas.gr',
      address: '\u039b\u03b5\u03c9\u03c6. \u039a\u03b7\u03c6\u03b9\u03c3\u03af\u03b1\u03c2 15, \u0391\u03b8\u03ae\u03bd\u03b1, 11523',
      extraLine:
        '\u0394\u03b7\u03bc\u03b9\u03bf\u03c5\u03c1\u03b3\u03ce \u03b3\u03c1\u03ae\u03b3\u03bf\u03c1\u03b5\u03c2 \u03ba\u03b1\u03b9 \u03bb\u03b5\u03b9\u03c4\u03bf\u03c5\u03c1\u03b3\u03b9\u03ba\u03ad\u03c2 \u03b9\u03c3\u03c4\u03bf\u03c3\u03b5\u03bb\u03af\u03b4\u03b5\u03c2.',
      ctaLabel: '\u039a\u03bb\u03b5\u03af\u03c3\u03c4\u03b5 \u03b4\u03c9\u03c1\u03b5\u03ac\u03bd \u03c3\u03c5\u03bc\u03b2\u03bf\u03c5\u03bb\u03b5\u03c5\u03c4\u03b9\u03ba\u03ae',
      ctaUrl: 'https://www.istoselida-sas.gr',
      cta2Label: '',
      cta2Url: '',
      socials: {
        linkedin: 'https://www.linkedin.com/in/giannispapadopoulos',
        instagram: '',
        facebook: '',
        tiktok: '',
        youtube: '',
        x: '',
        github: '',
        dribbble: '',
        behance: '',
        whatsapp: '',
        telegram: '',
        pinterest: '',
      },
      legalNote:
        '\u0391\u03c5\u03c4\u03cc \u03c4\u03bf \u03bc\u03ae\u03bd\u03c5\u03bc\u03b1 \u03bc\u03c0\u03bf\u03c1\u03b5\u03af \u03bd\u03b1 \u03c0\u03b5\u03c1\u03b9\u03ad\u03c7\u03b5\u03b9 \u03b5\u03bc\u03c0\u03b9\u03c3\u03c4\u03b5\u03c5\u03c4\u03b9\u03ba\u03ad\u03c2 \u03c0\u03bb\u03b7\u03c1\u03bf\u03c6\u03bf\u03c1\u03af\u03b5\u03c2. \u0391\u03bd \u03b4\u03b5\u03bd \u03b5\u03af\u03c3\u03c4\u03b5 \u03bf \u03c0\u03c1\u03bf\u03bf\u03c1\u03b9\u03b6\u03cc\u03bc\u03b5\u03bd\u03bf\u03c2 \u03c0\u03b1\u03c1\u03b1\u03bb\u03ae\u03c0\u03c4\u03b7\u03c2, \u03c0\u03b1\u03c1\u03b1\u03ba\u03b1\u03bb\u03bf\u03cd\u03bc\u03b5 \u03b5\u03bd\u03b7\u03bc\u03b5\u03c1\u03ce\u03c3\u03c4\u03b5 \u03c4\u03bf\u03bd \u03b1\u03c0\u03bf\u03c3\u03c4\u03bf\u03bb\u03ad\u03b1 \u03ba\u03b1\u03b9 \u03b4\u03b9\u03b1\u03b3\u03c1\u03ac\u03c8\u03c4\u03b5 \u03b1\u03c5\u03c4\u03cc \u03c4\u03bf \u03bc\u03ae\u03bd\u03c5\u03bc\u03b1.',
      formalLine: '',
      avatarUrl: '',
    };
  }
  return {
    fullName: 'Jan Kowalski',
    jobTitle: 'Web Developer',
    company: 'Arteon Agency',
    topLine: '',
    nameTag: '',
    email: 'jan.kowalski@example.com',
    phone: '+48 000 000 000',
    website: 'https://www.twojadomena.pl',
    address: 'ul. Dobra 3, 30-000 Krak\u00f3w',
    extraLine: 'Projektuj\u0119 szybkie i funkcjonalne strony WWW.',
    ctaLabel: 'Um\u00f3w bezp\u0142atn\u0105 konsultacj\u0119',
    ctaUrl: 'https://www.twojadomena.pl',
    cta2Label: '',
    cta2Url: '',
    socials: {
      linkedin: 'https://www.linkedin.com/in/jankowalski',
      instagram: '',
      facebook: '',
      tiktok: '',
      youtube: '',
      x: '',
      github: '',
      dribbble: '',
      behance: '',
      whatsapp: '',
      telegram: '',
      pinterest: '',
    },
    legalNote: 'Ta wiadomość może zawierać informacje poufne. Jeżeli nie jesteś jej adresatem, poinformuj nadawcę i usuń wiadomość.',
    formalLine: '',
    avatarUrl: '',
  };
}

export function getThemePresets(locale: Locale): ThemePreset[] {
  const t = ui[locale];
  return [
    { id: 'classic-dark', name: t.themes.dark, accentColor: SIGNATURE_COLOR_DARK, textColor: SIGNATURE_COLOR_DARK },
    { id: 'modern-blue', name: t.themes.blue, accentColor: SIGNATURE_COLOR_BLUE, textColor: SIGNATURE_COLOR_DARK },
    { id: 'creative-purple', name: t.themes.purple, accentColor: SIGNATURE_COLOR_PURPLE, textColor: SIGNATURE_COLOR_DARK },
    { id: 'eco-green', name: t.themes.green, accentColor: SIGNATURE_COLOR_GREEN, textColor: SIGNATURE_COLOR_DARK },
    { id: 'minimal', name: t.themes.gray, accentColor: SIGNATURE_COLOR_GRAY, textColor: SIGNATURE_COLOR_DARK },
  ];
}
