export type {
  CopyStatus,
  FontSizeOption,
  MarginOption,
  CtaRadiusOption,
  AvatarShape,
  AvatarSize,
  DividerStyle,
  DividerWidth,
  SocialKey,
  SocialIconSize,
  SocialIconColorMode,
  SocialIconSettings,
  ActivePanel,
  TextElementKey,
  TextElementStyle,
  TextStyleConfig,
  LayoutType,
  BorderSides,
  SignatureConfig,
  StyleConfig,
  ThemePreset,
  SpacingKey,
  SpacingConfig,
} from '@/types/tools/email';
