// Format technical properties
const FORMATS = {
  jpg: { name: 'JPG', full: 'JPEG', lossy: true, lossless: false, transparency: false, animation: false, vector: false, typical: 'photos', maxColors: 'millions', browser: 'universal' },
  png: {
    name: 'PNG',
    full: 'Portable Network Graphics',
    lossy: false,
    lossless: true,
    transparency: true,
    animation: false,
    vector: false,
    typical: 'graphics with transparency',
    maxColors: 'millions',
    browser: 'universal',
  },
  webp: {
    name: 'WebP',
    full: 'WebP',
    lossy: true,
    lossless: true,
    transparency: true,
    animation: true,
    vector: false,
    typical: 'web images',
    maxColors: 'millions',
    browser: 'Chrome, Firefox, Safari 14+, Edge',
  },
  avif: {
    name: 'AVIF',
    full: 'AV1 Image File Format',
    lossy: true,
    lossless: true,
    transparency: true,
    animation: true,
    vector: false,
    typical: 'modern web images',
    maxColors: 'millions',
    browser: 'Chrome 85+, Firefox 93+, Safari 16.4+',
  },
  gif: {
    name: 'GIF',
    full: 'Graphics Interchange Format',
    lossy: false,
    lossless: true,
    transparency: true,
    animation: true,
    vector: false,
    typical: 'simple animations',
    maxColors: '256',
    browser: 'universal',
  },
  bmp: { name: 'BMP', full: 'Bitmap', lossy: false, lossless: true, transparency: false, animation: false, vector: false, typical: 'uncompressed images', maxColors: 'millions', browser: 'universal' },
  tiff: {
    name: 'TIFF',
    full: 'Tagged Image File Format',
    lossy: false,
    lossless: true,
    transparency: true,
    animation: false,
    vector: false,
    typical: 'print and archival',
    maxColors: 'millions',
    browser: 'limited',
  },
  svg: {
    name: 'SVG',
    full: 'Scalable Vector Graphics',
    lossy: false,
    lossless: true,
    transparency: true,
    animation: true,
    vector: true,
    typical: 'logos and icons',
    maxColors: 'unlimited',
    browser: 'universal',
  },
  heic: {
    name: 'HEIC',
    full: 'High Efficiency Image Container',
    lossy: true,
    lossless: true,
    transparency: false,
    animation: false,
    vector: false,
    typical: 'Apple device photos',
    maxColors: 'millions',
    browser: 'Safari only',
  },
};

// Section title translations per locale
const TITLES = {
  en: {
    why: (s, t) => `Why convert ${s} to ${t}?`,
    how: (s, t) => `How to convert ${s} to ${t}`,
    comparison: (s, t) => `${s} vs ${t} \u2013 key differences`,
    when: (s, t) => `When should you convert ${s} to ${t}?`,
    features: (s, t) => `What makes this ${s} to ${t} converter different?`,
    regional: (s, t) => `${s} to ${t} conversion in practice`,
    tips: (s, t) => `Tips for converting ${s} to ${t}`,
    faq: (s, t) => `Frequently asked questions about ${s} to ${t} conversion`,
    contact: 'Help us improve our tools',
    contactDesc: 'Have an idea, found a bug, or want to suggest a feature? Drop us a message \u2013 we respond within 24 hours.',
    carousel: 'Explore more free tools',
  },
  pl: {
    why: (s, t) => `Dlaczego warto konwertowa\u0107 ${s} na ${t}?`,
    how: (s, t) => `Jak przekonwertowa\u0107 ${s} na ${t}?`,
    comparison: (s, t) => `${s} a ${t} \u2013 por\u00f3wnanie format\u00f3w`,
    when: (s, t) => `Kiedy konwertowa\u0107 ${s} na ${t}?`,
    features: (s, t) => `Co wyr\u00f3\u017cnia konwerter ${s} na ${t}?`,
    regional: (s, t) => `Konwersja ${s} na ${t} w praktyce`,
    tips: (s, t) => `Na co zwr\u00f3ci\u0107 uwag\u0119 przy konwersji ${s} na ${t}?`,
    faq: (s, t) => `Najcz\u0119\u015bciej zadawane pytania o konwersji ${s} na ${t}`,
    contact: 'Pom\u00f3\u017c nam ulepszy\u0107 narz\u0119dzia',
    contactDesc:
      'Masz pomys\u0142 na now\u0105 funkcj\u0119, znalaz\u0142e\u015b b\u0142\u0105d lub chcesz zaproponowa\u0107 inne narz\u0119dzie? Napisz do nas \u2013 odpowiadamy w ci\u0105gu 24 godzin.',
    carousel: 'Sprawd\u017a inne narz\u0119dzia',
  },
  de: {
    why: (s, t) => `Warum ${s} in ${t} konvertieren?`,
    how: (s, t) => `So konvertieren Sie ${s} in ${t}`,
    comparison: (s, t) => `${s} vs. ${t} \u2013 die wichtigsten Unterschiede`,
    when: (s, t) => `Wann sollten Sie ${s} in ${t} konvertieren?`,
    features: (s, t) => `Was zeichnet diesen ${s}-zu-${t}-Konverter aus?`,
    regional: (s, t) => `${s}-zu-${t}-Konvertierung in der Praxis`,
    tips: (s, t) => `Tipps f\u00fcr die Konvertierung von ${s} in ${t}`,
    faq: (s, t) => `H\u00e4ufig gestellte Fragen zur Konvertierung von ${s} in ${t}`,
    contact: 'Helfen Sie uns, unsere Tools zu verbessern',
    contactDesc: 'Haben Sie eine Idee, einen Fehler gefunden oder m\u00f6chten Sie eine Funktion vorschlagen? Schreiben Sie uns \u2013 wir antworten innerhalb von 24 Stunden.',
    carousel: 'Entdecken Sie weitere kostenlose Tools',
  },
  fr: {
    why: (s, t) => `Pourquoi convertir ${s} en ${t}\u00a0?`,
    how: (s, t) => `Comment convertir ${s} en ${t}`,
    comparison: (s, t) => `${s} vs ${t} \u2013 les diff\u00e9rences cl\u00e9s`,
    when: (s, t) => `Quand faut-il convertir ${s} en ${t}\u00a0?`,
    features: (s, t) => `Qu\u2019est-ce qui distingue ce convertisseur ${s} vers ${t}\u00a0?`,
    regional: (s, t) => `Conversion ${s} vers ${t} en pratique`,
    tips: (s, t) => `Conseils pour convertir ${s} en ${t}`,
    faq: (s, t) => `Questions fr\u00e9quentes sur la conversion ${s} vers ${t}`,
    contact: 'Aidez-nous \u00e0 am\u00e9liorer nos outils',
    contactDesc: 'Vous avez une id\u00e9e, trouv\u00e9 un bug ou souhaitez sugg\u00e9rer une fonctionnalit\u00e9\u00a0? \u00c9crivez-nous \u2013 nous r\u00e9pondons sous 24 heures.',
    carousel: 'D\u00e9couvrez d\u2019autres outils gratuits',
  },
  es: {
    why: (s, t) => `\u00bfPor qu\u00e9 convertir ${s} a ${t}?`,
    how: (s, t) => `C\u00f3mo convertir ${s} a ${t}`,
    comparison: (s, t) => `${s} vs ${t} \u2013 diferencias clave`,
    when: (s, t) => `\u00bfCu\u00e1ndo conviene convertir ${s} a ${t}?`,
    features: (s, t) => `\u00bfQu\u00e9 diferencia a este convertidor de ${s} a ${t}?`,
    regional: (s, t) => `Conversi\u00f3n de ${s} a ${t} en la pr\u00e1ctica`,
    tips: (s, t) => `Consejos para convertir ${s} a ${t}`,
    faq: (s, t) => `Preguntas frecuentes sobre la conversi\u00f3n de ${s} a ${t}`,
    contact: 'Ay\u00fadanos a mejorar nuestras herramientas',
    contactDesc: '\u00bfTienes una idea, encontraste un error o quieres sugerir una funci\u00f3n? Escr\u00edbenos \u2013 respondemos en 24 horas.',
    carousel: 'Descubre m\u00e1s herramientas gratuitas',
  },
  it: {
    why: (s, t) => `Perch\u00e9 convertire ${s} in ${t}?`,
    how: (s, t) => `Come convertire ${s} in ${t}`,
    comparison: (s, t) => `${s} vs ${t} \u2013 le differenze principali`,
    when: (s, t) => `Quando conviene convertire ${s} in ${t}?`,
    features: (s, t) => `Cosa distingue questo convertitore da ${s} a ${t}?`,
    regional: (s, t) => `Conversione da ${s} a ${t} nella pratica`,
    tips: (s, t) => `Consigli per la conversione da ${s} a ${t}`,
    faq: (s, t) => `Domande frequenti sulla conversione da ${s} a ${t}`,
    contact: 'Aiutaci a migliorare i nostri strumenti',
    contactDesc: "Hai un'idea, trovato un bug o vuoi suggerire una funzione? Scrivici \u2013 rispondiamo entro 24 ore.",
    carousel: 'Scopri altri strumenti gratuiti',
  },
  pt: {
    why: (s, t) => `Por que converter ${s} para ${t}?`,
    how: (s, t) => `Como converter ${s} para ${t}`,
    comparison: (s, t) => `${s} vs ${t} \u2013 diferen\u00e7as principais`,
    when: (s, t) => `Quando converter ${s} para ${t}?`,
    features: (s, t) => `O que diferencia este conversor de ${s} para ${t}?`,
    regional: (s, t) => `Convers\u00e3o de ${s} para ${t} na pr\u00e1tica`,
    tips: (s, t) => `Dicas para converter ${s} para ${t}`,
    faq: (s, t) => `Perguntas frequentes sobre a convers\u00e3o de ${s} para ${t}`,
    contact: 'Ajude-nos a melhorar as nossas ferramentas',
    contactDesc: 'Tem uma ideia, encontrou um bug ou quer sugerir uma funcionalidade? Escreva-nos \u2013 respondemos em 24 horas.',
    carousel: 'Descubra mais ferramentas gratuitas',
  },
  cs: {
    why: (s, t) => `Pro\u010d p\u0159ev\u00e1d\u011bt ${s} na ${t}?`,
    how: (s, t) => `Jak p\u0159ev\u00e9st ${s} na ${t}`,
    comparison: (s, t) => `${s} vs ${t} \u2013 hlavn\u00ed rozd\u00edly`,
    when: (s, t) => `Kdy p\u0159ev\u00e1d\u011bt ${s} na ${t}?`,
    features: (s, t) => `\u010c\u00edm se tento p\u0159evodn\u00edk ${s} na ${t} li\u0161\u00ed?`,
    regional: (s, t) => `P\u0159evod ${s} na ${t} v praxi`,
    tips: (s, t) => `Tipy pro p\u0159evod ${s} na ${t}`,
    faq: (s, t) => `\u010casto kladen\u00e9 ot\u00e1zky o p\u0159evodu ${s} na ${t}`,
    contact: 'Pomozte n\u00e1m vylep\u0161it na\u0161e n\u00e1stroje',
    contactDesc: 'M\u00e1te n\u00e1pad, na\u0161li jste chybu nebo chcete navrhnout funkci? Napi\u0161te n\u00e1m \u2013 odpov\u00edd\u00e1me do 24 hodin.',
    carousel: 'Objevte dal\u0161\u00ed bezplatn\u00e9 n\u00e1stroje',
  },
  da: {
    why: (s, t) => `Hvorfor konvertere ${s} til ${t}?`,
    how: (s, t) => `S\u00e5dan konverterer du ${s} til ${t}`,
    comparison: (s, t) => `${s} vs ${t} \u2013 de vigtigste forskelle`,
    when: (s, t) => `Hvorn\u00e5r skal du konvertere ${s} til ${t}?`,
    features: (s, t) => `Hvad g\u00f8r denne ${s}-til-${t}-konverter anderledes?`,
    regional: (s, t) => `Konvertering af ${s} til ${t} i praksis`,
    tips: (s, t) => `Tips til konvertering af ${s} til ${t}`,
    faq: (s, t) => `Ofte stillede sp\u00f8rgsm\u00e5l om konvertering af ${s} til ${t}`,
    contact: 'Hj\u00e6lp os med at forbedre vores v\u00e6rkt\u00f8jer',
    contactDesc: 'Har du en id\u00e9, fundet en fejl eller vil foresl\u00e5 en funktion? Skriv til os \u2013 vi svarer inden for 24 timer.',
    carousel: 'Udforsk flere gratis v\u00e6rkt\u00f8jer',
  },
  el: {
    why: (s, t) => `\u0393\u03b9\u03b1\u03c4\u03af \u03bd\u03b1 \u03bc\u03b5\u03c4\u03b1\u03c4\u03c1\u03ad\u03c8\u03b5\u03c4\u03b5 ${s} \u03c3\u03b5 ${t};`,
    how: (s, t) => `\u03a0\u03ce\u03c2 \u03bd\u03b1 \u03bc\u03b5\u03c4\u03b1\u03c4\u03c1\u03ad\u03c8\u03b5\u03c4\u03b5 ${s} \u03c3\u03b5 ${t}`,
    comparison: (s, t) => `${s} \u03ad\u03bd\u03b1\u03bd\u03c4\u03b9 ${t} \u2013 \u03b2\u03b1\u03c3\u03b9\u03ba\u03ad\u03c2 \u03b4\u03b9\u03b1\u03c6\u03bf\u03c1\u03ad\u03c2`,
    when: (s, t) => `\u03a0\u03cc\u03c4\u03b5 \u03c0\u03c1\u03ad\u03c0\u03b5\u03b9 \u03bd\u03b1 \u03bc\u03b5\u03c4\u03b1\u03c4\u03c1\u03ad\u03c8\u03b5\u03c4\u03b5 ${s} \u03c3\u03b5 ${t};`,
    features: (s, t) =>
      `\u03a4\u03b9 \u03be\u03b5\u03c7\u03c9\u03c1\u03af\u03b6\u03b5\u03b9 \u03b1\u03c5\u03c4\u03cc\u03bd \u03c4\u03bf\u03bd \u03bc\u03b5\u03c4\u03b1\u03c4\u03c1\u03bf\u03c0\u03ad\u03b1 ${s} \u03c3\u03b5 ${t};`,
    regional: (s, t) => `\u039c\u03b5\u03c4\u03b1\u03c4\u03c1\u03bf\u03c0\u03ae ${s} \u03c3\u03b5 ${t} \u03c3\u03c4\u03b7\u03bd \u03c0\u03c1\u03ac\u03be\u03b7`,
    tips: (s, t) => `\u03a3\u03c5\u03bc\u03b2\u03bf\u03c5\u03bb\u03ad\u03c2 \u03b3\u03b9\u03b1 \u03c4\u03b7 \u03bc\u03b5\u03c4\u03b1\u03c4\u03c1\u03bf\u03c0\u03ae ${s} \u03c3\u03b5 ${t}`,
    faq: (s, t) =>
      `\u03a3\u03c5\u03c7\u03bd\u03ad\u03c2 \u03b5\u03c1\u03c9\u03c4\u03ae\u03c3\u03b5\u03b9\u03c2 \u03b3\u03b9\u03b1 \u03c4\u03b7 \u03bc\u03b5\u03c4\u03b1\u03c4\u03c1\u03bf\u03c0\u03ae ${s} \u03c3\u03b5 ${t}`,
    contact:
      '\u0392\u03bf\u03b7\u03b8\u03ae\u03c3\u03c4\u03b5 \u03bc\u03b1\u03c2 \u03bd\u03b1 \u03b2\u03b5\u03bb\u03c4\u03b9\u03ce\u03c3\u03bf\u03c5\u03bc\u03b5 \u03c4\u03b1 \u03b5\u03c1\u03b3\u03b1\u03bb\u03b5\u03af\u03b1 \u03bc\u03b1\u03c2',
    contactDesc:
      '\u0388\u03c7\u03b5\u03c4\u03b5 \u03bc\u03b9\u03b1 \u03b9\u03b4\u03ad\u03b1, \u03b2\u03c1\u03ae\u03ba\u03b1\u03c4\u03b5 \u03c3\u03c6\u03ac\u03bb\u03bc\u03b1 \u03ae \u03b8\u03ad\u03bb\u03b5\u03c4\u03b5 \u03bd\u03b1 \u03c0\u03c1\u03bf\u03c4\u03b5\u03af\u03bd\u03b5\u03c4\u03b5 \u03bb\u03b5\u03b9\u03c4\u03bf\u03c5\u03c1\u03b3\u03af\u03b1; \u0393\u03c1\u03ac\u03c8\u03c4\u03b5 \u03bc\u03b1\u03c2 \u2013 \u03b1\u03c0\u03b1\u03bd\u03c4\u03ac\u03bc\u03b5 \u03b5\u03bd\u03c4\u03cc\u03c2 24 \u03c9\u03c1\u03ce\u03bd.',
    carousel:
      '\u0391\u03bd\u03b1\u03ba\u03b1\u03bb\u03cd\u03c8\u03c4\u03b5 \u03c0\u03b5\u03c1\u03b9\u03c3\u03c3\u03cc\u03c4\u03b5\u03c1\u03b1 \u03b4\u03c9\u03c1\u03b5\u03ac\u03bd \u03b5\u03c1\u03b3\u03b1\u03bb\u03b5\u03af\u03b1',
  },
  fi: {
    why: (s, t) => `Miksi muuntaa ${s} ${t}-muotoon?`,
    how: (s, t) => `Kuinka muuntaa ${s} ${t}-muotoon`,
    comparison: (s, t) => `${s} vs ${t} \u2013 keskeiset erot`,
    when: (s, t) => `Milloin kannattaa muuntaa ${s} ${t}-muotoon?`,
    features: (s, t) => `Mik\u00e4 erottaa t\u00e4m\u00e4n ${s}-${t}-muuntimen?`,
    regional: (s, t) => `${s}-${t}-muunnos k\u00e4yt\u00e4nn\u00f6ss\u00e4`,
    tips: (s, t) => `Vinkkej\u00e4 ${s}-${t}-muunnokseen`,
    faq: (s, t) => `Usein kysytyt kysymykset ${s}-${t}-muunnoksesta`,
    contact: 'Auta meit\u00e4 parantamaan ty\u00f6kalujamme',
    contactDesc: 'Onko sinulla idea, l\u00f6ysitkö virheen tai haluatko ehdottaa ominaisuutta? Kirjoita meille \u2013 vastaamme 24 tunnin kuluessa.',
    carousel: 'Tutustu muihin ilmaisiin ty\u00f6kaluihin',
  },
  hu: {
    why: (s, t) => `Mi\u00e9rt \u00e9rdemes ${s}-t ${t}-re konvert\u00e1lni?`,
    how: (s, t) => `Hogyan konvert\u00e1lja ${s}-t ${t}-re`,
    comparison: (s, t) => `${s} vs ${t} \u2013 a legfontosabb k\u00fcl\u00f6nbs\u00e9gek`,
    when: (s, t) => `Mikor \u00e9rdemes ${s}-t ${t}-re konvert\u00e1lni?`,
    features: (s, t) => `Mi teszi k\u00fcl\u00f6nlegess\u00e9 ezt a ${s}-${t} konvertert?`,
    regional: (s, t) => `${s}-${t} konvert\u00e1l\u00e1s a gyakorlatban`,
    tips: (s, t) => `Tippek a ${s}-${t} konvert\u00e1l\u00e1shoz`,
    faq: (s, t) => `Gyakran ism\u00e9telt k\u00e9rd\u00e9sek a ${s}-${t} konvert\u00e1l\u00e1sr\u00f3l`,
    contact: 'Seg\u00edtsen nek\u00fcnk fejleszteni eszk\u00f6zeinket',
    contactDesc: 'Van \u00f6tlete, hib\u00e1t tal\u00e1lt vagy funkci\u00f3t szeretne javasolni? \u00cdrjon nek\u00fcnk \u2013 24 \u00f3r\u00e1n bel\u00fcl v\u00e1laszolunk.',
    carousel: 'Fedezzen fel tov\u00e1bbi ingyenes eszk\u00f6z\u00f6ket',
  },
  nl: {
    why: (s, t) => `Waarom ${s} naar ${t} converteren?`,
    how: (s, t) => `Hoe ${s} naar ${t} converteren`,
    comparison: (s, t) => `${s} vs ${t} \u2013 de belangrijkste verschillen`,
    when: (s, t) => `Wanneer ${s} naar ${t} converteren?`,
    features: (s, t) => `Wat maakt deze ${s}-naar-${t}-converter anders?`,
    regional: (s, t) => `${s}-naar-${t}-conversie in de praktijk`,
    tips: (s, t) => `Tips voor het converteren van ${s} naar ${t}`,
    faq: (s, t) => `Veelgestelde vragen over ${s}-naar-${t}-conversie`,
    contact: 'Help ons onze tools te verbeteren',
    contactDesc: 'Heeft u een idee, een bug gevonden of wilt u een functie voorstellen? Schrijf ons \u2013 we reageren binnen 24 uur.',
    carousel: 'Ontdek meer gratis tools',
  },
  no: {
    why: (s, t) => `Hvorfor konvertere ${s} til ${t}?`,
    how: (s, t) => `Slik konverterer du ${s} til ${t}`,
    comparison: (s, t) => `${s} vs ${t} \u2013 de viktigste forskjellene`,
    when: (s, t) => `N\u00e5r b\u00f8r du konvertere ${s} til ${t}?`,
    features: (s, t) => `Hva gj\u00f8r denne ${s}-til-${t}-konverteren annerledes?`,
    regional: (s, t) => `${s}-til-${t}-konvertering i praksis`,
    tips: (s, t) => `Tips for konvertering av ${s} til ${t}`,
    faq: (s, t) => `Vanlige sp\u00f8rsm\u00e5l om konvertering av ${s} til ${t}`,
    contact: 'Hjelp oss med \u00e5 forbedre v\u00e5re verkt\u00f8y',
    contactDesc: 'Har du en id\u00e9, funnet en feil eller vil foresl\u00e5 en funksjon? Skriv til oss \u2013 vi svarer innen 24 timer.',
    carousel: 'Utforsk flere gratis verkt\u00f8y',
  },
  ro: {
    why: (s, t) => `De ce s\u0103 converti\u021bi ${s} \u00een ${t}?`,
    how: (s, t) => `Cum s\u0103 converti\u021bi ${s} \u00een ${t}`,
    comparison: (s, t) => `${s} vs ${t} \u2013 diferen\u021bele cheie`,
    when: (s, t) => `C\u00e2nd s\u0103 converti\u021bi ${s} \u00een ${t}?`,
    features: (s, t) => `Ce face acest convertor ${s} \u00een ${t} diferit?`,
    regional: (s, t) => `Conversia ${s} \u00een ${t} \u00een practic\u0103`,
    tips: (s, t) => `Sfaturi pentru conversia ${s} \u00een ${t}`,
    faq: (s, t) => `\u00centreb\u0103ri frecvente despre conversia ${s} \u00een ${t}`,
    contact: 'Ajuta\u021bi-ne s\u0103 \u00eembun\u0103t\u0103\u021bim instrumentele noastre',
    contactDesc: 'Ave\u021bi o idee, a\u021bi g\u0103sit un bug sau dori\u021bi s\u0103 sugera\u021bi o func\u021bie? Scrie\u021bi-ne \u2013 r\u0103spundem \u00een 24 de ore.',
    carousel: 'Descoperi\u021bi mai multe instrumente gratuite',
  },
  sv: {
    why: (s, t) => `Varf\u00f6r konvertera ${s} till ${t}?`,
    how: (s, t) => `S\u00e5 konverterar du ${s} till ${t}`,
    comparison: (s, t) => `${s} vs ${t} \u2013 de viktigaste skillnaderna`,
    when: (s, t) => `N\u00e4r ska du konvertera ${s} till ${t}?`,
    features: (s, t) => `Vad g\u00f6r denna ${s}-till-${t}-konverterare annorlunda?`,
    regional: (s, t) => `${s}-till-${t}-konvertering i praktiken`,
    tips: (s, t) => `Tips f\u00f6r konvertering av ${s} till ${t}`,
    faq: (s, t) => `Vanliga fr\u00e5gor om konvertering av ${s} till ${t}`,
    contact: 'Hj\u00e4lp oss f\u00f6rb\u00e4ttra v\u00e5ra verktyg',
    contactDesc: 'Har du en id\u00e9, hittat en bugg eller vill f\u00f6resl\u00e5 en funktion? Skriv till oss \u2013 vi svarar inom 24 timmar.',
    carousel: 'Utforska fler gratis verktyg',
  },
};

// Regional platform/context data per locale
const REGIONAL = {
  en: {
    platforms: ['Amazon', 'eBay', 'Etsy', 'Shopify'],
    gov: 'government portals worldwide',
    ecom: 'global e-commerce',
    cms: 'WordPress, Wix, Squarespace',
    printShops: 'print services',
    emailClients: 'Gmail, Outlook, Apple Mail',
    focus: 'Businesses, developers, and creators worldwide rely on image format compatibility.',
  },
  pl: {
    platforms: ['Allegro', 'OLX', 'Empik', 'Ceneo'],
    gov: 'gov.pl i ePUAP',
    ecom: 'polski e-commerce',
    cms: 'WordPress, Shoper, Sky-Shop',
    printShops: 'drukarnie',
    emailClients: 'Gmail, Outlook, Poczta WP',
    focus: 'Polskie platformy sprzeda\u017cowe i serwisy og\u0142oszeniowe cz\u0119sto wymagaj\u0105 konkretnych format\u00f3w graficznych.',
  },
  de: {
    platforms: ['Otto.de', 'Idealo', 'Amazon.de', 'eBay Kleinanzeigen'],
    gov: 'Beh\u00f6rdenportale (Elster, BundID)',
    ecom: 'deutschen E-Commerce',
    cms: 'WordPress, Shopify, TYPO3',
    printShops: 'Druckereien',
    emailClients: 'Gmail, Outlook, GMX, Web.de',
    focus: 'Im DACH-Raum gelten strenge Datenschutzanforderungen \u2013 lokale Bildverarbeitung sch\u00fctzt sensible Daten.',
  },
  fr: {
    platforms: ['Leboncoin', 'Cdiscount', 'Amazon.fr', 'Vinted'],
    gov: 'service-public.fr et FranceConnect',
    ecom: 'e-commerce fran\u00e7ais',
    cms: 'WordPress, PrestaShop, Shopify',
    printShops: 'imprimeries',
    emailClients: 'Gmail, Outlook, La Poste',
    focus: 'En France, au Canada et en Belgique, la conformit\u00e9 RGPD rend la conversion locale particuli\u00e8rement pertinente.',
  },
  es: {
    platforms: ['Amazon.es', 'Wallapop', 'MercadoLibre', 'Milanuncios'],
    gov: 'Sede Electr\u00f3nica y portales auton\u00f3micos',
    ecom: 'e-commerce hispanohablante',
    cms: 'WordPress, Shopify, PrestaShop',
    printShops: 'imprentas',
    emailClients: 'Gmail, Outlook, Yahoo',
    focus: 'En Espa\u00f1a y Latinoam\u00e9rica, muchas plataformas de venta requieren im\u00e1genes en formatos espec\u00edficos.',
  },
  it: {
    platforms: ['Subito.it', 'Amazon.it', 'eBay.it', 'Vinted'],
    gov: 'SPID e portali della PA',
    ecom: 'e-commerce italiano',
    cms: 'WordPress, Shopify, WooCommerce',
    printShops: 'tipografie',
    emailClients: 'Gmail, Outlook, Libero Mail',
    focus: 'In Italia, la conversione locale garantisce il rispetto delle normative sulla privacy (GDPR/Garante).',
  },
  pt: {
    platforms: ['OLX.pt', 'KuantoKusta', 'Amazon', 'Mercado Livre'],
    gov: 'ePortugal e Gov.br',
    ecom: 'e-commerce em portugu\u00eas',
    cms: 'WordPress, Shopify, Nuvemshop',
    printShops: 'gr\u00e1ficas',
    emailClients: 'Gmail, Outlook, UOL Mail',
    focus: 'Em Portugal e no Brasil, plataformas de com\u00e9rcio e servi\u00e7os p\u00fablicos frequentemente exigem formatos de imagem espec\u00edficos.',
  },
  cs: {
    platforms: ['Heureka.cz', 'Alza.cz', 'Baz\u00e1r', 'Mall.cz'],
    gov: 'Datov\u00e9 schr\u00e1nky a Port\u00e1l ob\u010dana',
    ecom: '\u010desk\u00fd e-commerce',
    cms: 'WordPress, Shoptet, Shopify',
    printShops: 'tisk\u00e1rny',
    emailClients: 'Gmail, Outlook, Seznam',
    focus: '\u010cesk\u00e9 e-shopy a inzertn\u00ed port\u00e1ly \u010dasto vy\u017eaduj\u00ed konkr\u00e9tn\u00ed form\u00e1ty obr\u00e1zk\u016f.',
  },
  da: {
    platforms: ['DBA.dk', 'Bilka.dk', 'Nemlig.com', 'COOP'],
    gov: 'borger.dk og NemID/MitID',
    ecom: 'dansk e-handel',
    cms: 'WordPress, Shopify, DanDomain',
    printShops: 'trykkerier',
    emailClients: 'Gmail, Outlook, Jubii',
    focus: 'I Danmark og Norden er databeskyttelse afg\u00f8rende \u2013 lokal billedbehandling beskytter f\u00f8lsomme data.',
  },
  el: {
    platforms: ['Skroutz.gr', 'Public.gr', 'Marketplace'],
    gov: 'gov.gr \u03ba\u03b1\u03b9 Taxisnet',
    ecom: '\u03b5\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03cc e-commerce',
    cms: 'WordPress, Shopify, WooCommerce',
    printShops: '\u03c4\u03c5\u03c0\u03bf\u03b3\u03c1\u03b1\u03c6\u03b5\u03af\u03b1',
    emailClients: 'Gmail, Outlook, Forthnet',
    focus:
      '\u03a3\u03c4\u03b7\u03bd \u0395\u03bb\u03bb\u03ac\u03b4\u03b1 \u03ba\u03b1\u03b9 \u03c4\u03b7\u03bd \u039a\u03cd\u03c0\u03c1\u03bf, \u03c0\u03bf\u03bb\u03bb\u03ad\u03c2 \u03c0\u03bb\u03b1\u03c4\u03c6\u03cc\u03c1\u03bc\u03b5\u03c2 \u03b1\u03c0\u03b1\u03b9\u03c4\u03bf\u03cd\u03bd \u03c3\u03c5\u03b3\u03ba\u03b5\u03ba\u03c1\u03b9\u03bc\u03ad\u03bd\u03b5\u03c2 \u03bc\u03bf\u03c1\u03c6\u03ad\u03c2 \u03b5\u03b9\u03ba\u03cc\u03bd\u03b1\u03c2.',
  },
  fi: {
    platforms: ['Tori.fi', 'Verkkokauppa.com', 'Gigantti', 'Amazon'],
    gov: 'suomi.fi ja Omakanta',
    ecom: 'suomalainen verkkokauppa',
    cms: 'WordPress, Shopify, MyCashflow',
    printShops: 'painotalot',
    emailClients: 'Gmail, Outlook, Elisa S\u00e4hk\u00f6posti',
    focus: 'Suomessa ja Pohjoismaissa tietosuoja on ensisijaista \u2013 paikallinen kuvanmuunnos suojaa arkaluonteisia tietoja.',
  },
  hu: {
    platforms: ['J\u00f3fog\u00e1s.hu', 'Extreme Digital', 'eMAG.hu', 'Marketplace'],
    gov: '\u00dcgyf\u00e9lkapu \u00e9s Korm\u00e1nyablak',
    ecom: 'magyar e-kereskedelem',
    cms: 'WordPress, Shopify, Shoprenter',
    printShops: 'nyomd\u00e1k',
    emailClients: 'Gmail, Outlook, Citromail',
    focus: 'Magyarorsz\u00e1gon az online piacterek \u00e9s korm\u00e1nyzati port\u00e1lok gyakran specifikus k\u00e9pform\u00e1tumot k\u00f6vetelnek.',
  },
  nl: {
    platforms: ['Bol.com', 'Marktplaats', 'Amazon.nl', 'Coolblue'],
    gov: 'Rijksoverheid.nl en DigiD',
    ecom: 'Nederlandse e-commerce',
    cms: 'WordPress, Shopify, Lightspeed',
    printShops: 'drukkerijen',
    emailClients: 'Gmail, Outlook, Ziggo Mail',
    focus: 'In Nederland en Belgi\u00eb hechten consumenten veel waarde aan privacy \u2013 lokale beeldconversie beschermt gevoelige gegevens.',
  },
  no: {
    platforms: ['Finn.no', 'Komplett.no', 'Elkj\u00f8p', 'CDON'],
    gov: 'Altinn og ID-porten',
    ecom: 'norsk e-handel',
    cms: 'WordPress, Shopify, Mystore',
    printShops: 'trykkerier',
    emailClients: 'Gmail, Outlook, Telenor',
    focus: 'I Norge og Norden er personvern avgj\u00f8rende \u2013 lokal bildebehandling beskytter sensitive data.',
  },
  ro: {
    platforms: ['OLX.ro', 'eMAG.ro', 'Amazon', 'Marketplace'],
    gov: 'ghiseul.ro \u0219i SPV',
    ecom: 'e-commerce rom\u00e2nesc',
    cms: 'WordPress, Shopify, GomAG',
    printShops: 'tipografii',
    emailClients: 'Gmail, Outlook, Yahoo',
    focus: '\u00cen Rom\u00e2nia, platformele de comer\u021b \u0219i serviciile publice solicit\u0103 frecvent formate de imagine specifice.',
  },
  sv: {
    platforms: ['Blocket.se', 'Tradera', 'CDON', 'Amazon.se'],
    gov: 'Skatteverket och BankID',
    ecom: 'svensk e-handel',
    cms: 'WordPress, Shopify, Quickbutik',
    printShops: 'tryckerier',
    emailClients: 'Gmail, Outlook, Telia',
    focus: 'I Sverige och Norden \u00e4r integritet avg\u00f6rande \u2013 lokal bildkonvertering skyddar k\u00e4nsliga data.',
  },
};

module.exports = { FORMATS, TITLES, REGIONAL };
