// ---------------------------------------------------------------------------
// Lorem Ipsum generator – pure functions, no React dependency
// ---------------------------------------------------------------------------

export type LoremMode =
  | 'paragraphs'
  | 'sentences'
  | 'words'
  | 'lists'
  | 'headings'
  | 'links'
  | 'table'
  | 'blockquotes'
  | 'definitions';
export type LoremLength = 'short' | 'medium' | 'long';
export type LoremStyle =
  | 'classic'
  | 'hipster'
  | 'business'
  | 'polish'
  | 'bacon'
  | 'cupcake'
  | 'pirate'
  | 'legal';
export type LoremFormat = 'plain' | 'html';

export interface LoremOptions {
  mode: LoremMode;
  count: number;
  paragraphLength: LoremLength;
  startWithLorem: boolean;
  outputFormat: LoremFormat;
  style: LoremStyle;
  locale?: string;
}

// ---------------------------------------------------------------------------
// Word banks
// ---------------------------------------------------------------------------

const LOREM_CLASSIC = [
  'lorem',
  'ipsum',
  'dolor',
  'sit',
  'amet',
  'consectetur',
  'adipiscing',
  'elit',
  'sed',
  'do',
  'eiusmod',
  'tempor',
  'incididunt',
  'ut',
  'labore',
  'et',
  'dolore',
  'magna',
  'aliqua',
  'enim',
  'ad',
  'minim',
  'veniam',
  'quis',
  'nostrud',
  'exercitation',
  'ullamco',
  'laboris',
  'nisi',
  'aliquip',
  'ex',
  'ea',
  'commodo',
  'consequat',
  'duis',
  'aute',
  'irure',
  'in',
  'reprehenderit',
  'voluptate',
  'velit',
  'esse',
  'cillum',
  'fugiat',
  'nulla',
  'pariatur',
  'excepteur',
  'sint',
  'occaecat',
  'cupidatat',
  'non',
  'proident',
  'sunt',
  'culpa',
  'qui',
  'officia',
  'deserunt',
  'mollit',
  'anim',
  'id',
  'est',
  'laborum',
  'at',
  'vero',
  'eos',
  'accusamus',
  'iusto',
  'odio',
  'dignissimos',
  'ducimus',
  'blanditiis',
  'praesentium',
  'voluptatum',
  'deleniti',
  'atque',
  'corrupti',
  'quos',
  'dolores',
  'quas',
  'molestias',
  'excepturi',
  'obcaecati',
  'cupiditate',
  'provident',
  'similique',
  'architecto',
  'beatae',
  'vitae',
  'dicta',
  'explicabo',
  'nemo',
  'ipsam',
  'voluptatem',
  'quia',
  'voluptas',
  'aspernatur',
  'fugit',
  'consequuntur',
  'magni',
  'nesciunt',
  'neque',
  'porro',
  'quisquam',
  'nihil',
  'impedit',
  'quo',
  'minus',
  'maxime',
  'placeat',
  'facere',
  'possimus',
  'omnis',
  'assumenda',
  'repellendus',
  'temporibus',
  'autem',
  'quibusdam',
  'officiis',
  'debitis',
  'aut',
  'rerum',
  'necessitatibus',
  'saepe',
  'eveniet',
  'voluptates',
  'repudiandae',
  'recusandae',
  'itaque',
  'earum',
  'hic',
  'tenetur',
  'sapiente',
  'delectus',
  'reiciendis',
  'voluptatibus',
  'maiores',
  'alias',
  'perferendis',
  'doloribus',
  'asperiores',
  'repellat',
  'nam',
  'libero',
  'cum',
  'soluta',
  'nobis',
  'eligendi',
  'optio',
  'cumque',
  'inventore',
  'veritatis',
  'quasi',
  'rem',
  'aperiam',
  'eaque',
  'ipsa',
  'ab',
  'illo',
  'totam',
  'ullam',
  'corporis',
  'suscipit',
  'laboriosam',
];

const LOREM_HIPSTER = [
  'artisan',
  'craft',
  'vinyl',
  'organic',
  'sustainable',
  'avocado',
  'toast',
  'kombucha',
  'matcha',
  'latte',
  'pour-over',
  'cold-brew',
  'espresso',
  'aesthetic',
  'vintage',
  'retro',
  'minimalist',
  'curated',
  'handcrafted',
  'bespoke',
  'locally-sourced',
  'farm-to-table',
  'plant-based',
  'vegan',
  'gluten-free',
  'kale',
  'quinoa',
  'acai',
  'smoothie',
  'granola',
  'sourdough',
  'fermented',
  'probiotic',
  'wellness',
  'mindfulness',
  'meditation',
  'yoga',
  'pilates',
  'breathwork',
  'journaling',
  'typewriter',
  'polaroid',
  'film',
  'analog',
  'cassette',
  'turntable',
  'flea-market',
  'thrift',
  'upcycled',
  'reclaimed',
  'distressed',
  'raw',
  'unfiltered',
  'small-batch',
  'micro',
  'indie',
  'underground',
  'loft',
  'studio',
  'co-working',
  'creative',
  'concept',
  'gallery',
  'mural',
  'zine',
  'podcast',
  'playlist',
  'lo-fi',
  'ambient',
  'brunch',
  'flat-white',
  'oat-milk',
  'cortado',
  'chai',
  'turmeric',
  'chia',
  'hemp',
  'coconut',
  'almond',
  'cashew',
  'tahini',
  'sriracha',
  'kimchi',
  'miso',
  'ramen',
  'poke',
  'tempeh',
  'terrazzo',
  'monstera',
  'macrame',
  'ceramic',
  'linen',
  'rattan',
  'eucalyptus',
  'sage',
  'pastel',
  'neutral',
  'earthy',
  'muted',
  'slow-living',
  'hygge',
  'lagom',
  'wabi-sabi',
  'ikigai',
  'cozy',
  'intentional',
  'authentic',
  'transparent',
  'ethical',
  'conscious',
  'sustainable',
  'zero-waste',
  'biodegradable',
  'compostable',
  'reusable',
];

const LOREM_BUSINESS = [
  'synergy',
  'leverage',
  'stakeholder',
  'paradigm',
  'scalable',
  'agile',
  'innovative',
  'disruptive',
  'ecosystem',
  'pipeline',
  'bandwidth',
  'deliverable',
  'milestone',
  'roadmap',
  'benchmark',
  'metric',
  'KPI',
  'ROI',
  'bottom-line',
  'top-line',
  'revenue',
  'margin',
  'growth',
  'strategy',
  'alignment',
  'optimization',
  'transformation',
  'integration',
  'automation',
  'digitalization',
  'streamline',
  'efficiency',
  'productivity',
  'value-add',
  'core-competency',
  'best-practice',
  'thought-leader',
  'game-changer',
  'low-hanging-fruit',
  'deep-dive',
  'drill-down',
  'action-item',
  'takeaway',
  'next-steps',
  'follow-up',
  'touch-base',
  'circle-back',
  'ping',
  'loop-in',
  'escalate',
  'fast-track',
  'proactive',
  'holistic',
  'cross-functional',
  'data-driven',
  'results-oriented',
  'customer-centric',
  'mission-critical',
  'enterprise-grade',
  'end-to-end',
  'turnkey',
  'plug-and-play',
  'out-of-the-box',
  'cutting-edge',
  'bleeding-edge',
  'state-of-the-art',
  'next-generation',
  'future-proof',
  'world-class',
  'market-leading',
  'industry-standard',
  'robust',
  'seamless',
  'frictionless',
  'dynamic',
  'adaptive',
  'resilient',
  'sustainable',
  'inclusive',
  'transparent',
  'accountable',
  'empowered',
  'engaged',
  'motivated',
  'onboarding',
  'offboarding',
  'upskilling',
  'reskilling',
  'mentorship',
  'collaboration',
  'brainstorm',
  'workshop',
  'sprint',
  'retrospective',
  'standup',
  'demo',
  'release',
  'launch',
  'rollout',
  'deployment',
  'funnel',
  'conversion',
  'retention',
  'churn',
  'lifetime-value',
  'acquisition',
  'engagement',
  'impression',
  'reach',
  'visibility',
];

const LOREM_POLISH = [
  'projekt',
  'strona',
  'klient',
  'firma',
  'zespol',
  'produkt',
  'usluga',
  'rynek',
  'strategia',
  'rozwoj',
  'innowacja',
  'jakosc',
  'efektywnosc',
  'komunikacja',
  'marka',
  'doswiadczenie',
  'technologia',
  'rozwiazanie',
  'analiza',
  'optymalizacja',
  'proces',
  'wartosc',
  'cel',
  'wizja',
  'realizacja',
  'partnerstwo',
  'wspolpraca',
  'budowanie',
  'planowanie',
  'zarzadzanie',
  'wdrozenie',
  'integracja',
  'automatyzacja',
  'cyfryzacja',
  'modernizacja',
  'transformacja',
  'skalowanie',
  'adaptacja',
  'personalizacja',
  'kreacja',
  'inspiracja',
  'motywacja',
  'organizacja',
  'struktura',
  'platforma',
  'narzedzie',
  'system',
  'interfejs',
  'aplikacja',
  'baza',
  'serwer',
  'chmura',
  'bezpieczenstwo',
  'wydajnosc',
  'uzytkownik',
  'odbiorca',
  'konsument',
  'dostawca',
  'partner',
  'mentor',
  'ekspert',
  'specjalista',
  'koordynator',
  'lider',
  'decyzja',
  'wynik',
  'raport',
  'dane',
  'statystyka',
  'budzet',
  'inwestycja',
  'zysk',
  'przychod',
  'koszt',
  'spotkanie',
  'prezentacja',
  'negocjacja',
  'umowa',
  'kontrakt',
  'harmonogram',
  'termin',
  'priorytet',
  'kamien',
  'etap',
  'grafika',
  'typografia',
  'kolor',
  'kompozycja',
  'uklad',
  'tresc',
  'naglowek',
  'akapit',
  'sekcja',
  'stopka',
  'responsywnosc',
  'dostepnosc',
  'uzytecznosc',
  'nawigacja',
  'interakcja',
  'wyszukiwarka',
  'pozycjonowanie',
  'konwersja',
  'ruch',
  'zasieg',
  'kampania',
  'reklama',
  'promocja',
  'newsletter',
  'formularz',
  'zdjecie',
  'wideo',
  'animacja',
  'ikona',
  'ilustracja',
];

const LOREM_BACON = [
  'bacon',
  'ipsum',
  'steak',
  'ribeye',
  'sirloin',
  'filet',
  'mignon',
  'brisket',
  'chuck',
  'flank',
  'tenderloin',
  'strip',
  'porterhouse',
  'tri-tip',
  'rump',
  'hamburger',
  'cheeseburger',
  'patty',
  'ground',
  'beef',
  'pork',
  'chicken',
  'turkey',
  'lamb',
  'veal',
  'venison',
  'bison',
  'elk',
  'sausage',
  'bratwurst',
  'kielbasa',
  'chorizo',
  'salami',
  'pepperoni',
  'prosciutto',
  'pancetta',
  'capicola',
  'bresaola',
  'pastrami',
  'corned',
  'jerky',
  'smoked',
  'cured',
  'grilled',
  'roasted',
  'seared',
  'braised',
  'barbecue',
  'charcoal',
  'hickory',
  'mesquite',
  'applewood',
  'marinade',
  'rub',
  'glaze',
  'baste',
  'grill',
  'smoker',
  'rotisserie',
  'skillet',
  'cast-iron',
  'thermometer',
  'tongs',
  'medium-rare',
  'well-done',
  'char',
  'crust',
  'juicy',
  'tender',
  'savory',
  'umami',
  'seasoned',
  'marbled',
  'lean',
  'fatty',
  'crispy',
  'caramelized',
  'ribs',
  'spare-ribs',
  'baby-back',
  'short-ribs',
  'drumstick',
  'thigh',
  'wing',
  'breast',
  'cutlet',
  'chop',
  'shank',
  'shoulder',
  'belly',
  'meatball',
  'meatloaf',
  'burger',
  'hotdog',
  'kebab',
  'skewer',
  'pulled',
  'slow-cooked',
  'pit-smoked',
  'fire-roasted',
  'flame-grilled',
  'dry-aged',
];

const LOREM_CUPCAKE = [
  'cupcake',
  'ipsum',
  'muffin',
  'brownie',
  'cookie',
  'macaron',
  'croissant',
  'donut',
  'eclair',
  'pastry',
  'tart',
  'pie',
  'cake',
  'cheesecake',
  'tiramisu',
  'chocolate',
  'vanilla',
  'strawberry',
  'caramel',
  'butterscotch',
  'toffee',
  'fudge',
  'ganache',
  'mousse',
  'pudding',
  'custard',
  'cream',
  'whipped',
  'frosting',
  'icing',
  'glaze',
  'sprinkles',
  'fondant',
  'meringue',
  'soufflé',
  'candy',
  'lollipop',
  'gummy',
  'marshmallow',
  'licorice',
  'taffy',
  'nougat',
  'praline',
  'truffle',
  'bonbon',
  'dragée',
  'marzipan',
  'halvah',
  'jelly',
  'sugar',
  'honey',
  'maple',
  'syrup',
  'cinnamon',
  'nutmeg',
  'ginger',
  'cardamom',
  'clove',
  'anise',
  'mint',
  'lemon',
  'orange',
  'raspberry',
  'blueberry',
  'cherry',
  'peach',
  'apple',
  'pear',
  'coconut',
  'almond',
  'hazelnut',
  'pistachio',
  'walnut',
  'pecan',
  'cashew',
  'peanut',
  'sesame',
  'danish',
  'strudel',
  'biscuit',
  'wafer',
  'shortbread',
  'scone',
  'brioche',
  'sweet-roll',
  'cinnamon-roll',
  'bear-claw',
  'fruitcake',
  'gingerbread',
  'cotton-candy',
  'ice-cream',
  'sorbet',
  'gelato',
  'parfait',
  'sundae',
];

const LOREM_PIRATE = [
  'ahoy',
  'matey',
  'avast',
  'arrr',
  'shiver',
  'timbers',
  'scallywag',
  'buccaneer',
  'corsair',
  'privateer',
  'freebooter',
  'marauder',
  'plunder',
  'pillage',
  'booty',
  'treasure',
  'doubloon',
  'pieces-of-eight',
  'gold',
  'silver',
  'jewels',
  'chest',
  'map',
  'compass',
  'spyglass',
  'cannon',
  'cutlass',
  'saber',
  'musket',
  'pistol',
  'dagger',
  'hook',
  'peg-leg',
  'eyepatch',
  'parrot',
  'monkey',
  'skull',
  'crossbones',
  'jolly-roger',
  'flag',
  'mast',
  'sail',
  'rigging',
  'anchor',
  'helm',
  'rudder',
  'starboard',
  'port',
  'bow',
  'stern',
  'hull',
  'deck',
  'gangplank',
  'plank',
  'crow-nest',
  'galley',
  'brig',
  'quarters',
  'cabin',
  'hold',
  'galleon',
  'frigate',
  'schooner',
  'sloop',
  'brigantine',
  'man-o-war',
  'shipwreck',
  'castaway',
  'island',
  'cove',
  'harbor',
  'reef',
  'lagoon',
  'rum',
  'grog',
  'tankard',
  'feast',
  'shanty',
  'sea-dog',
  'landlubber',
  'swashbuckler',
  'mutiny',
  'marooned',
  'keelhaul',
  'broadside',
  'loot',
  'voyage',
  'horizon',
  'tide',
  'storm',
  'kraken',
  'siren',
  'mermaid',
  'captain',
  'first-mate',
  'quartermaster',
  'bosun',
  'crew',
  'deckhand',
];

const LOREM_LEGAL = [
  'whereas',
  'hereby',
  'thereof',
  'herein',
  'pursuant',
  'notwithstanding',
  'aforementioned',
  'undersigned',
  'stipulation',
  'provision',
  'clause',
  'article',
  'section',
  'subsection',
  'paragraph',
  'amendment',
  'addendum',
  'jurisdiction',
  'arbitration',
  'mediation',
  'litigation',
  'adjudication',
  'deposition',
  'testimony',
  'affidavit',
  'subpoena',
  'injunction',
  'warrant',
  'plaintiff',
  'defendant',
  'counsel',
  'attorney',
  'advocate',
  'solicitor',
  'barrister',
  'judge',
  'magistrate',
  'jury',
  'witness',
  'appellant',
  'indemnify',
  'liability',
  'negligence',
  'breach',
  'damages',
  'remedy',
  'compensation',
  'restitution',
  'settlement',
  'verdict',
  'ruling',
  'decree',
  'statute',
  'regulation',
  'ordinance',
  'code',
  'precedent',
  'doctrine',
  'contract',
  'agreement',
  'covenant',
  'deed',
  'lease',
  'license',
  'permit',
  'compliance',
  'enforcement',
  'obligation',
  'duty',
  'right',
  'privilege',
  'tort',
  'felony',
  'misdemeanor',
  'infraction',
  'conviction',
  'acquittal',
  'fiduciary',
  'executor',
  'beneficiary',
  'trustee',
  'guardian',
  'proxy',
  'waiver',
  'disclaimer',
  'force-majeure',
  'pro-bono',
  'de-facto',
  'bona-fide',
  'habeas-corpus',
  'prima-facie',
  'due-process',
  'good-faith',
  'precedent',
  'jurisprudence',
  'sovereignty',
  'jurisdiction',
  'tribunal',
  'appellate',
];

// ---------------------------------------------------------------------------
// Locale-specific filler word banks (used when style === 'polish')
// ---------------------------------------------------------------------------

const FILLER_EN = [
  'project',
  'website',
  'client',
  'company',
  'team',
  'product',
  'service',
  'market',
  'strategy',
  'growth',
  'innovation',
  'quality',
  'efficiency',
  'communication',
  'brand',
  'experience',
  'technology',
  'solution',
  'analysis',
  'optimization',
  'process',
  'value',
  'goal',
  'vision',
  'partnership',
  'collaboration',
  'planning',
  'management',
  'integration',
  'automation',
  'transformation',
  'adaptation',
  'personalization',
  'platform',
  'application',
  'database',
  'server',
  'cloud',
  'security',
  'performance',
  'user',
  'customer',
  'supplier',
  'expert',
  'leader',
  'decision',
  'result',
  'report',
  'data',
  'statistics',
  'budget',
  'investment',
  'profit',
  'revenue',
  'cost',
  'meeting',
  'presentation',
  'agreement',
  'contract',
  'schedule',
  'deadline',
  'priority',
  'milestone',
  'design',
  'typography',
  'color',
  'composition',
  'layout',
  'content',
  'heading',
  'paragraph',
  'section',
  'footer',
  'navigation',
  'interaction',
  'search',
  'ranking',
  'conversion',
  'traffic',
  'campaign',
  'newsletter',
  'photograph',
  'video',
  'animation',
  'icon',
  'illustration',
  'framework',
  'developer',
  'designer',
  'feedback',
  'review',
  'launch',
  'workflow',
];

const FILLER_DE = [
  'Projekt',
  'Webseite',
  'Kunde',
  'Unternehmen',
  'Team',
  'Produkt',
  'Dienst',
  'Markt',
  'Strategie',
  'Wachstum',
  'Innovation',
  'Qualität',
  'Effizienz',
  'Kommunikation',
  'Marke',
  'Erfahrung',
  'Technologie',
  'Lösung',
  'Analyse',
  'Optimierung',
  'Prozess',
  'Wert',
  'Ziel',
  'Vision',
  'Partnerschaft',
  'Zusammenarbeit',
  'Planung',
  'Verwaltung',
  'Integration',
  'Automatisierung',
  'Transformation',
  'Anpassung',
  'Personalisierung',
  'Plattform',
  'Anwendung',
  'Datenbank',
  'Server',
  'Cloud',
  'Sicherheit',
  'Leistung',
  'Benutzer',
  'Verbraucher',
  'Lieferant',
  'Experte',
  'Leiter',
  'Entscheidung',
  'Ergebnis',
  'Bericht',
  'Daten',
  'Statistik',
  'Budget',
  'Investition',
  'Gewinn',
  'Umsatz',
  'Kosten',
  'Besprechung',
  'Präsentation',
  'Vereinbarung',
  'Vertrag',
  'Zeitplan',
  'Frist',
  'Priorität',
  'Meilenstein',
  'Gestaltung',
  'Typografie',
  'Farbe',
  'Komposition',
  'Layout',
  'Inhalt',
  'Überschrift',
  'Absatz',
  'Abschnitt',
  'Navigation',
  'Interaktion',
  'Suche',
  'Ranking',
  'Konversion',
  'Verkehr',
  'Kampagne',
  'Newsletter',
  'Fotografie',
  'Video',
  'Animation',
  'Symbol',
  'Illustration',
  'Rahmenwerk',
];

const FILLER_ES = [
  'proyecto',
  'sitio',
  'cliente',
  'empresa',
  'equipo',
  'producto',
  'servicio',
  'mercado',
  'estrategia',
  'crecimiento',
  'innovación',
  'calidad',
  'eficiencia',
  'comunicación',
  'marca',
  'experiencia',
  'tecnología',
  'solución',
  'análisis',
  'optimización',
  'proceso',
  'valor',
  'objetivo',
  'visión',
  'asociación',
  'colaboración',
  'planificación',
  'gestión',
  'integración',
  'automatización',
  'transformación',
  'adaptación',
  'personalización',
  'plataforma',
  'aplicación',
  'servidor',
  'nube',
  'seguridad',
  'rendimiento',
  'usuario',
  'consumidor',
  'proveedor',
  'experto',
  'líder',
  'decisión',
  'resultado',
  'informe',
  'datos',
  'estadística',
  'presupuesto',
  'inversión',
  'beneficio',
  'ingreso',
  'coste',
  'reunión',
  'presentación',
  'acuerdo',
  'contrato',
  'calendario',
  'plazo',
  'prioridad',
  'hito',
  'diseño',
  'tipografía',
  'color',
  'composición',
  'contenido',
  'encabezado',
  'párrafo',
  'sección',
  'navegación',
  'interacción',
  'búsqueda',
  'clasificación',
  'conversión',
  'tráfico',
  'campaña',
  'boletín',
  'fotografía',
  'vídeo',
];

const FILLER_FR = [
  'projet',
  'site',
  'client',
  'entreprise',
  'équipe',
  'produit',
  'service',
  'marché',
  'stratégie',
  'croissance',
  'innovation',
  'qualité',
  'efficacité',
  'communication',
  'marque',
  'expérience',
  'technologie',
  'solution',
  'analyse',
  'optimisation',
  'processus',
  'valeur',
  'objectif',
  'vision',
  'partenariat',
  'collaboration',
  'planification',
  'gestion',
  'intégration',
  'automatisation',
  'transformation',
  'adaptation',
  'personnalisation',
  'plateforme',
  'application',
  'serveur',
  'nuage',
  'sécurité',
  'performance',
  'utilisateur',
  'consommateur',
  'fournisseur',
  'expert',
  'dirigeant',
  'décision',
  'résultat',
  'rapport',
  'données',
  'statistique',
  'budget',
  'investissement',
  'bénéfice',
  'revenu',
  'coût',
  'réunion',
  'présentation',
  'accord',
  'contrat',
  'calendrier',
  'échéance',
  'priorité',
  'jalon',
  'conception',
  'typographie',
  'couleur',
  'composition',
  'contenu',
  'titre',
  'paragraphe',
  'section',
  'navigation',
  'interaction',
  'recherche',
  'classement',
  'conversion',
  'trafic',
  'campagne',
  'bulletin',
  'photographie',
];

const FILLER_PT = [
  'projeto',
  'site',
  'cliente',
  'empresa',
  'equipe',
  'produto',
  'serviço',
  'mercado',
  'estratégia',
  'crescimento',
  'inovação',
  'qualidade',
  'eficiência',
  'comunicação',
  'marca',
  'experiência',
  'tecnologia',
  'solução',
  'análise',
  'otimização',
  'processo',
  'valor',
  'objetivo',
  'visão',
  'parceria',
  'colaboração',
  'planejamento',
  'gestão',
  'integração',
  'automação',
  'transformação',
  'adaptação',
  'personalização',
  'plataforma',
  'aplicação',
  'servidor',
  'nuvem',
  'segurança',
  'desempenho',
  'usuário',
  'consumidor',
  'fornecedor',
  'especialista',
  'líder',
  'decisão',
  'resultado',
  'relatório',
  'dados',
  'estatística',
  'orçamento',
  'investimento',
  'lucro',
  'receita',
  'custo',
  'reunião',
  'apresentação',
  'acordo',
  'contrato',
  'cronograma',
  'prazo',
  'prioridade',
  'marco',
  'design',
  'tipografia',
  'cor',
  'composição',
  'conteúdo',
  'cabeçalho',
  'parágrafo',
  'seção',
  'navegação',
  'interação',
  'busca',
  'classificação',
  'conversão',
];

const FILLER_IT = [
  'progetto',
  'sito',
  'cliente',
  'azienda',
  'squadra',
  'prodotto',
  'servizio',
  'mercato',
  'strategia',
  'crescita',
  'innovazione',
  'qualità',
  'efficienza',
  'comunicazione',
  'marchio',
  'esperienza',
  'tecnologia',
  'soluzione',
  'analisi',
  'ottimizzazione',
  'processo',
  'valore',
  'obiettivo',
  'visione',
  'partnership',
  'collaborazione',
  'pianificazione',
  'gestione',
  'integrazione',
  'automazione',
  'trasformazione',
  'adattamento',
  'personalizzazione',
  'piattaforma',
  'applicazione',
  'server',
  'cloud',
  'sicurezza',
  'prestazione',
  'utente',
  'consumatore',
  'fornitore',
  'esperto',
  'leader',
  'decisione',
  'risultato',
  'rapporto',
  'dati',
  'statistica',
  'bilancio',
  'investimento',
  'profitto',
  'ricavo',
  'costo',
  'riunione',
  'presentazione',
  'accordo',
  'contratto',
  'calendario',
  'scadenza',
  'priorità',
  'traguardo',
  'design',
  'tipografia',
  'colore',
  'composizione',
  'contenuto',
  'intestazione',
  'paragrafo',
  'sezione',
  'navigazione',
  'interazione',
  'ricerca',
  'conversione',
];

const FILLER_RO = [
  'proiect',
  'site',
  'client',
  'companie',
  'echipă',
  'produs',
  'serviciu',
  'piață',
  'strategie',
  'creștere',
  'inovație',
  'calitate',
  'eficiență',
  'comunicare',
  'marcă',
  'experiență',
  'tehnologie',
  'soluție',
  'analiză',
  'optimizare',
  'proces',
  'valoare',
  'obiectiv',
  'viziune',
  'parteneriat',
  'colaborare',
  'planificare',
  'administrare',
  'integrare',
  'automatizare',
  'transformare',
  'adaptare',
  'personalizare',
  'platformă',
  'aplicație',
  'server',
  'cloud',
  'securitate',
  'performanță',
  'utilizator',
  'consumator',
  'furnizor',
  'expert',
  'lider',
  'decizie',
  'rezultat',
  'raport',
  'date',
  'statistică',
  'buget',
  'investiție',
  'profit',
  'venit',
  'cost',
  'întâlnire',
  'prezentare',
  'acord',
  'contract',
  'calendar',
  'termen',
  'prioritate',
  'reper',
  'design',
  'tipografie',
  'culoare',
  'compoziție',
  'conținut',
  'titlu',
  'paragraf',
  'secțiune',
  'navigare',
  'interacțiune',
  'căutare',
  'clasificare',
  'conversie',
];

const FILLER_NL = [
  'project',
  'website',
  'klant',
  'bedrijf',
  'team',
  'product',
  'dienst',
  'markt',
  'strategie',
  'groei',
  'innovatie',
  'kwaliteit',
  'efficiëntie',
  'communicatie',
  'merk',
  'ervaring',
  'technologie',
  'oplossing',
  'analyse',
  'optimalisatie',
  'proces',
  'waarde',
  'doel',
  'visie',
  'partnerschap',
  'samenwerking',
  'planning',
  'beheer',
  'integratie',
  'automatisering',
  'transformatie',
  'aanpassing',
  'personalisatie',
  'platform',
  'applicatie',
  'database',
  'server',
  'cloud',
  'beveiliging',
  'prestatie',
  'gebruiker',
  'consument',
  'leverancier',
  'expert',
  'leider',
  'beslissing',
  'resultaat',
  'rapport',
  'gegevens',
  'statistiek',
  'budget',
  'investering',
  'winst',
  'omzet',
  'kosten',
  'vergadering',
  'presentatie',
  'overeenkomst',
  'contract',
  'planning',
  'deadline',
  'prioriteit',
  'mijlpaal',
  'ontwerp',
  'typografie',
  'kleur',
  'compositie',
  'inhoud',
  'koptekst',
  'alinea',
  'sectie',
  'navigatie',
  'interactie',
  'zoekopdracht',
  'conversie',
];

const FILLER_HU = [
  'projekt',
  'weboldal',
  'ügyfél',
  'vállalat',
  'csapat',
  'termék',
  'szolgáltatás',
  'piac',
  'stratégia',
  'növekedés',
  'innováció',
  'minőség',
  'hatékonyság',
  'kommunikáció',
  'márka',
  'tapasztalat',
  'technológia',
  'megoldás',
  'elemzés',
  'optimalizálás',
  'folyamat',
  'érték',
  'cél',
  'jövőkép',
  'partnerség',
  'együttműködés',
  'tervezés',
  'irányítás',
  'integráció',
  'automatizálás',
  'átalakítás',
  'alkalmazkodás',
  'személyre szabás',
  'platform',
  'alkalmazás',
  'adatbázis',
  'szerver',
  'felhő',
  'biztonság',
  'teljesítmény',
  'felhasználó',
  'fogyasztó',
  'beszállító',
  'szakértő',
  'vezető',
  'döntés',
  'eredmény',
  'jelentés',
  'adat',
  'statisztika',
  'költségvetés',
  'befektetés',
  'nyereség',
  'bevétel',
  'költség',
  'megbeszélés',
  'bemutató',
  'megállapodás',
  'szerződés',
  'ütemterv',
  'határidő',
  'prioritás',
  'mérföldkő',
  'tervezés',
  'tipográfia',
  'szín',
  'összetétel',
  'tartalom',
  'fejléc',
  'bekezdés',
  'rész',
  'navigáció',
  'keresés',
  'rangsorolás',
  'konverzió',
];

const FILLER_CS = [
  'projekt',
  'web',
  'klient',
  'společnost',
  'tým',
  'produkt',
  'služba',
  'trh',
  'strategie',
  'růst',
  'inovace',
  'kvalita',
  'efektivita',
  'komunikace',
  'značka',
  'zkušenost',
  'technologie',
  'řešení',
  'analýza',
  'optimalizace',
  'proces',
  'hodnota',
  'cíl',
  'vize',
  'partnerství',
  'spolupráce',
  'plánování',
  'správa',
  'integrace',
  'automatizace',
  'transformace',
  'přizpůsobení',
  'personalizace',
  'platforma',
  'aplikace',
  'databáze',
  'server',
  'cloud',
  'bezpečnost',
  'výkon',
  'uživatel',
  'spotřebitel',
  'dodavatel',
  'odborník',
  'vedoucí',
  'rozhodnutí',
  'výsledek',
  'zpráva',
  'data',
  'statistika',
  'rozpočet',
  'investice',
  'zisk',
  'příjem',
  'náklad',
  'schůzka',
  'prezentace',
  'dohoda',
  'smlouva',
  'harmonogram',
  'termín',
  'priorita',
  'milník',
  'návrh',
  'typografie',
  'barva',
  'kompozice',
  'obsah',
  'nadpis',
  'odstavec',
  'sekce',
  'navigace',
  'interakce',
  'vyhledávání',
  'konverze',
];

const FILLER_SV = [
  'projekt',
  'webbplats',
  'kund',
  'företag',
  'team',
  'produkt',
  'tjänst',
  'marknad',
  'strategi',
  'tillväxt',
  'innovation',
  'kvalitet',
  'effektivitet',
  'kommunikation',
  'varumärke',
  'upplevelse',
  'teknik',
  'lösning',
  'analys',
  'optimering',
  'process',
  'värde',
  'mål',
  'vision',
  'partnerskap',
  'samarbete',
  'planering',
  'förvaltning',
  'integration',
  'automatisering',
  'omvandling',
  'anpassning',
  'personalisering',
  'plattform',
  'applikation',
  'databas',
  'server',
  'moln',
  'säkerhet',
  'prestanda',
  'användare',
  'konsument',
  'leverantör',
  'expert',
  'ledare',
  'beslut',
  'resultat',
  'rapport',
  'data',
  'statistik',
  'budget',
  'investering',
  'vinst',
  'intäkt',
  'kostnad',
  'möte',
  'presentation',
  'avtal',
  'kontrakt',
  'schema',
  'deadline',
  'prioritet',
  'milstolpe',
  'design',
  'typografi',
  'färg',
  'komposition',
  'innehåll',
  'rubrik',
  'stycke',
  'avsnitt',
  'navigering',
  'interaktion',
  'sökning',
  'konvertering',
];

const FILLER_DA = [
  'projekt',
  'hjemmeside',
  'kunde',
  'virksomhed',
  'hold',
  'produkt',
  'tjeneste',
  'marked',
  'strategi',
  'vækst',
  'innovation',
  'kvalitet',
  'effektivitet',
  'kommunikation',
  'varemærke',
  'oplevelse',
  'teknologi',
  'løsning',
  'analyse',
  'optimering',
  'proces',
  'værdi',
  'mål',
  'vision',
  'partnerskab',
  'samarbejde',
  'planlægning',
  'forvaltning',
  'integration',
  'automatisering',
  'omstilling',
  'tilpasning',
  'personalisering',
  'platform',
  'applikation',
  'database',
  'server',
  'sky',
  'sikkerhed',
  'ydeevne',
  'bruger',
  'forbruger',
  'leverandør',
  'ekspert',
  'leder',
  'beslutning',
  'resultat',
  'rapport',
  'data',
  'statistik',
  'budget',
  'investering',
  'overskud',
  'indtægt',
  'omkostning',
  'møde',
  'præsentation',
  'aftale',
  'kontrakt',
  'tidsplan',
  'frist',
  'prioritet',
  'milepæl',
  'design',
  'typografi',
  'farve',
  'komposition',
  'indhold',
  'overskrift',
  'afsnit',
  'sektion',
  'navigation',
  'interaktion',
  'søgning',
  'konvertering',
];

const FILLER_NO = [
  'prosjekt',
  'nettside',
  'kunde',
  'bedrift',
  'team',
  'produkt',
  'tjeneste',
  'marked',
  'strategi',
  'vekst',
  'innovasjon',
  'kvalitet',
  'effektivitet',
  'kommunikasjon',
  'merkevare',
  'opplevelse',
  'teknologi',
  'løsning',
  'analyse',
  'optimalisering',
  'prosess',
  'verdi',
  'mål',
  'visjon',
  'partnerskap',
  'samarbeid',
  'planlegging',
  'forvaltning',
  'integrasjon',
  'automatisering',
  'omstilling',
  'tilpasning',
  'personalisering',
  'plattform',
  'applikasjon',
  'database',
  'server',
  'sky',
  'sikkerhet',
  'ytelse',
  'bruker',
  'forbruker',
  'leverandør',
  'ekspert',
  'leder',
  'beslutning',
  'resultat',
  'rapport',
  'data',
  'statistikk',
  'budsjett',
  'investering',
  'overskudd',
  'inntekt',
  'kostnad',
  'møte',
  'presentasjon',
  'avtale',
  'kontrakt',
  'tidsplan',
  'frist',
  'prioritet',
  'milepæl',
  'design',
  'typografi',
  'farge',
  'komposisjon',
  'innhold',
  'overskrift',
  'avsnitt',
  'seksjon',
  'navigasjon',
  'interaksjon',
  'søk',
  'konvertering',
];

const FILLER_FI = [
  'projekti',
  'verkkosivu',
  'asiakas',
  'yritys',
  'tiimi',
  'tuote',
  'palvelu',
  'markkina',
  'strategia',
  'kasvu',
  'innovaatio',
  'laatu',
  'tehokkuus',
  'viestintä',
  'brändi',
  'kokemus',
  'teknologia',
  'ratkaisu',
  'analyysi',
  'optimointi',
  'prosessi',
  'arvo',
  'tavoite',
  'visio',
  'kumppanuus',
  'yhteistyö',
  'suunnittelu',
  'hallinta',
  'integraatio',
  'automaatio',
  'muutos',
  'sopeutuminen',
  'personointi',
  'alusta',
  'sovellus',
  'tietokanta',
  'palvelin',
  'pilvi',
  'turvallisuus',
  'suorituskyky',
  'käyttäjä',
  'kuluttaja',
  'toimittaja',
  'asiantuntija',
  'johtaja',
  'päätös',
  'tulos',
  'raportti',
  'data',
  'tilasto',
  'budjetti',
  'sijoitus',
  'voitto',
  'liikevaihto',
  'kustannus',
  'kokous',
  'esitys',
  'sopimus',
  'sopimus',
  'aikataulu',
  'määräaika',
  'prioriteetti',
  'virstanpylväs',
  'muotoilu',
  'typografia',
  'väri',
  'sommittelu',
  'sisältö',
  'otsikko',
  'kappale',
  'osio',
  'navigointi',
  'vuorovaikutus',
  'haku',
  'konversio',
];

const FILLER_EL = [
  'έργο',
  'ιστοσελίδα',
  'πελάτης',
  'εταιρεία',
  'ομάδα',
  'προϊόν',
  'υπηρεσία',
  'αγορά',
  'στρατηγική',
  'ανάπτυξη',
  'καινοτομία',
  'ποιότητα',
  'αποτελεσματικότητα',
  'επικοινωνία',
  'μάρκα',
  'εμπειρία',
  'τεχνολογία',
  'λύση',
  'ανάλυση',
  'βελτιστοποίηση',
  'διαδικασία',
  'αξία',
  'στόχος',
  'όραμα',
  'συνεργασία',
  'σχεδιασμός',
  'διαχείριση',
  'ενσωμάτωση',
  'αυτοματισμός',
  'μετασχηματισμός',
  'προσαρμογή',
  'εξατομίκευση',
  'πλατφόρμα',
  'εφαρμογή',
  'διακομιστής',
  'σύννεφο',
  'ασφάλεια',
  'απόδοση',
  'χρήστης',
  'καταναλωτής',
  'προμηθευτής',
  'ειδικός',
  'ηγέτης',
  'απόφαση',
  'αποτέλεσμα',
  'αναφορά',
  'δεδομένα',
  'στατιστική',
  'προϋπολογισμός',
  'επένδυση',
  'κέρδος',
  'έσοδα',
  'κόστος',
  'συνάντηση',
  'παρουσίαση',
  'συμφωνία',
  'σύμβαση',
  'πρόγραμμα',
  'προθεσμία',
  'προτεραιότητα',
  'ορόσημο',
  'σχέδιο',
  'τυπογραφία',
  'χρώμα',
  'σύνθεση',
  'περιεχόμενο',
  'τίτλος',
  'παράγραφος',
  'ενότητα',
  'πλοήγηση',
  'αλληλεπίδραση',
  'αναζήτηση',
  'μετατροπή',
];

const LOCALE_FILLERS: Record<string, string[]> = {
  pl: LOREM_POLISH,
  en: FILLER_EN,
  de: FILLER_DE,
  es: FILLER_ES,
  fr: FILLER_FR,
  pt: FILLER_PT,
  it: FILLER_IT,
  ro: FILLER_RO,
  nl: FILLER_NL,
  hu: FILLER_HU,
  cs: FILLER_CS,
  sv: FILLER_SV,
  da: FILLER_DA,
  no: FILLER_NO,
  fi: FILLER_FI,
  el: FILLER_EL,
};

const WORD_BANKS: Record<LoremStyle, string[]> = {
  classic: LOREM_CLASSIC,
  hipster: LOREM_HIPSTER,
  business: LOREM_BUSINESS,
  polish: LOREM_POLISH,
  bacon: LOREM_BACON,
  cupcake: LOREM_CUPCAKE,
  pirate: LOREM_PIRATE,
  legal: LOREM_LEGAL,
};

const LOREM_OPENER = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function seededRandom(seed: number): () => number {
  let s = seed;
  return () => {
    s = (s * 16807) % 2147483647;
    return (s - 1) / 2147483646;
  };
}

/**
 * Selects a single element from `arr` using the provided random number generator.
 *
 * @param arr - The array to choose an element from
 * @param rng - A function that returns a pseudo-random number in the range [0, 1)
 * @returns A single element chosen from `arr`
 */
function pick<T>(arr: T[], rng: () => number): T {
  return arr[Math.floor(rng() * arr.length)];
}

/**
 * Capitalizes the first character of a string using locale-aware casing.
 *
 * @param s - The input string to capitalize
 * @returns The input string with its first character converted to uppercase according to locale; returns an empty string unchanged
 */
function capitalize(s: string): string {
  return s.charAt(0).toLocaleUpperCase() + s.slice(1);
}

/**
 * Selects a pseudorandom integer between min and max, inclusive.
 *
 * @param min - Lowest integer in the inclusive range.
 * @param max - Highest integer in the inclusive range.
 * @param rng - Random number generator that produces a float in [0, 1).
 * @returns An integer between `min` and `max`, inclusive.
 */
function randBetween(min: number, max: number, rng: () => number): number {
  return Math.floor(rng() * (max - min + 1)) + min;
}

// ---------------------------------------------------------------------------
// Sentence / paragraph builders
// ---------------------------------------------------------------------------

function buildSentence(
  bank: string[],
  rng: () => number,
  minWords: number,
  maxWords: number,
): string {
  const len = randBetween(minWords, maxWords, rng);
  const words: string[] = [];
  for (let i = 0; i < len; i++) {
    words.push(pick(bank, rng));
  }
  // Add a comma somewhere in the middle for natural flow
  if (len > 6) {
    const commaPos = randBetween(2, len - 3, rng);
    words[commaPos] = words[commaPos] + ',';
  }
  return capitalize(words.join(' ')) + '.';
}

function getLengthRange(length: LoremLength): {
  minSentences: number;
  maxSentences: number;
} {
  switch (length) {
    case 'short':
      return { minSentences: 2, maxSentences: 4 };
    case 'medium':
      return { minSentences: 4, maxSentences: 7 };
    case 'long':
      return { minSentences: 7, maxSentences: 12 };
  }
}

function buildParagraph(
  bank: string[],
  rng: () => number,
  length: LoremLength,
): string {
  const { minSentences, maxSentences } = getLengthRange(length);
  const sentenceCount = randBetween(minSentences, maxSentences, rng);
  const sentences: string[] = [];
  for (let i = 0; i < sentenceCount; i++) {
    sentences.push(buildSentence(bank, rng, 5, 15));
  }
  return sentences.join(' ');
}

// ---------------------------------------------------------------------------
// Public API
/**
 * Generate lorem ipsum content in the requested structure and format.
 *
 * @param options - Configuration controlling mode (`paragraphs`, `sentences`, `words`, `lists`, `headings`, `links`, `table`, `blockquotes`, `definitions`), `count`, `paragraphLength`, `startWithLorem`, `outputFormat` (`plain` or `html`), `style`, and optional `locale`.
 * @param seed - Optional deterministic seed for the internal random generator; when omitted a time-based seed is used.
 * @returns The generated lorem ipsum text formatted according to `options`. If `outputFormat` is `'html'`, the result contains appropriate HTML elements; otherwise it is plain text.

export function generateLoremIpsum(
  options: LoremOptions,
  seed?: number,
): string {
  const rng = seededRandom(seed ?? Date.now());
  const bank =
    options.style === 'polish' &&
    options.locale &&
    LOCALE_FILLERS[options.locale]
      ? LOCALE_FILLERS[options.locale]
      : WORD_BANKS[options.style];
  const { mode, count, paragraphLength, startWithLorem, outputFormat } =
    options;
  const isHtml = outputFormat === 'html';

  const clampedCount = Math.max(1, Math.min(count, 9999));

  let result = '';

  switch (mode) {
    case 'paragraphs': {
      const paragraphs: string[] = [];
      for (let i = 0; i < clampedCount; i++) {
        let p = buildParagraph(bank, rng, paragraphLength);
        if (i === 0 && startWithLorem && options.style === 'classic') {
          p = LOREM_OPENER + ' ' + p;
        }
        paragraphs.push(isHtml ? `<p>${p}</p>` : p);
      }
      result = isHtml ? paragraphs.join('\n') : paragraphs.join('\n\n');
      break;
    }

    case 'sentences': {
      const sentences: string[] = [];
      for (let i = 0; i < clampedCount; i++) {
        sentences.push(buildSentence(bank, rng, 5, 15));
      }
      if (startWithLorem && options.style === 'classic') {
        sentences[0] = LOREM_OPENER;
      }
      result = sentences.join(' ');
      if (isHtml) result = `<p>${result}</p>`;
      break;
    }

    case 'words': {
      const words: string[] = [];
      for (let i = 0; i < clampedCount; i++) {
        words.push(pick(bank, rng));
      }
      if (startWithLorem && options.style === 'classic' && clampedCount >= 2) {
        words[0] = 'lorem';
        words[1] = 'ipsum';
      }
      result = words.join(' ');
      if (isHtml) result = `<p>${result}</p>`;
      break;
    }

    case 'lists': {
      const items: string[] = [];
      for (let i = 0; i < clampedCount; i++) {
        items.push(buildSentence(bank, rng, 4, 10));
      }
      if (startWithLorem && options.style === 'classic') {
        items[0] = LOREM_OPENER;
      }
      if (isHtml) {
        result =
          '<ul>\n' +
          items.map(item => `  <li>${item}</li>`).join('\n') +
          '\n</ul>';
      } else {
        result = items.map((item, i) => `${i + 1}. ${item}`).join('\n');
      }
      break;
    }

    case 'headings': {
      const headings: string[] = [];
      for (let i = 0; i < clampedCount; i++) {
        const level = randBetween(1, 6, rng);
        const len = randBetween(3, 8, rng);
        const words: string[] = [];
        for (let w = 0; w < len; w++) words.push(pick(bank, rng));
        const text = capitalize(words.join(' '));
        headings.push(
          isHtml
            ? `<h${level}>${text}</h${level}>`
            : `${'#'.repeat(level)} ${text}`,
        );
      }
      result = headings.join('\n');
      break;
    }

    case 'links': {
      const links: string[] = [];
      const tlds = ['com', 'org', 'net', 'io', 'co', 'dev', 'app'];
      for (let i = 0; i < clampedCount; i++) {
        const textLen = randBetween(2, 5, rng);
        const words: string[] = [];
        for (let w = 0; w < textLen; w++) words.push(pick(bank, rng));
        const linkText = capitalize(words.join(' '));
        const domain =
          pick(bank, rng)
            .toLocaleLowerCase()
            .replace(/[^a-z]/g, '') || 'example';
        const tld = pick(tlds, rng);
        const url = `https://${domain}.${tld}`;
        links.push(
          isHtml ? `<a href="${url}">${linkText}</a>` : `[${linkText}](${url})`,
        );
      }
      result = links.join('\n');
      break;
    }

    case 'table': {
      const cols = Math.min(randBetween(3, 5, rng), 6);
      const headerWords: string[] = [];
      for (let c = 0; c < cols; c++)
        headerWords.push(capitalize(pick(bank, rng)));

      if (isHtml) {
        const thRow = headerWords.map(h => `    <th>${h}</th>`).join('\n');
        const bodyRows: string[] = [];
        for (let r = 0; r < clampedCount; r++) {
          const cells = [];
          for (let c = 0; c < cols; c++) {
            const cellLen = randBetween(1, 3, rng);
            const w: string[] = [];
            for (let k = 0; k < cellLen; k++) w.push(pick(bank, rng));
            cells.push(`    <td>${capitalize(w.join(' '))}</td>`);
          }
          bodyRows.push(`  <tr>\n${cells.join('\n')}\n  </tr>`);
        }
        result = `<table>\n  <thead>\n  <tr>\n${thRow}\n  </tr>\n  </thead>\n  <tbody>\n${bodyRows.join('\n')}\n  </tbody>\n</table>`;
      } else {
        const separator = headerWords.map(() => '---');
        const rows: string[] = [];
        rows.push('| ' + headerWords.join(' | ') + ' |');
        rows.push('| ' + separator.join(' | ') + ' |');
        for (let r = 0; r < clampedCount; r++) {
          const cells: string[] = [];
          for (let c = 0; c < cols; c++) {
            const cellLen = randBetween(1, 3, rng);
            const w: string[] = [];
            for (let k = 0; k < cellLen; k++) w.push(pick(bank, rng));
            cells.push(capitalize(w.join(' ')));
          }
          rows.push('| ' + cells.join(' | ') + ' |');
        }
        result = rows.join('\n');
      }
      break;
    }

    case 'blockquotes': {
      const quotes: string[] = [];
      for (let i = 0; i < clampedCount; i++) {
        const sentenceCount = randBetween(1, 3, rng);
        const sentences: string[] = [];
        for (let s = 0; s < sentenceCount; s++) {
          sentences.push(buildSentence(bank, rng, 5, 12));
        }
        const text = sentences.join(' ');
        quotes.push(
          isHtml ? `<blockquote><p>${text}</p></blockquote>` : `> ${text}`,
        );
      }
      result = isHtml ? quotes.join('\n') : quotes.join('\n\n');
      break;
    }

    case 'definitions': {
      const defs: string[] = [];
      for (let i = 0; i < clampedCount; i++) {
        const termLen = randBetween(1, 3, rng);
        const termWords: string[] = [];
        for (let w = 0; w < termLen; w++) termWords.push(pick(bank, rng));
        const term = capitalize(termWords.join(' '));
        const desc = buildSentence(bank, rng, 8, 18);
        if (isHtml) {
          defs.push(`<dt>${term}</dt>\n<dd>${desc}</dd>`);
        } else {
          defs.push(`${term}\n  ${desc}`);
        }
      }
      result = isHtml ? `<dl>\n${defs.join('\n')}\n</dl>` : defs.join('\n\n');
      break;
    }
  }

  return result;
}

// ---------------------------------------------------------------------------
// Statistics
// ---------------------------------------------------------------------------

export interface LoremStats {
  words: number;
  charsWithSpaces: number;
  charsWithoutSpaces: number;
  sentences: number;
  paragraphs: number;
  readingTime: string;
  bytes: number;
}

export function getLoremStats(text: string): LoremStats {
  const clean = text.replace(/<[^>]+>/g, '');
  const trimmed = clean.trim();
  if (!trimmed) {
    return {
      words: 0,
      charsWithSpaces: 0,
      charsWithoutSpaces: 0,
      sentences: 0,
      paragraphs: 0,
      readingTime: '0 s',
      bytes: 0,
    };
  }

  const words = trimmed.split(/\s+/).length;
  const charsWithSpaces = trimmed.length;
  const charsWithoutSpaces = trimmed.replace(/\s/g, '').length;
  const sentences = (trimmed.match(/[.!?]+/g) || []).length || 1;
  const paragraphs = trimmed.split(/\n\s*\n/).filter(Boolean).length || 1;
  const readingMinutes = words / 200;
  const bytes = new TextEncoder().encode(text).length;

  let readingTime: string;
  if (readingMinutes < 1) {
    readingTime = `${Math.max(1, Math.round(readingMinutes * 60))} s`;
  } else {
    readingTime = `${Math.round(readingMinutes)} min`;
  }

  return {
    words,
    charsWithSpaces,
    charsWithoutSpaces,
    sentences,
    paragraphs,
    readingTime,
    bytes,
  };
}

export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  return `${(bytes / 1024).toFixed(1)} KB`;
}
