import type { UnitConversionConfig } from '@/types/tools/units';
import { CSS_CONVERSION_FACTORS, CONVERSION_PRECISION, POPULAR_CSS_VALUES, RANGE_CONSTRAINTS, CONVERSION_FORMULAS } from '@/utils/conversion-constants';

// ---------------------------------------------------------------------------
// All 17 unit conversion configurations
// ---------------------------------------------------------------------------

export const UNIT_CONVERSIONS: UnitConversionConfig[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // A. Design / graphics (10)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    toolKey: 'ptToPx',
    category: 'css',
    sourceField: { label: 'Punkty', suffix: 'pt' },
    targetField: { label: 'Piksele', suffix: 'px' },
    convert: (v) => v * CSS_CONVERSION_FACTORS.PT_TO_PX,
    reverseConvert: (v) => v * CSS_CONVERSION_FACTORS.PX_TO_PT,
    formula: CONVERSION_FORMULAS.PT_TO_PX,
    reverseFormula: CONVERSION_FORMULAS.PX_TO_PT,
    precision: CONVERSION_PRECISION.DEFAULT,
    swappable: true,
    popularValues: POPULAR_CSS_VALUES.PT_TO_PX,
  },

  {
    toolKey: 'remToPx',
    category: 'css',
    sourceField: { label: 'rem', suffix: 'rem' },
    targetField: { label: 'Piksele', suffix: 'px' },
    extraField: {
      key: 'baseFontSize',
      label: 'Bazowy font-size',
      suffix: 'px',
      defaultValue: CSS_CONVERSION_FACTORS.DEFAULT_BASE_FONT_SIZE,
      ...RANGE_CONSTRAINTS.BASE_FONT_SIZE,
    },
    convert: (v, extra) => v * (extra ?? CSS_CONVERSION_FACTORS.DEFAULT_BASE_FONT_SIZE),
    reverseConvert: (v, extra) => v / (extra ?? CSS_CONVERSION_FACTORS.DEFAULT_BASE_FONT_SIZE),
    formula: CONVERSION_FORMULAS.REM_TO_PX,
    reverseFormula: CONVERSION_FORMULAS.PX_TO_REM,
    precision: CONVERSION_PRECISION.DEFAULT,
    swappable: true,
    popularValues: POPULAR_CSS_VALUES.REM_TO_PX,
  },

  {
    toolKey: 'emToPx',
    category: 'css',
    sourceField: { label: 'em', suffix: 'em' },
    targetField: { label: 'Piksele', suffix: 'px' },
    extraField: {
      key: 'parentFontSize',
      label: 'Font-size rodzica',
      suffix: 'px',
      defaultValue: CSS_CONVERSION_FACTORS.DEFAULT_PARENT_FONT_SIZE,
      ...RANGE_CONSTRAINTS.PARENT_FONT_SIZE,
    },
    convert: (v, extra) => v * (extra ?? CSS_CONVERSION_FACTORS.DEFAULT_PARENT_FONT_SIZE),
    reverseConvert: (v, extra) => v / (extra ?? CSS_CONVERSION_FACTORS.DEFAULT_PARENT_FONT_SIZE),
    formula: CONVERSION_FORMULAS.EM_TO_PX,
    reverseFormula: CONVERSION_FORMULAS.PX_TO_EM,
    precision: CONVERSION_PRECISION.DEFAULT,
    swappable: true,
    popularValues: POPULAR_CSS_VALUES.EM_TO_PX,
  },

  {
    toolKey: 'cmToPxDpi',
    category: 'css',
    sourceField: { label: 'Centymetry', suffix: 'cm' },
    targetField: { label: 'Piksele', suffix: 'px' },
    extraField: {
      key: 'dpi',
      label: 'DPI / PPI',
      suffix: 'dpi',
      defaultValue: 96,
      min: 1,
      max: 2400,
      step: 1,
    },
    convert: (v, extra) => (v * (extra ?? 96)) / 2.54,
    reverseConvert: (v, extra) => (v * 2.54) / (extra ?? 96),
    formula: 'px = cm \u00D7 DPI \u00F7 2,54',
    reverseFormula: 'cm = px \u00D7 2,54 \u00F7 DPI',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: 1, target: 38, label: '96 DPI' },
      { source: 2.54, target: 96, label: '1 cal @ 96 DPI' },
      { source: 5, target: 189 },
      { source: 10, target: 378 },
      { source: 21, target: 794, label: 'A4 szerokość @ 96 DPI' },
      { source: 29.7, target: 1123, label: 'A4 wysokość @ 96 DPI' },
    ],
  },

  {
    toolKey: 'mmToPxDpi',
    category: 'css',
    sourceField: { label: 'Milimetry', suffix: 'mm' },
    targetField: { label: 'Piksele', suffix: 'px' },
    extraField: {
      key: 'dpi',
      label: 'DPI / PPI',
      suffix: 'dpi',
      defaultValue: 96,
      min: 1,
      max: 2400,
      step: 1,
    },
    convert: (v, extra) => (v * (extra ?? 96)) / 25.4,
    reverseConvert: (v, extra) => (v * 25.4) / (extra ?? 96),
    formula: 'px = mm \u00D7 DPI \u00F7 25,4',
    reverseFormula: 'mm = px \u00D7 25,4 \u00F7 DPI',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: 1, target: 4, label: '96 DPI' },
      { source: 10, target: 38 },
      { source: 25.4, target: 96, label: '1 cal @ 96 DPI' },
      { source: 100, target: 378 },
      { source: 210, target: 794, label: 'A4 szerokość @ 96 DPI' },
      { source: 297, target: 1123, label: 'A4 wysokość @ 96 DPI' },
    ],
  },

  {
    toolKey: 'inchesToPxDpi',
    category: 'css',
    sourceField: { label: 'Cale', suffix: 'in' },
    targetField: { label: 'Piksele', suffix: 'px' },
    extraField: {
      key: 'dpi',
      label: 'DPI / PPI',
      suffix: 'dpi',
      defaultValue: 96,
      min: 1,
      max: 2400,
      step: 1,
    },
    convert: (v, extra) => v * (extra ?? 96),
    reverseConvert: (v, extra) => v / (extra ?? 96),
    formula: 'px = cale \u00D7 DPI',
    reverseFormula: 'cale = px \u00F7 DPI',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: 1, target: 96, label: '96 DPI' },
      { source: 1, target: 300, label: '300 DPI (druk)' },
      { source: 2, target: 192 },
      { source: 5, target: 480 },
      { source: 8.27, target: 794, label: 'A4 szerokość @ 96 DPI' },
      { source: 11.69, target: 1123, label: 'A4 wysokość @ 96 DPI' },
    ],
  },

  {
    toolKey: 'dpiToPpi',
    category: 'css',
    sourceField: { label: 'DPI (Dots Per Inch)', suffix: 'dpi' },
    targetField: { label: 'PPI (Pixels Per Inch)', suffix: 'ppi' },
    convert: (v) => v,
    reverseConvert: (v) => v,
    formula: 'PPI = DPI (wartość 1:1 dla ekranów)',
    reverseFormula: 'DPI = PPI (wartość 1:1 dla ekranów)',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: 72, target: 72, label: 'macOS klasyczny' },
      { source: 96, target: 96, label: 'Windows domyślnie' },
      { source: 150, target: 150, label: 'Druk ekonomiczny' },
      { source: 264, target: 264, label: 'iPad Retina' },
      { source: 300, target: 300, label: 'Druk fotograficzny' },
      { source: 460, target: 460, label: 'iPhone 15 Pro' },
    ],
  },

  {
    toolKey: 'hexToRgb',
    category: 'color',
    sourceField: { label: 'HEX', suffix: '', placeholder: '#3B82F6' },
    targetField: { label: 'RGB', suffix: '' },
    convert: () => 0,
    reverseConvert: () => 0,
    formula: 'R = parseInt(hex[1..2], 16), G = parseInt(hex[3..4], 16), B = parseInt(hex[5..6], 16)',
    reverseFormula: 'HEX = # + R.toString(16) + G.toString(16) + B.toString(16)',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: '#000000', target: 'rgb(0, 0, 0)', label: 'Czarny' },
      { source: '#FFFFFF', target: 'rgb(255, 255, 255)', label: 'Biały' },
      { source: '#FF0000', target: 'rgb(255, 0, 0)', label: 'Czerwony' },
      { source: '#00FF00', target: 'rgb(0, 255, 0)', label: 'Zielony' },
      { source: '#0000FF', target: 'rgb(0, 0, 255)', label: 'Niebieski' },
      { source: '#3B82F6', target: 'rgb(59, 130, 246)', label: 'Blue-500' },
    ],
  },

  {
    toolKey: 'rgbToHsl',
    category: 'color',
    sourceField: { label: 'RGB', suffix: '', placeholder: '59, 130, 246' },
    targetField: { label: 'HSL', suffix: '' },
    convert: () => 0,
    reverseConvert: () => 0,
    formula: 'H = arctan2(...), S = (max-min)/(1-|2L-1|), L = (max+min)/2',
    reverseFormula: 'R,G,B = f(H, S, L)',
    precision: 1,
    swappable: true,
    popularValues: [
      { source: '0, 0, 0', target: 'hsl(0, 0%, 0%)', label: 'Czarny' },
      { source: '255, 255, 255', target: 'hsl(0, 0%, 100%)', label: 'Biały' },
      { source: '255, 0, 0', target: 'hsl(0, 100%, 50%)', label: 'Czerwony' },
      { source: '0, 128, 0', target: 'hsl(120, 100%, 25%)', label: 'Zielony' },
      { source: '0, 0, 255', target: 'hsl(240, 100%, 50%)', label: 'Niebieski' },
      { source: '59, 130, 246', target: 'hsl(217, 91%, 60%)', label: 'Blue-500' },
    ],
  },

  {
    toolKey: 'rgbToCmyk',
    category: 'color',
    sourceField: { label: 'RGB', suffix: '', placeholder: '59, 130, 246' },
    targetField: { label: 'CMYK', suffix: '' },
    convert: () => 0,
    reverseConvert: () => 0,
    formula: 'K=1-max(R,G,B)/255, C=(1-R/255-K)/(1-K), M=(1-G/255-K)/(1-K), Y=(1-B/255-K)/(1-K)',
    reverseFormula: 'R=255(1-C)(1-K), G=255(1-M)(1-K), B=255(1-Y)(1-K)',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: '0, 0, 0', target: 'cmyk(0%, 0%, 0%, 100%)', label: 'Czarny' },
      { source: '255, 255, 255', target: 'cmyk(0%, 0%, 0%, 0%)', label: 'Biały' },
      { source: '255, 0, 0', target: 'cmyk(0%, 100%, 100%, 0%)', label: 'Czerwony' },
      { source: '0, 128, 0', target: 'cmyk(100%, 0%, 100%, 50%)', label: 'Zielony' },
      { source: '0, 0, 255', target: 'cmyk(100%, 100%, 0%, 0%)', label: 'Niebieski' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // B. Programming / technical (7)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    toolKey: 'bytesConverter',
    category: 'data',
    sourceField: { label: 'Bajty', suffix: 'B' },
    targetField: { label: 'Kilobajty', suffix: 'KB' },
    convert: (v) => v / 1024,
    reverseConvert: (v) => v * 1024,
    formula: 'KB = B \u00F7 1024',
    reverseFormula: 'B = KB \u00D7 1024',
    precision: 4,
    swappable: true,
    popularValues: [
      { source: 1024, target: 1, label: '1 KB' },
      { source: 1048576, target: 1024, label: '1 MB' },
      { source: 1073741824, target: 1048576, label: '1 GB' },
      { source: 5242880, target: 5120, label: '5 MB' },
      { source: 10485760, target: 10240, label: '10 MB' },
      { source: 104857600, target: 102400, label: '100 MB' },
    ],
  },

  {
    toolKey: 'unixTimestamp',
    category: 'time',
    sourceField: { label: 'Unix Timestamp', suffix: 's', placeholder: '1700000000' },
    targetField: { label: 'Data i czas', suffix: '' },
    convert: () => 0,
    reverseConvert: () => 0,
    formula: 'data = new Date(timestamp \u00D7 1000)',
    reverseFormula: 'timestamp = Date.getTime() \u00F7 1000',
    precision: 0,
    swappable: false,
    popularValues: [
      { source: 0, target: '1970-01-01 01:00:00', label: 'Epoka Unix' },
      { source: 1000000000, target: '2001-09-09 03:46:40', label: '1 miliard' },
      { source: 1700000000, target: '2023-11-14 23:13:20' },
      { source: 1735689600, target: '2025-01-01 01:00:00', label: 'Nowy Rok 2025' },
      { source: 2000000000, target: '2033-05-18 05:33:20', label: '2 miliardy' },
    ],
  },

  {
    toolKey: 'decToBin',
    category: 'math',
    sourceField: { label: 'Dziesiętny', suffix: '', placeholder: '255' },
    targetField: { label: 'Binarny', suffix: '' },
    convert: () => 0,
    reverseConvert: () => 0,
    formula: 'bin = dec.toString(2)',
    reverseFormula: 'dec = parseInt(bin, 2)',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: '1', target: '1' },
      { source: '8', target: '1000' },
      { source: '10', target: '1010' },
      { source: '16', target: '10000' },
      { source: '128', target: '10000000' },
      { source: '255', target: '11111111', label: 'Maks. bajt' },
      { source: '1024', target: '10000000000', label: '1 KB' },
    ],
  },

  {
    toolKey: 'decToHex',
    category: 'math',
    sourceField: { label: 'Dziesiętny', suffix: '', placeholder: '255' },
    targetField: { label: 'Szesnastkowy', suffix: '' },
    convert: () => 0,
    reverseConvert: () => 0,
    formula: 'hex = dec.toString(16).toUpperCase()',
    reverseFormula: 'dec = parseInt(hex, 16)',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: '10', target: 'A' },
      { source: '16', target: '10' },
      { source: '128', target: '80' },
      { source: '255', target: 'FF', label: 'Maks. bajt' },
      { source: '256', target: '100' },
      { source: '65535', target: 'FFFF', label: '16-bit max' },
      { source: '16777215', target: 'FFFFFF', label: 'Biały (RGB)' },
    ],
  },

  {
    toolKey: 'mbpsToMBs',
    category: 'data',
    sourceField: { label: 'Megabity/s', suffix: 'Mbps' },
    targetField: { label: 'Megabajty/s', suffix: 'MB/s' },
    convert: (v) => v / 8,
    reverseConvert: (v) => v * 8,
    formula: 'MB/s = Mbps \u00F7 8',
    reverseFormula: 'Mbps = MB/s \u00D7 8',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: 10, target: 1.25, label: 'ADSL' },
      { source: 50, target: 6.25, label: 'LTE' },
      { source: 100, target: 12.5, label: 'Światłowód 100' },
      { source: 300, target: 37.5, label: 'Światłowód 300' },
      { source: 500, target: 62.5, label: 'Światłowód 500' },
      { source: 1000, target: 125, label: '1 Gbps' },
    ],
  },

  {
    toolKey: 'vwToPx',
    category: 'css',
    sourceField: { label: 'vw (viewport width)', suffix: 'vw' },
    targetField: { label: 'Piksele', suffix: 'px' },
    extraField: {
      key: 'viewportWidth',
      label: 'Szerokość viewportu',
      suffix: 'px',
      defaultValue: 1920,
      min: 1,
      max: 7680,
      step: 1,
    },
    convert: (v, extra) => (v * (extra ?? 1920)) / 100,
    reverseConvert: (v, extra) => (v * 100) / (extra ?? 1920),
    formula: 'px = vw \u00D7 szerokosc viewportu \u00F7 100',
    reverseFormula: 'vw = px \u00D7 100 \u00F7 szerokosc viewportu',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: 1, target: 19.2, label: '1920px viewport' },
      { source: 5, target: 96 },
      { source: 10, target: 192 },
      { source: 25, target: 480 },
      { source: 50, target: 960 },
      { source: 100, target: 1920, label: 'Pełna szerokość' },
    ],
  },

  {
    toolKey: 'twToPx',
    category: 'css',
    sourceField: { label: 'Tailwind CSS spacing', suffix: 'tw', placeholder: '4' },
    targetField: { label: 'Piksele', suffix: 'px' },
    convert: (v) => v * 4,
    reverseConvert: (v) => v / 4,
    formula: 'px = spacing \u00D7 4 (domyślna skala Tailwind)',
    reverseFormula: 'spacing = px \u00F7 4',
    precision: 1,
    swappable: true,
    popularValues: [
      { source: 0.5, target: 2, label: 'p-0.5' },
      { source: 1, target: 4, label: 'p-1' },
      { source: 2, target: 8, label: 'p-2' },
      { source: 4, target: 16, label: 'p-4' },
      { source: 6, target: 24, label: 'p-6' },
      { source: 8, target: 32, label: 'p-8' },
      { source: 10, target: 40, label: 'p-10' },
      { source: 12, target: 48, label: 'p-12' },
      { source: 16, target: 64, label: 'p-16' },
      { source: 20, target: 80, label: 'p-20' },
      { source: 24, target: 96, label: 'p-24' },
    ],
  },
];

// ---------------------------------------------------------------------------
// Lookup helper
// ---------------------------------------------------------------------------

export function getUnitConversion(toolKey: string): UnitConversionConfig | undefined {
  return UNIT_CONVERSIONS.find((c) => c.toolKey === toolKey);
}
