import type { UnitConversionConfig } from '@/types/tools/units';

// ---------------------------------------------------------------------------
// All 34 unit conversion configurations
// ---------------------------------------------------------------------------

export const UNIT_CONVERSIONS: UnitConversionConfig[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // A. Popular / everyday (15)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    toolKey: 'kmToMiles',
    category: 'length',
    sourceField: { label: 'Kilometry', suffix: 'km' },
    targetField: { label: 'Mile', suffix: 'mi' },
    convert: (v) => v * 0.621371,
    reverseConvert: (v) => v / 0.621371,
    formula: 'mile = km × 0,621371',
    reverseFormula: 'km = mile ÷ 0,621371',
    precision: 4,
    swappable: true,
    popularValues: [
      { source: 1, target: 0.6214 },
      { source: 5, target: 3.1069 },
      { source: 10, target: 6.2137 },
      { source: 42.195, target: 26.2188, label: 'Maraton' },
      { source: 100, target: 62.1371 },
      { source: 500, target: 310.6855 },
      { source: 1000, target: 621.371 },
    ],
  },

  {
    toolKey: 'kgToLbs',
    category: 'weight',
    sourceField: { label: 'Kilogramy', suffix: 'kg' },
    targetField: { label: 'Funty', suffix: 'lbs' },
    convert: (v) => v * 2.20462,
    reverseConvert: (v) => v / 2.20462,
    formula: 'funty = kg × 2,20462',
    reverseFormula: 'kg = funty ÷ 2,20462',
    precision: 4,
    swappable: true,
    popularValues: [
      { source: 1, target: 2.2046 },
      { source: 5, target: 11.0231 },
      { source: 10, target: 22.0462 },
      { source: 50, target: 110.231 },
      { source: 70, target: 154.3234 },
      { source: 80, target: 176.3696 },
      { source: 100, target: 220.462 },
    ],
  },

  {
    toolKey: 'celsiusToFahrenheit',
    category: 'temperature',
    sourceField: { label: 'Celsjusz', suffix: '°C' },
    targetField: { label: 'Fahrenheit', suffix: '°F' },
    convert: (v) => (v * 9) / 5 + 32,
    reverseConvert: (v) => ((v - 32) * 5) / 9,
    formula: '°F = °C × 9/5 + 32',
    reverseFormula: '°C = (°F − 32) × 5/9',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: -40, target: -40, label: 'Punkt zrównania' },
      { source: 0, target: 32, label: 'Zamarzanie wody' },
      { source: 20, target: 68, label: 'Temperatura pokojowa' },
      { source: 36.6, target: 97.88, label: 'Temperatura ciała' },
      { source: 100, target: 212, label: 'Wrzenie wody' },
      { source: 180, target: 356, label: 'Piekarnik' },
    ],
  },

  {
    toolKey: 'cmToInches',
    category: 'length',
    sourceField: { label: 'Centymetry', suffix: 'cm' },
    targetField: { label: 'Cale', suffix: 'in' },
    convert: (v) => v / 2.54,
    reverseConvert: (v) => v * 2.54,
    formula: 'cale = cm ÷ 2,54',
    reverseFormula: 'cm = cale × 2,54',
    precision: 4,
    swappable: true,
    popularValues: [
      { source: 1, target: 0.3937 },
      { source: 2.54, target: 1, label: '1 cal' },
      { source: 10, target: 3.937 },
      { source: 30, target: 11.811 },
      { source: 100, target: 39.3701 },
      { source: 160, target: 62.9921, label: 'Wzrost ~160 cm' },
      { source: 180, target: 70.8661, label: 'Wzrost ~180 cm' },
    ],
  },

  {
    toolKey: 'metersToFeet',
    category: 'length',
    sourceField: { label: 'Metry', suffix: 'm' },
    targetField: { label: 'Stopy', suffix: 'ft' },
    convert: (v) => v * 3.28084,
    reverseConvert: (v) => v / 3.28084,
    formula: 'stopy = m × 3,28084',
    reverseFormula: 'm = stopy ÷ 3,28084',
    precision: 4,
    swappable: true,
    popularValues: [
      { source: 1, target: 3.2808 },
      { source: 1.8, target: 5.9055, label: 'Wzrost ~180 cm' },
      { source: 3, target: 9.8425 },
      { source: 10, target: 32.8084 },
      { source: 100, target: 328.084 },
      { source: 1000, target: 3280.84 },
    ],
  },

  {
    toolKey: 'litersToGallons',
    category: 'volume',
    sourceField: { label: 'Litry', suffix: 'l' },
    targetField: { label: 'Galony (US)', suffix: 'gal' },
    convert: (v) => v * 0.264172,
    reverseConvert: (v) => v / 0.264172,
    formula: 'galony = litry × 0,264172',
    reverseFormula: 'litry = galony ÷ 0,264172',
    precision: 4,
    swappable: true,
    popularValues: [
      { source: 1, target: 0.2642 },
      { source: 3.785, target: 1, label: '1 galon' },
      { source: 5, target: 1.3209 },
      { source: 10, target: 2.6417 },
      { source: 50, target: 13.2086 },
      { source: 100, target: 26.4172 },
    ],
  },

  {
    toolKey: 'sqmToSqft',
    category: 'area',
    sourceField: { label: 'Metry kwadratowe', suffix: 'm\u00B2' },
    targetField: { label: 'Stopy kwadratowe', suffix: 'ft\u00B2' },
    convert: (v) => v * 10.7639,
    reverseConvert: (v) => v / 10.7639,
    formula: 'ft\u00B2 = m\u00B2 \u00D7 10,7639',
    reverseFormula: 'm\u00B2 = ft\u00B2 \u00F7 10,7639',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: 1, target: 10.76 },
      { source: 10, target: 107.64 },
      { source: 25, target: 269.1, label: 'Kawalerka' },
      { source: 50, target: 538.2, label: 'Mieszkanie 2-pok.' },
      { source: 100, target: 1076.39, label: 'Dom jednorodzinny' },
      { source: 200, target: 2152.78 },
    ],
  },

  {
    toolKey: 'kmhToMph',
    category: 'speed',
    sourceField: { label: 'km/h', suffix: 'km/h' },
    targetField: { label: 'mph', suffix: 'mph' },
    convert: (v) => v * 0.621371,
    reverseConvert: (v) => v / 0.621371,
    formula: 'mph = km/h \u00D7 0,621371',
    reverseFormula: 'km/h = mph \u00F7 0,621371',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: 30, target: 18.64, label: 'Strefa miejska' },
      { source: 50, target: 31.07, label: 'Miasto' },
      { source: 90, target: 55.92, label: 'Droga ekspresowa' },
      { source: 120, target: 74.56, label: 'Autostrada PL' },
      { source: 130, target: 80.78, label: 'Autostrada DE (zalecana)' },
      { source: 200, target: 124.27 },
    ],
  },

  {
    toolKey: 'mmToInches',
    category: 'length',
    sourceField: { label: 'Milimetry', suffix: 'mm' },
    targetField: { label: 'Cale', suffix: 'in' },
    convert: (v) => v / 25.4,
    reverseConvert: (v) => v * 25.4,
    formula: 'cale = mm \u00F7 25,4',
    reverseFormula: 'mm = cale \u00D7 25,4',
    precision: 4,
    swappable: true,
    popularValues: [
      { source: 1, target: 0.0394 },
      { source: 5, target: 0.1969 },
      { source: 10, target: 0.3937 },
      { source: 25.4, target: 1, label: '1 cal' },
      { source: 100, target: 3.937 },
      { source: 300, target: 11.811 },
    ],
  },

  {
    toolKey: 'gramsToOunces',
    category: 'weight',
    sourceField: { label: 'Gramy', suffix: 'g' },
    targetField: { label: 'Uncje', suffix: 'oz' },
    convert: (v) => v * 0.035274,
    reverseConvert: (v) => v / 0.035274,
    formula: 'uncje = g \u00D7 0,035274',
    reverseFormula: 'g = uncje \u00F7 0,035274',
    precision: 4,
    swappable: true,
    popularValues: [
      { source: 1, target: 0.0353 },
      { source: 28.3495, target: 1, label: '1 uncja' },
      { source: 100, target: 3.5274 },
      { source: 250, target: 8.8185 },
      { source: 500, target: 17.637 },
      { source: 1000, target: 35.274 },
    ],
  },

  {
    toolKey: 'tonnesToPounds',
    category: 'weight',
    sourceField: { label: 'Tony metryczne', suffix: 't' },
    targetField: { label: 'Funty', suffix: 'lbs' },
    convert: (v) => v * 2204.62,
    reverseConvert: (v) => v / 2204.62,
    formula: 'funty = tony \u00D7 2204,62',
    reverseFormula: 'tony = funty \u00F7 2204,62',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: 0.5, target: 1102.31 },
      { source: 1, target: 2204.62 },
      { source: 5, target: 11023.1 },
      { source: 10, target: 22046.2 },
      { source: 50, target: 110231 },
      { source: 100, target: 220462 },
    ],
  },

  {
    toolKey: 'hectaresToAcres',
    category: 'area',
    sourceField: { label: 'Hektary', suffix: 'ha' },
    targetField: { label: 'Akry', suffix: 'ac' },
    convert: (v) => v * 2.47105,
    reverseConvert: (v) => v / 2.47105,
    formula: 'akry = ha \u00D7 2,47105',
    reverseFormula: 'ha = akry \u00F7 2,47105',
    precision: 4,
    swappable: true,
    popularValues: [
      { source: 0.4047, target: 1, label: '1 akr' },
      { source: 1, target: 2.4711 },
      { source: 5, target: 12.3553 },
      { source: 10, target: 24.7105 },
      { source: 50, target: 123.5525 },
      { source: 100, target: 247.105 },
    ],
  },

  {
    toolKey: 'mlToFlOz',
    category: 'volume',
    sourceField: { label: 'Mililitry', suffix: 'ml' },
    targetField: { label: 'Uncje płynne (US)', suffix: 'fl oz' },
    convert: (v) => v * 0.033814,
    reverseConvert: (v) => v / 0.033814,
    formula: 'fl oz = ml \u00D7 0,033814',
    reverseFormula: 'ml = fl oz \u00F7 0,033814',
    precision: 4,
    swappable: true,
    popularValues: [
      { source: 29.5735, target: 1, label: '1 fl oz' },
      { source: 100, target: 3.3814 },
      { source: 250, target: 8.4535, label: 'Szklanka' },
      { source: 330, target: 11.1587, label: 'Puszka' },
      { source: 500, target: 16.907 },
      { source: 1000, target: 33.814 },
    ],
  },

  {
    toolKey: 'barToPsi',
    category: 'pressure',
    sourceField: { label: 'Bar', suffix: 'bar' },
    targetField: { label: 'PSI', suffix: 'psi' },
    convert: (v) => v * 14.5038,
    reverseConvert: (v) => v / 14.5038,
    formula: 'psi = bar \u00D7 14,5038',
    reverseFormula: 'bar = psi \u00F7 14,5038',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: 1, target: 14.5 },
      { source: 2, target: 29.01, label: 'Opony rowerowe (szosa)' },
      { source: 2.2, target: 31.91, label: 'Opony samochodowe' },
      { source: 3, target: 43.51 },
      { source: 6, target: 87.02, label: 'Kompresor' },
      { source: 10, target: 145.04 },
    ],
  },

  {
    toolKey: 'kwToHp',
    category: 'power',
    sourceField: { label: 'Kilowaty', suffix: 'kW' },
    targetField: { label: 'Konie mechaniczne', suffix: 'KM' },
    convert: (v) => v * 1.35962,
    reverseConvert: (v) => v / 1.35962,
    formula: 'KM = kW \u00D7 1,35962',
    reverseFormula: 'kW = KM \u00F7 1,35962',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: 50, target: 67.98, label: 'Mały samochód' },
      { source: 75, target: 101.97, label: 'Kompakt' },
      { source: 110, target: 149.56, label: 'Sedan' },
      { source: 150, target: 203.94 },
      { source: 200, target: 271.92, label: 'Sportowy' },
      { source: 300, target: 407.89 },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // B. Design / graphics (10)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    toolKey: 'ptToPx',
    category: 'css',
    sourceField: { label: 'Punkty', suffix: 'pt' },
    targetField: { label: 'Piksele', suffix: 'px' },
    convert: (v) => v * 1.333333,
    reverseConvert: (v) => v / 1.333333,
    formula: 'px = pt \u00D7 1,3\u0305 (96/72)',
    reverseFormula: 'pt = px \u00D7 0,75 (72/96)',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: 8, target: 10.67 },
      { source: 9, target: 12, label: 'Tekst podstawowy' },
      { source: 10, target: 13.33 },
      { source: 12, target: 16, label: '1rem domyślnie' },
      { source: 14, target: 18.67 },
      { source: 18, target: 24, label: 'Nagłówek' },
      { source: 24, target: 32 },
      { source: 36, target: 48 },
      { source: 48, target: 64 },
      { source: 72, target: 96, label: '1 cal na ekranie' },
    ],
  },

  {
    toolKey: 'remToPx',
    category: 'css',
    sourceField: { label: 'rem', suffix: 'rem' },
    targetField: { label: 'Piksele', suffix: 'px' },
    extraField: {
      key: 'baseFontSize',
      label: 'Bazowy font-size',
      suffix: 'px',
      defaultValue: 16,
      min: 1,
      max: 100,
      step: 1,
    },
    convert: (v, extra) => v * (extra ?? 16),
    reverseConvert: (v, extra) => v / (extra ?? 16),
    formula: 'px = rem \u00D7 bazowy font-size',
    reverseFormula: 'rem = px \u00F7 bazowy font-size',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: 0.25, target: 4 },
      { source: 0.5, target: 8 },
      { source: 0.75, target: 12 },
      { source: 1, target: 16 },
      { source: 1.25, target: 20 },
      { source: 1.5, target: 24 },
      { source: 2, target: 32 },
      { source: 3, target: 48 },
      { source: 4, target: 64 },
      { source: 5, target: 80 },
    ],
  },

  {
    toolKey: 'emToPx',
    category: 'css',
    sourceField: { label: 'em', suffix: 'em' },
    targetField: { label: 'Piksele', suffix: 'px' },
    extraField: {
      key: 'parentFontSize',
      label: 'Font-size rodzica',
      suffix: 'px',
      defaultValue: 16,
      min: 1,
      max: 200,
      step: 1,
    },
    convert: (v, extra) => v * (extra ?? 16),
    reverseConvert: (v, extra) => v / (extra ?? 16),
    formula: 'px = em \u00D7 font-size rodzica',
    reverseFormula: 'em = px \u00F7 font-size rodzica',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: 0.5, target: 8 },
      { source: 0.75, target: 12 },
      { source: 1, target: 16 },
      { source: 1.25, target: 20 },
      { source: 1.5, target: 24 },
      { source: 2, target: 32 },
      { source: 2.5, target: 40 },
      { source: 3, target: 48 },
    ],
  },

  {
    toolKey: 'cmToPxDpi',
    category: 'css',
    sourceField: { label: 'Centymetry', suffix: 'cm' },
    targetField: { label: 'Piksele', suffix: 'px' },
    extraField: {
      key: 'dpi',
      label: 'DPI / PPI',
      suffix: 'dpi',
      defaultValue: 96,
      min: 1,
      max: 2400,
      step: 1,
    },
    convert: (v, extra) => (v * (extra ?? 96)) / 2.54,
    reverseConvert: (v, extra) => (v * 2.54) / (extra ?? 96),
    formula: 'px = cm \u00D7 DPI \u00F7 2,54',
    reverseFormula: 'cm = px \u00D7 2,54 \u00F7 DPI',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: 1, target: 38, label: '96 DPI' },
      { source: 2.54, target: 96, label: '1 cal @ 96 DPI' },
      { source: 5, target: 189 },
      { source: 10, target: 378 },
      { source: 21, target: 794, label: 'A4 szerokość @ 96 DPI' },
      { source: 29.7, target: 1123, label: 'A4 wysokość @ 96 DPI' },
    ],
  },

  {
    toolKey: 'mmToPxDpi',
    category: 'css',
    sourceField: { label: 'Milimetry', suffix: 'mm' },
    targetField: { label: 'Piksele', suffix: 'px' },
    extraField: {
      key: 'dpi',
      label: 'DPI / PPI',
      suffix: 'dpi',
      defaultValue: 96,
      min: 1,
      max: 2400,
      step: 1,
    },
    convert: (v, extra) => (v * (extra ?? 96)) / 25.4,
    reverseConvert: (v, extra) => (v * 25.4) / (extra ?? 96),
    formula: 'px = mm \u00D7 DPI \u00F7 25,4',
    reverseFormula: 'mm = px \u00D7 25,4 \u00F7 DPI',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: 1, target: 4, label: '96 DPI' },
      { source: 10, target: 38 },
      { source: 25.4, target: 96, label: '1 cal @ 96 DPI' },
      { source: 100, target: 378 },
      { source: 210, target: 794, label: 'A4 szerokość @ 96 DPI' },
      { source: 297, target: 1123, label: 'A4 wysokość @ 96 DPI' },
    ],
  },

  {
    toolKey: 'inchesToPxDpi',
    category: 'css',
    sourceField: { label: 'Cale', suffix: 'in' },
    targetField: { label: 'Piksele', suffix: 'px' },
    extraField: {
      key: 'dpi',
      label: 'DPI / PPI',
      suffix: 'dpi',
      defaultValue: 96,
      min: 1,
      max: 2400,
      step: 1,
    },
    convert: (v, extra) => v * (extra ?? 96),
    reverseConvert: (v, extra) => v / (extra ?? 96),
    formula: 'px = cale \u00D7 DPI',
    reverseFormula: 'cale = px \u00F7 DPI',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: 1, target: 96, label: '96 DPI' },
      { source: 1, target: 300, label: '300 DPI (druk)' },
      { source: 2, target: 192 },
      { source: 5, target: 480 },
      { source: 8.27, target: 794, label: 'A4 szerokość @ 96 DPI' },
      { source: 11.69, target: 1123, label: 'A4 wysokość @ 96 DPI' },
    ],
  },

  {
    toolKey: 'dpiToPpi',
    category: 'css',
    sourceField: { label: 'DPI (Dots Per Inch)', suffix: 'dpi' },
    targetField: { label: 'PPI (Pixels Per Inch)', suffix: 'ppi' },
    convert: (v) => v,
    reverseConvert: (v) => v,
    formula: 'PPI = DPI (wartość 1:1 dla ekranów)',
    reverseFormula: 'DPI = PPI (wartość 1:1 dla ekranów)',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: 72, target: 72, label: 'macOS klasyczny' },
      { source: 96, target: 96, label: 'Windows domyślnie' },
      { source: 150, target: 150, label: 'Druk ekonomiczny' },
      { source: 264, target: 264, label: 'iPad Retina' },
      { source: 300, target: 300, label: 'Druk fotograficzny' },
      { source: 460, target: 460, label: 'iPhone 15 Pro' },
    ],
  },

  {
    toolKey: 'hexToRgb',
    category: 'color',
    sourceField: { label: 'HEX', suffix: '', placeholder: '#3B82F6' },
    targetField: { label: 'RGB', suffix: '' },
    convert: () => 0,
    reverseConvert: () => 0,
    formula: 'R = parseInt(hex[1..2], 16), G = parseInt(hex[3..4], 16), B = parseInt(hex[5..6], 16)',
    reverseFormula: 'HEX = # + R.toString(16) + G.toString(16) + B.toString(16)',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: '#000000', target: 'rgb(0, 0, 0)', label: 'Czarny' },
      { source: '#FFFFFF', target: 'rgb(255, 255, 255)', label: 'Biały' },
      { source: '#FF0000', target: 'rgb(255, 0, 0)', label: 'Czerwony' },
      { source: '#00FF00', target: 'rgb(0, 255, 0)', label: 'Zielony' },
      { source: '#0000FF', target: 'rgb(0, 0, 255)', label: 'Niebieski' },
      { source: '#3B82F6', target: 'rgb(59, 130, 246)', label: 'Blue-500' },
    ],
  },

  {
    toolKey: 'rgbToHsl',
    category: 'color',
    sourceField: { label: 'RGB', suffix: '', placeholder: '59, 130, 246' },
    targetField: { label: 'HSL', suffix: '' },
    convert: () => 0,
    reverseConvert: () => 0,
    formula: 'H = arctan2(...), S = (max-min)/(1-|2L-1|), L = (max+min)/2',
    reverseFormula: 'R,G,B = f(H, S, L)',
    precision: 1,
    swappable: true,
    popularValues: [
      { source: '0, 0, 0', target: 'hsl(0, 0%, 0%)', label: 'Czarny' },
      { source: '255, 255, 255', target: 'hsl(0, 0%, 100%)', label: 'Biały' },
      { source: '255, 0, 0', target: 'hsl(0, 100%, 50%)', label: 'Czerwony' },
      { source: '0, 128, 0', target: 'hsl(120, 100%, 25%)', label: 'Zielony' },
      { source: '0, 0, 255', target: 'hsl(240, 100%, 50%)', label: 'Niebieski' },
      { source: '59, 130, 246', target: 'hsl(217, 91%, 60%)', label: 'Blue-500' },
    ],
  },

  {
    toolKey: 'rgbToCmyk',
    category: 'color',
    sourceField: { label: 'RGB', suffix: '', placeholder: '59, 130, 246' },
    targetField: { label: 'CMYK', suffix: '' },
    convert: () => 0,
    reverseConvert: () => 0,
    formula: 'K=1-max(R,G,B)/255, C=(1-R/255-K)/(1-K), M=(1-G/255-K)/(1-K), Y=(1-B/255-K)/(1-K)',
    reverseFormula: 'R=255(1-C)(1-K), G=255(1-M)(1-K), B=255(1-Y)(1-K)',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: '0, 0, 0', target: 'cmyk(0%, 0%, 0%, 100%)', label: 'Czarny' },
      { source: '255, 255, 255', target: 'cmyk(0%, 0%, 0%, 0%)', label: 'Biały' },
      { source: '255, 0, 0', target: 'cmyk(0%, 100%, 100%, 0%)', label: 'Czerwony' },
      { source: '0, 128, 0', target: 'cmyk(100%, 0%, 100%, 50%)', label: 'Zielony' },
      { source: '0, 0, 255', target: 'cmyk(100%, 100%, 0%, 0%)', label: 'Niebieski' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // C. Programming / technical (9)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    toolKey: 'bytesConverter',
    category: 'data',
    sourceField: { label: 'Bajty', suffix: 'B' },
    targetField: { label: 'Kilobajty', suffix: 'KB' },
    convert: (v) => v / 1024,
    reverseConvert: (v) => v * 1024,
    formula: 'KB = B \u00F7 1024',
    reverseFormula: 'B = KB \u00D7 1024',
    precision: 4,
    swappable: true,
    popularValues: [
      { source: 1024, target: 1, label: '1 KB' },
      { source: 1048576, target: 1024, label: '1 MB' },
      { source: 1073741824, target: 1048576, label: '1 GB' },
      { source: 5242880, target: 5120, label: '5 MB' },
      { source: 10485760, target: 10240, label: '10 MB' },
      { source: 104857600, target: 102400, label: '100 MB' },
    ],
  },

  {
    toolKey: 'unixTimestamp',
    category: 'time',
    sourceField: { label: 'Unix Timestamp', suffix: 's', placeholder: '1700000000' },
    targetField: { label: 'Data i czas', suffix: '' },
    convert: () => 0,
    reverseConvert: () => 0,
    formula: 'data = new Date(timestamp \u00D7 1000)',
    reverseFormula: 'timestamp = Date.getTime() \u00F7 1000',
    precision: 0,
    swappable: false,
    popularValues: [
      { source: 0, target: '1970-01-01 01:00:00', label: 'Epoka Unix' },
      { source: 1000000000, target: '2001-09-09 03:46:40', label: '1 miliard' },
      { source: 1700000000, target: '2023-11-14 23:13:20' },
      { source: 1735689600, target: '2025-01-01 01:00:00', label: 'Nowy Rok 2025' },
      { source: 2000000000, target: '2033-05-18 05:33:20', label: '2 miliardy' },
    ],
  },

  {
    toolKey: 'decToBin',
    category: 'math',
    sourceField: { label: 'Dziesiętny', suffix: '', placeholder: '255' },
    targetField: { label: 'Binarny', suffix: '' },
    convert: () => 0,
    reverseConvert: () => 0,
    formula: 'bin = dec.toString(2)',
    reverseFormula: 'dec = parseInt(bin, 2)',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: '1', target: '1' },
      { source: '8', target: '1000' },
      { source: '10', target: '1010' },
      { source: '16', target: '10000' },
      { source: '128', target: '10000000' },
      { source: '255', target: '11111111', label: 'Maks. bajt' },
      { source: '1024', target: '10000000000', label: '1 KB' },
    ],
  },

  {
    toolKey: 'decToHex',
    category: 'math',
    sourceField: { label: 'Dziesiętny', suffix: '', placeholder: '255' },
    targetField: { label: 'Szesnastkowy', suffix: '' },
    convert: () => 0,
    reverseConvert: () => 0,
    formula: 'hex = dec.toString(16).toUpperCase()',
    reverseFormula: 'dec = parseInt(hex, 16)',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: '10', target: 'A' },
      { source: '16', target: '10' },
      { source: '128', target: '80' },
      { source: '255', target: 'FF', label: 'Maks. bajt' },
      { source: '256', target: '100' },
      { source: '65535', target: 'FFFF', label: '16-bit max' },
      { source: '16777215', target: 'FFFFFF', label: 'Biały (RGB)' },
    ],
  },

  {
    toolKey: 'degToRad',
    category: 'math',
    sourceField: { label: 'Stopnie', suffix: '\u00B0' },
    targetField: { label: 'Radiany', suffix: 'rad' },
    convert: (v) => (v * Math.PI) / 180,
    reverseConvert: (v) => (v * 180) / Math.PI,
    formula: 'rad = stopnie \u00D7 \u03C0 \u00F7 180',
    reverseFormula: 'stopnie = rad \u00D7 180 \u00F7 \u03C0',
    precision: 6,
    swappable: true,
    popularValues: [
      { source: 0, target: 0 },
      { source: 30, target: 0.5236 },
      { source: 45, target: 0.7854 },
      { source: 90, target: 1.5708, label: 'Kąt prosty' },
      { source: 180, target: 3.1416, label: '\u03C0' },
      { source: 270, target: 4.7124 },
      { source: 360, target: 6.2832, label: 'Pełny obrót' },
    ],
  },

  {
    toolKey: 'mbpsToMBs',
    category: 'data',
    sourceField: { label: 'Megabity/s', suffix: 'Mbps' },
    targetField: { label: 'Megabajty/s', suffix: 'MB/s' },
    convert: (v) => v / 8,
    reverseConvert: (v) => v * 8,
    formula: 'MB/s = Mbps \u00F7 8',
    reverseFormula: 'Mbps = MB/s \u00D7 8',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: 10, target: 1.25, label: 'ADSL' },
      { source: 50, target: 6.25, label: 'LTE' },
      { source: 100, target: 12.5, label: 'Światłowód 100' },
      { source: 300, target: 37.5, label: 'Światłowód 300' },
      { source: 500, target: 62.5, label: 'Światłowód 500' },
      { source: 1000, target: 125, label: '1 Gbps' },
    ],
  },

  {
    toolKey: 'whToMah',
    category: 'energy',
    sourceField: { label: 'Watogodziny', suffix: 'Wh' },
    targetField: { label: 'Miliamperogodziny', suffix: 'mAh' },
    extraField: {
      key: 'voltage',
      label: 'Napięcie',
      suffix: 'V',
      defaultValue: 3.7,
      min: 0.1,
      max: 240,
      step: 0.1,
    },
    convert: (v, extra) => (v / (extra ?? 3.7)) * 1000,
    reverseConvert: (v, extra) => (v * (extra ?? 3.7)) / 1000,
    formula: 'mAh = (Wh \u00F7 V) \u00D7 1000',
    reverseFormula: 'Wh = (mAh \u00D7 V) \u00F7 1000',
    precision: 0,
    swappable: true,
    popularValues: [
      { source: 1.5, target: 405, label: 'Smartwatch' },
      { source: 11.55, target: 3122, label: 'Smartfon mały' },
      { source: 18.5, target: 5000, label: 'Smartfon duży' },
      { source: 38, target: 10270, label: 'Powerbank' },
      { source: 50, target: 13514, label: 'Laptop mały' },
      { source: 100, target: 27027, label: 'Laptop limit lotniczy' },
    ],
  },

  {
    toolKey: 'vwToPx',
    category: 'css',
    sourceField: { label: 'vw (viewport width)', suffix: 'vw' },
    targetField: { label: 'Piksele', suffix: 'px' },
    extraField: {
      key: 'viewportWidth',
      label: 'Szerokość viewportu',
      suffix: 'px',
      defaultValue: 1920,
      min: 1,
      max: 7680,
      step: 1,
    },
    convert: (v, extra) => (v * (extra ?? 1920)) / 100,
    reverseConvert: (v, extra) => (v * 100) / (extra ?? 1920),
    formula: 'px = vw \u00D7 szerokosc viewportu \u00F7 100',
    reverseFormula: 'vw = px \u00D7 100 \u00F7 szerokosc viewportu',
    precision: 2,
    swappable: true,
    popularValues: [
      { source: 1, target: 19.2, label: '1920px viewport' },
      { source: 5, target: 96 },
      { source: 10, target: 192 },
      { source: 25, target: 480 },
      { source: 50, target: 960 },
      { source: 100, target: 1920, label: 'Pełna szerokość' },
    ],
  },

  {
    toolKey: 'twToPx',
    category: 'css',
    sourceField: { label: 'Tailwind CSS spacing', suffix: 'tw', placeholder: '4' },
    targetField: { label: 'Piksele', suffix: 'px' },
    convert: (v) => v * 4,
    reverseConvert: (v) => v / 4,
    formula: 'px = spacing \u00D7 4 (domyślna skala Tailwind)',
    reverseFormula: 'spacing = px \u00F7 4',
    precision: 1,
    swappable: true,
    popularValues: [
      { source: 0.5, target: 2, label: 'p-0.5' },
      { source: 1, target: 4, label: 'p-1' },
      { source: 2, target: 8, label: 'p-2' },
      { source: 4, target: 16, label: 'p-4' },
      { source: 6, target: 24, label: 'p-6' },
      { source: 8, target: 32, label: 'p-8' },
      { source: 10, target: 40, label: 'p-10' },
      { source: 12, target: 48, label: 'p-12' },
      { source: 16, target: 64, label: 'p-16' },
      { source: 20, target: 80, label: 'p-20' },
      { source: 24, target: 96, label: 'p-24' },
    ],
  },
];

// ---------------------------------------------------------------------------
// Lookup helper
// ---------------------------------------------------------------------------

export function getUnitConversion(toolKey: string): UnitConversionConfig | undefined {
  return UNIT_CONVERSIONS.find((c) => c.toolKey === toolKey);
}
