import type { ReactNode } from 'react';
import {
  RiAlertLine,
  RiAppsLine,
  RiArticleLine,
  RiAspectRatioLine,
  RiBarChartLine,
  RiBloggerLine,
  RiBriefcaseLine,
  RiBrushLine,
  RiBuilding2Line,
  RiCalendarEventLine,
  RiCameraLine,
  RiCheckboxCircleLine,
  RiClipboardLine,
  RiCodeLine,
  RiContactsBookLine,
  RiContractLeftRightLine,
  RiContrast2Line,
  RiContrastLine,
  RiCropLine,
  RiCursorLine,
  RiDownloadLine,
  RiDropLine,
  RiEditLine,
  RiEqualizerLine,
  RiEraserLine,
  RiErrorWarningLine,
  RiEyeLine,
  RiFacebookLine,
  RiFileCodeLine,
  RiFileCopyLine,
  RiFileDownloadLine,
  RiFileImageLine,
  RiFileTextLine,
  RiFileWarningLine,
  RiFlashlightLine,
  RiFolderZipLine,
  RiGlobalLine,
  RiGraduationCapLine,
  RiGroupLine,
  RiHandCoinLine,
  RiHashtag,
  RiHome4Line,
  RiHospitalLine,
  RiHtml5Line,
  RiImageEditLine,
  RiImageLine,
  RiInfinityFill,
  RiInfinityLine,
  RiInstagramLine,
  RiLayoutGridLine,
  RiLayoutMasonryLine,
  RiLinkedinLine,
  RiListCheck2,
  RiLockLine,
  RiMagicLine,
  RiMailCheckLine,
  RiMailLine,
  RiMegaphoneLine,
  RiMoonLine,
  RiPaintBrushLine,
  RiPaletteLine,
  RiPantoneLine,
  RiParagraph,
  RiPencilLine,
  RiPhoneLine,
  RiPrinterLine,
  RiQrCodeLine,
  RiReactjsLine,
  RiRefreshLine,
  RiRestaurantLine,
  RiRuler2Line,
  RiRulerLine,
  RiSaveLine,
  RiScales3Line,
  RiSearchEyeLine,
  RiSearchLine,
  RiSettings3Line,
  RiShapeLine,
  RiShieldCheckLine,
  RiShoppingBagLine,
  RiShoppingCartLine,
  RiSlideshowLine,
  RiSmartphoneLine,
  RiSpaceShipLine,
  RiSparklingLine,
  RiSpeedLine,
  RiStackLine,
  RiStarLine,
  RiTeamLine,
  RiText,
  RiTimeLine,
  RiTimerLine,
  RiToolsLine,
  RiTranslate2,
  RiTruckLine,
  RiUploadLine,
  RiUserLine,
  RiWordpressLine,
  RiZoomInLine,
} from 'react-icons/ri';
import { normalIconSizeClasses } from '@/lib/uiClasses';

const ICON_MAP: Record<string, ReactNode> = {
  RiAlertLine: <RiAlertLine className={normalIconSizeClasses} />,
  RiAppsLine: <RiAppsLine className={normalIconSizeClasses} />,
  RiArticleLine: <RiArticleLine className={normalIconSizeClasses} />,
  RiAspectRatioLine: <RiAspectRatioLine className={normalIconSizeClasses} />,
  RiBarChartLine: <RiBarChartLine className={normalIconSizeClasses} />,
  RiBloggerLine: <RiBloggerLine className={normalIconSizeClasses} />,
  RiBriefcaseLine: <RiBriefcaseLine className={normalIconSizeClasses} />,
  RiBrushLine: <RiBrushLine className={normalIconSizeClasses} />,
  RiBuilding2Line: <RiBuilding2Line className={normalIconSizeClasses} />,
  RiCalendarEventLine: <RiCalendarEventLine className={normalIconSizeClasses} />,
  RiCameraLine: <RiCameraLine className={normalIconSizeClasses} />,
  RiCheckboxCircleLine: <RiCheckboxCircleLine className={normalIconSizeClasses} />,
  RiClipboardLine: <RiClipboardLine className={normalIconSizeClasses} />,
  RiCodeLine: <RiCodeLine className={normalIconSizeClasses} />,
  RiContactsBookLine: <RiContactsBookLine className={normalIconSizeClasses} />,
  RiContractLeftRightLine: <RiContractLeftRightLine className={normalIconSizeClasses} />,
  RiContrast2Line: <RiContrast2Line className={normalIconSizeClasses} />,
  RiContrastLine: <RiContrastLine className={normalIconSizeClasses} />,
  RiCropLine: <RiCropLine className={normalIconSizeClasses} />,
  RiCursorLine: <RiCursorLine className={normalIconSizeClasses} />,
  RiDownloadLine: <RiDownloadLine className={normalIconSizeClasses} />,
  RiDropLine: <RiDropLine className={normalIconSizeClasses} />,
  RiEditLine: <RiEditLine className={normalIconSizeClasses} />,
  RiEqualizerLine: <RiEqualizerLine className={normalIconSizeClasses} />,
  RiEraserLine: <RiEraserLine className={normalIconSizeClasses} />,
  RiErrorWarningLine: <RiErrorWarningLine className={normalIconSizeClasses} />,
  RiEyeLine: <RiEyeLine className={normalIconSizeClasses} />,
  RiFacebookLine: <RiFacebookLine className={normalIconSizeClasses} />,
  RiFileCodeLine: <RiFileCodeLine className={normalIconSizeClasses} />,
  RiFileCopyLine: <RiFileCopyLine className={normalIconSizeClasses} />,
  RiFileDownloadLine: <RiFileDownloadLine className={normalIconSizeClasses} />,
  RiFileImageLine: <RiFileImageLine className={normalIconSizeClasses} />,
  RiFileTextLine: <RiFileTextLine className={normalIconSizeClasses} />,
  RiFileWarningLine: <RiFileWarningLine className={normalIconSizeClasses} />,
  RiFlashlightLine: <RiFlashlightLine className={normalIconSizeClasses} />,
  RiFolderZipLine: <RiFolderZipLine className={normalIconSizeClasses} />,
  RiGlobalLine: <RiGlobalLine className={normalIconSizeClasses} />,
  RiGraduationCapLine: <RiGraduationCapLine className={normalIconSizeClasses} />,
  RiGroupLine: <RiGroupLine className={normalIconSizeClasses} />,
  RiHandCoinLine: <RiHandCoinLine className={normalIconSizeClasses} />,
  RiHashtag: <RiHashtag className={normalIconSizeClasses} />,
  RiHome4Line: <RiHome4Line className={normalIconSizeClasses} />,
  RiHospitalLine: <RiHospitalLine className={normalIconSizeClasses} />,
  RiHtml5Line: <RiHtml5Line className={normalIconSizeClasses} />,
  RiImageEditLine: <RiImageEditLine className={normalIconSizeClasses} />,
  RiImageLine: <RiImageLine className={normalIconSizeClasses} />,
  RiInfinityFill: <RiInfinityFill className={normalIconSizeClasses} />,
  RiInfinityLine: <RiInfinityLine className={normalIconSizeClasses} />,
  RiInstagramLine: <RiInstagramLine className={normalIconSizeClasses} />,
  RiLayoutGridLine: <RiLayoutGridLine className={normalIconSizeClasses} />,
  RiLayoutMasonryLine: <RiLayoutMasonryLine className={normalIconSizeClasses} />,
  RiLinkedinLine: <RiLinkedinLine className={normalIconSizeClasses} />,
  RiListCheck2: <RiListCheck2 className={normalIconSizeClasses} />,
  RiLockLine: <RiLockLine className={normalIconSizeClasses} />,
  RiMagicLine: <RiMagicLine className={normalIconSizeClasses} />,
  RiMailCheckLine: <RiMailCheckLine className={normalIconSizeClasses} />,
  RiMailLine: <RiMailLine className={normalIconSizeClasses} />,
  RiMegaphoneLine: <RiMegaphoneLine className={normalIconSizeClasses} />,
  RiMoonLine: <RiMoonLine className={normalIconSizeClasses} />,
  RiPaintBrushLine: <RiPaintBrushLine className={normalIconSizeClasses} />,
  RiPaletteLine: <RiPaletteLine className={normalIconSizeClasses} />,
  RiPantoneLine: <RiPantoneLine className={normalIconSizeClasses} />,
  RiParagraph: <RiParagraph className={normalIconSizeClasses} />,
  RiPencilLine: <RiPencilLine className={normalIconSizeClasses} />,
  RiPhoneLine: <RiPhoneLine className={normalIconSizeClasses} />,
  RiPrinterLine: <RiPrinterLine className={normalIconSizeClasses} />,
  RiQrCodeLine: <RiQrCodeLine className={normalIconSizeClasses} />,
  RiReactjsLine: <RiReactjsLine className={normalIconSizeClasses} />,
  RiRefreshLine: <RiRefreshLine className={normalIconSizeClasses} />,
  RiRestaurantLine: <RiRestaurantLine className={normalIconSizeClasses} />,
  RiRuler2Line: <RiRuler2Line className={normalIconSizeClasses} />,
  RiRulerLine: <RiRulerLine className={normalIconSizeClasses} />,
  RiSaveLine: <RiSaveLine className={normalIconSizeClasses} />,
  RiScales3Line: <RiScales3Line className={normalIconSizeClasses} />,
  RiSearchEyeLine: <RiSearchEyeLine className={normalIconSizeClasses} />,
  RiSearchLine: <RiSearchLine className={normalIconSizeClasses} />,
  RiSettings3Line: <RiSettings3Line className={normalIconSizeClasses} />,
  RiShapeLine: <RiShapeLine className={normalIconSizeClasses} />,
  RiShieldCheckLine: <RiShieldCheckLine className={normalIconSizeClasses} />,
  RiShoppingBagLine: <RiShoppingBagLine className={normalIconSizeClasses} />,
  RiShoppingCartLine: <RiShoppingCartLine className={normalIconSizeClasses} />,
  RiSlideshowLine: <RiSlideshowLine className={normalIconSizeClasses} />,
  RiSmartphoneLine: <RiSmartphoneLine className={normalIconSizeClasses} />,
  RiSpaceShipLine: <RiSpaceShipLine className={normalIconSizeClasses} />,
  RiSparklingLine: <RiSparklingLine className={normalIconSizeClasses} />,
  RiSpeedLine: <RiSpeedLine className={normalIconSizeClasses} />,
  RiStackLine: <RiStackLine className={normalIconSizeClasses} />,
  RiStarLine: <RiStarLine className={normalIconSizeClasses} />,
  RiTeamLine: <RiTeamLine className={normalIconSizeClasses} />,
  RiText: <RiText className={normalIconSizeClasses} />,
  RiTimeLine: <RiTimeLine className={normalIconSizeClasses} />,
  RiTimerLine: <RiTimerLine className={normalIconSizeClasses} />,
  RiToolsLine: <RiToolsLine className={normalIconSizeClasses} />,
  RiTranslate2: <RiTranslate2 className={normalIconSizeClasses} />,
  RiTruckLine: <RiTruckLine className={normalIconSizeClasses} />,
  RiUploadLine: <RiUploadLine className={normalIconSizeClasses} />,
  RiUserLine: <RiUserLine className={normalIconSizeClasses} />,
  RiWordpressLine: <RiWordpressLine className={normalIconSizeClasses} />,
  RiZoomInLine: <RiZoomInLine className={normalIconSizeClasses} />,
};

export function getToolIcon(key: string): ReactNode {
  return ICON_MAP[key] ?? null;
}
