import type { ReactNode } from 'react';
import {
  RiAlertLine,
  RiAppsLine,
  RiArticleLine,
  RiAspectRatioLine,
  RiBarChartLine,
  RiBloggerLine,
  RiBriefcaseLine,
  RiBrushLine,
  RiBuilding2Line,
  RiCalendarEventLine,
  RiCameraLine,
  RiCheckboxCircleLine,
  RiClipboardLine,
  RiCodeLine,
  RiContactsBookLine,
  RiContractLeftRightLine,
  RiContrast2Line,
  RiContrastLine,
  RiCropLine,
  RiCursorLine,
  RiDownloadLine,
  RiDropLine,
  RiEditLine,
  RiEqualizerLine,
  RiEraserLine,
  RiErrorWarningLine,
  RiEyeLine,
  RiFacebookLine,
  RiFileCodeLine,
  RiFileCopyLine,
  RiFileDownloadLine,
  RiFileImageLine,
  RiFileTextLine,
  RiFileWarningLine,
  RiFlashlightLine,
  RiFolderZipLine,
  RiGlobalLine,
  RiGraduationCapLine,
  RiGroupLine,
  RiHandCoinLine,
  RiHashtag,
  RiHome4Line,
  RiHospitalLine,
  RiHtml5Line,
  RiImageEditLine,
  RiImageLine,
  RiInfinityFill,
  RiInfinityLine,
  RiInstagramLine,
  RiLayoutGridLine,
  RiLayoutMasonryLine,
  RiLinkedinLine,
  RiListCheck2,
  RiLockLine,
  RiMagicLine,
  RiMailCheckLine,
  RiMailLine,
  RiMegaphoneLine,
  RiMoonLine,
  RiPaintBrushLine,
  RiPaletteLine,
  RiPantoneLine,
  RiParagraph,
  RiPencilLine,
  RiPhoneLine,
  RiPrinterLine,
  RiQrCodeLine,
  RiReactjsLine,
  RiRefreshLine,
  RiRestaurantLine,
  RiRuler2Line,
  RiRulerLine,
  RiSaveLine,
  RiScales3Line,
  RiSearchEyeLine,
  RiSearchLine,
  RiSettings3Line,
  RiShapeLine,
  RiShieldCheckLine,
  RiShoppingBagLine,
  RiShoppingCartLine,
  RiSlideshowLine,
  RiSmartphoneLine,
  RiSpaceShipLine,
  RiSparklingLine,
  RiSpeedLine,
  RiStackLine,
  RiStarLine,
  RiTeamLine,
  RiText,
  RiTimeLine,
  RiTimerLine,
  RiToolsLine,
  RiTranslate2,
  RiTruckLine,
  RiUploadLine,
  RiUserLine,
  RiWordpressLine,
  RiZoomInLine,
} from 'react-icons/ri';

const ICON_MAP: Record<string, ReactNode> = {
  RiAlertLine: <RiAlertLine className='h-6 w-6' />,
  RiAppsLine: <RiAppsLine className='h-6 w-6' />,
  RiArticleLine: <RiArticleLine className='h-6 w-6' />,
  RiAspectRatioLine: <RiAspectRatioLine className='h-6 w-6' />,
  RiBarChartLine: <RiBarChartLine className='h-6 w-6' />,
  RiBloggerLine: <RiBloggerLine className='h-6 w-6' />,
  RiBriefcaseLine: <RiBriefcaseLine className='h-6 w-6' />,
  RiBrushLine: <RiBrushLine className='h-6 w-6' />,
  RiBuilding2Line: <RiBuilding2Line className='h-6 w-6' />,
  RiCalendarEventLine: <RiCalendarEventLine className='h-6 w-6' />,
  RiCameraLine: <RiCameraLine className='h-6 w-6' />,
  RiCheckboxCircleLine: <RiCheckboxCircleLine className='h-6 w-6' />,
  RiClipboardLine: <RiClipboardLine className='h-6 w-6' />,
  RiCodeLine: <RiCodeLine className='h-6 w-6' />,
  RiContactsBookLine: <RiContactsBookLine className='h-6 w-6' />,
  RiContractLeftRightLine: <RiContractLeftRightLine className='h-6 w-6' />,
  RiContrast2Line: <RiContrast2Line className='h-6 w-6' />,
  RiContrastLine: <RiContrastLine className='h-6 w-6' />,
  RiCropLine: <RiCropLine className='h-6 w-6' />,
  RiCursorLine: <RiCursorLine className='h-6 w-6' />,
  RiDownloadLine: <RiDownloadLine className='h-6 w-6' />,
  RiDropLine: <RiDropLine className='h-6 w-6' />,
  RiEditLine: <RiEditLine className='h-6 w-6' />,
  RiEqualizerLine: <RiEqualizerLine className='h-6 w-6' />,
  RiEraserLine: <RiEraserLine className='h-6 w-6' />,
  RiErrorWarningLine: <RiErrorWarningLine className='h-6 w-6' />,
  RiEyeLine: <RiEyeLine className='h-6 w-6' />,
  RiFacebookLine: <RiFacebookLine className='h-6 w-6' />,
  RiFileCodeLine: <RiFileCodeLine className='h-6 w-6' />,
  RiFileCopyLine: <RiFileCopyLine className='h-6 w-6' />,
  RiFileDownloadLine: <RiFileDownloadLine className='h-6 w-6' />,
  RiFileImageLine: <RiFileImageLine className='h-6 w-6' />,
  RiFileTextLine: <RiFileTextLine className='h-6 w-6' />,
  RiFileWarningLine: <RiFileWarningLine className='h-6 w-6' />,
  RiFlashlightLine: <RiFlashlightLine className='h-6 w-6' />,
  RiFolderZipLine: <RiFolderZipLine className='h-6 w-6' />,
  RiGlobalLine: <RiGlobalLine className='h-6 w-6' />,
  RiGraduationCapLine: <RiGraduationCapLine className='h-6 w-6' />,
  RiGroupLine: <RiGroupLine className='h-6 w-6' />,
  RiHandCoinLine: <RiHandCoinLine className='h-6 w-6' />,
  RiHashtag: <RiHashtag className='h-6 w-6' />,
  RiHome4Line: <RiHome4Line className='h-6 w-6' />,
  RiHospitalLine: <RiHospitalLine className='h-6 w-6' />,
  RiHtml5Line: <RiHtml5Line className='h-6 w-6' />,
  RiImageEditLine: <RiImageEditLine className='h-6 w-6' />,
  RiImageLine: <RiImageLine className='h-6 w-6' />,
  RiInfinityFill: <RiInfinityFill className='h-6 w-6' />,
  RiInfinityLine: <RiInfinityLine className='h-6 w-6' />,
  RiInstagramLine: <RiInstagramLine className='h-6 w-6' />,
  RiLayoutGridLine: <RiLayoutGridLine className='h-6 w-6' />,
  RiLayoutMasonryLine: <RiLayoutMasonryLine className='h-6 w-6' />,
  RiLinkedinLine: <RiLinkedinLine className='h-6 w-6' />,
  RiListCheck2: <RiListCheck2 className='h-6 w-6' />,
  RiLockLine: <RiLockLine className='h-6 w-6' />,
  RiMagicLine: <RiMagicLine className='h-6 w-6' />,
  RiMailCheckLine: <RiMailCheckLine className='h-6 w-6' />,
  RiMailLine: <RiMailLine className='h-6 w-6' />,
  RiMegaphoneLine: <RiMegaphoneLine className='h-6 w-6' />,
  RiMoonLine: <RiMoonLine className='h-6 w-6' />,
  RiPaintBrushLine: <RiPaintBrushLine className='h-6 w-6' />,
  RiPaletteLine: <RiPaletteLine className='h-6 w-6' />,
  RiPantoneLine: <RiPantoneLine className='h-6 w-6' />,
  RiParagraph: <RiParagraph className='h-6 w-6' />,
  RiPencilLine: <RiPencilLine className='h-6 w-6' />,
  RiPhoneLine: <RiPhoneLine className='h-6 w-6' />,
  RiPrinterLine: <RiPrinterLine className='h-6 w-6' />,
  RiQrCodeLine: <RiQrCodeLine className='h-6 w-6' />,
  RiReactjsLine: <RiReactjsLine className='h-6 w-6' />,
  RiRefreshLine: <RiRefreshLine className='h-6 w-6' />,
  RiRestaurantLine: <RiRestaurantLine className='h-6 w-6' />,
  RiRuler2Line: <RiRuler2Line className='h-6 w-6' />,
  RiRulerLine: <RiRulerLine className='h-6 w-6' />,
  RiSaveLine: <RiSaveLine className='h-6 w-6' />,
  RiScales3Line: <RiScales3Line className='h-6 w-6' />,
  RiSearchEyeLine: <RiSearchEyeLine className='h-6 w-6' />,
  RiSearchLine: <RiSearchLine className='h-6 w-6' />,
  RiSettings3Line: <RiSettings3Line className='h-6 w-6' />,
  RiShapeLine: <RiShapeLine className='h-6 w-6' />,
  RiShieldCheckLine: <RiShieldCheckLine className='h-6 w-6' />,
  RiShoppingBagLine: <RiShoppingBagLine className='h-6 w-6' />,
  RiShoppingCartLine: <RiShoppingCartLine className='h-6 w-6' />,
  RiSlideshowLine: <RiSlideshowLine className='h-6 w-6' />,
  RiSmartphoneLine: <RiSmartphoneLine className='h-6 w-6' />,
  RiSpaceShipLine: <RiSpaceShipLine className='h-6 w-6' />,
  RiSparklingLine: <RiSparklingLine className='h-6 w-6' />,
  RiSpeedLine: <RiSpeedLine className='h-6 w-6' />,
  RiStackLine: <RiStackLine className='h-6 w-6' />,
  RiStarLine: <RiStarLine className='h-6 w-6' />,
  RiTeamLine: <RiTeamLine className='h-6 w-6' />,
  RiText: <RiText className='h-6 w-6' />,
  RiTimeLine: <RiTimeLine className='h-6 w-6' />,
  RiTimerLine: <RiTimerLine className='h-6 w-6' />,
  RiToolsLine: <RiToolsLine className='h-6 w-6' />,
  RiTranslate2: <RiTranslate2 className='h-6 w-6' />,
  RiTruckLine: <RiTruckLine className='h-6 w-6' />,
  RiUploadLine: <RiUploadLine className='h-6 w-6' />,
  RiUserLine: <RiUserLine className='h-6 w-6' />,
  RiWordpressLine: <RiWordpressLine className='h-6 w-6' />,
  RiZoomInLine: <RiZoomInLine className='h-6 w-6' />,
};

export function getToolIcon(key: string): ReactNode {
  return ICON_MAP[key] ?? null;
}
