/**
 * Locale utilities and category labels
 * Helper functions for locale-specific operations
 */

import type { FormatCategory } from './formats';

// Category Labels per locale
export const CATEGORY_LABELS: Record<FormatCategory, Record<string, string>> = {
  images: {
    pl: 'Obrazy',
    en: 'Images',
    de: 'Bilder',
    es: 'Imágenes',
    fr: 'Images',
    pt: 'Imagens',
    it: 'Immagini',
    cs: 'Obrázky',
    el: 'Εικόνες',
  },
  documents: {
    pl: 'Dokumenty',
    en: 'Documents',
    de: 'Dokumente',
    es: 'Documentos',
    fr: 'Documents',
    pt: 'Documentos',
    it: 'Documenti',
    cs: 'Dokumenty',
    el: 'Έγγραφα',
  },
  data: {
    pl: 'Dane',
    en: 'Data',
    de: 'Daten',
    es: 'Datos',
    fr: 'Données',
    pt: 'Dados',
    it: 'Dati',
    cs: 'Data',
    el: 'Δεδομένα',
  },
  units: {
    pl: 'Jednostki',
    en: 'Units',
    de: 'Einheiten',
    es: 'Unidades',
    fr: 'Unités',
    pt: 'Unidades',
    it: 'Unità',
    cs: 'Jednotky',
    el: 'Μονάδες',
  },
} as const;

// ---------------------------------------------------------------------------
// Unit Converter Labels per locale
// ---------------------------------------------------------------------------

const UNIT_LABELS: Record<string, Record<string, string>> = {
  // Field labels
  points: {
    pl: 'Punkty',
    en: 'Points',
    de: 'Punkte',
    es: 'Puntos',
    fr: 'Points',
    pt: 'Pontos',
    it: 'Punti',
    cs: 'Body',
    el: 'Σημεία',
  },
  pixels: {
    pl: 'Piksele',
    en: 'Pixels',
    de: 'Pixel',
    es: 'Píxeles',
    fr: 'Pixels',
    pt: 'Pixels',
    it: 'Pixel',
    cs: 'Pixely',
    el: 'Εικονοστοιχεία',
  },
  baseFontSize: {
    pl: 'Bazowy font-size',
    en: 'Base font-size',
    de: 'Basis-Schriftgröße',
    es: 'Tamaño de fuente base',
    fr: 'Taille de police de base',
    pt: 'Tamanho de fonte base',
    it: 'Dimensione font base',
    cs: 'Základní velikost písma',
    el: 'Βασικό μέγεθος γραμματοσειράς',
  },
  parentFontSize: {
    pl: 'Font-size rodzica',
    en: 'Parent font-size',
    de: 'Eltern-Schriftgröße',
    es: 'Tamaño de fuente padre',
    fr: 'Taille de police parent',
    pt: 'Tamanho de fonte pai',
    it: 'Dimensione font genitore',
    cs: 'Velikost písma rodiče',
    el: 'Μέγεθος γραμματοσειράς γονέα',
  },
  centimeters: {
    pl: 'Centymetry',
    en: 'Centimeters',
    de: 'Zentimeter',
    es: 'Centímetros',
    fr: 'Centimètres',
    pt: 'Centímetros',
    it: 'Centimetri',
    cs: 'Centimetry',
    el: 'Εκατοστά',
  },
  millimeters: {
    pl: 'Milimetry',
    en: 'Millimeters',
    de: 'Millimeter',
    es: 'Milímetros',
    fr: 'Millimètres',
    pt: 'Milímetros',
    it: 'Millimetri',
    cs: 'Milimetry',
    el: 'Χιλιοστά',
  },
  inches: {
    pl: 'Cale',
    en: 'Inches',
    de: 'Zoll',
    es: 'Pulgadas',
    fr: 'Pouces',
    pt: 'Polegadas',
    it: 'Pollici',
    cs: 'Palce',
    el: 'Ίντσες',
  },
  kilograms: {
    pl: 'Kilogramy',
    en: 'Kilograms',
    de: 'Kilogramm',
    es: 'Kilogramos',
    fr: 'Kilogrammes',
    pt: 'Quilogramas',
    it: 'Chilogrammi',
    cs: 'Kilogramy',
    el: 'Χιλιόγραμμα',
  },
  pounds: {
    pl: 'Funty (lb)',
    en: 'Pounds (lb)',
    de: 'Pfund (lb)',
    es: 'Libras (lb)',
    fr: 'Livres (lb)',
    pt: 'Libras (lb)',
    it: 'Libbre (lb)',
    cs: 'Libry (lb)',
    el: 'Λίβρες (lb)',
  },
  bytes: {
    pl: 'Bajty',
    en: 'Bytes',
    de: 'Bytes',
    es: 'Bytes',
    fr: 'Octets',
    pt: 'Bytes',
    it: 'Byte',
    cs: 'Bajty',
    el: 'Bytes',
  },
  kilobytes: {
    pl: 'Kilobajty',
    en: 'Kilobytes',
    de: 'Kilobytes',
    es: 'Kilobytes',
    fr: 'Kilooctets',
    pt: 'Kilobytes',
    it: 'Kilobyte',
    cs: 'Kilobajty',
    el: 'Kilobytes',
  },
  dateTime: {
    pl: 'Data i czas',
    en: 'Date and time',
    de: 'Datum und Uhrzeit',
    es: 'Fecha y hora',
    fr: 'Date et heure',
    pt: 'Data e hora',
    it: 'Data e ora',
    cs: 'Datum a čas',
    el: 'Ημερομηνία και ώρα',
  },
  decimal: {
    pl: 'Dziesiętny',
    en: 'Decimal',
    de: 'Dezimal',
    es: 'Decimal',
    fr: 'Décimal',
    pt: 'Decimal',
    it: 'Decimale',
    cs: 'Desítkový',
    el: 'Δεκαδικός',
  },
  binary: {
    pl: 'Binarny',
    en: 'Binary',
    de: 'Binär',
    es: 'Binario',
    fr: 'Binaire',
    pt: 'Binário',
    it: 'Binario',
    cs: 'Binární',
    el: 'Δυαδικός',
  },
  hexadecimal: {
    pl: 'Szesnastkowy',
    en: 'Hexadecimal',
    de: 'Hexadezimal',
    es: 'Hexadecimal',
    fr: 'Hexadécimal',
    pt: 'Hexadecimal',
    it: 'Esadecimale',
    cs: 'Šestnáctkový',
    el: 'Δεκαεξαδικός',
  },
  megabitsPerSec: {
    pl: 'Megabity/s',
    en: 'Megabits/s',
    de: 'Megabit/s',
    es: 'Megabits/s',
    fr: 'Mégabits/s',
    pt: 'Megabits/s',
    it: 'Megabit/s',
    cs: 'Megabity/s',
    el: 'Megabits/s',
  },
  megabytesPerSec: {
    pl: 'Megabajty/s',
    en: 'Megabytes/s',
    de: 'Megabyte/s',
    es: 'Megabytes/s',
    fr: 'Mégaoctets/s',
    pt: 'Megabytes/s',
    it: 'Megabyte/s',
    cs: 'Megabajty/s',
    el: 'Megabytes/s',
  },
  viewportWidth: {
    pl: 'Szerokość viewportu',
    en: 'Viewport width',
    de: 'Viewport-Breite',
    es: 'Ancho del viewport',
    fr: 'Largeur du viewport',
    pt: 'Largura do viewport',
    it: 'Larghezza viewport',
    cs: 'Šířka viewportu',
    el: 'Πλάτος viewport',
  },
  dpiPpi: {
    pl: 'DPI / PPI',
    en: 'DPI / PPI',
    de: 'DPI / PPI',
    es: 'DPI / PPI',
    fr: 'DPI / PPI',
    pt: 'DPI / PPI',
    it: 'DPI / PPI',
    cs: 'DPI / PPI',
    el: 'DPI / PPI',
  },
  dpi: {
    pl: 'DPI (Dots Per Inch)',
    en: 'DPI (Dots Per Inch)',
    de: 'DPI (Punkte pro Zoll)',
    es: 'DPI (Puntos Por Pulgada)',
    fr: 'DPI (Points Par Pouce)',
    pt: 'DPI (Pontos Por Polegada)',
    it: 'DPI (Punti Per Pollice)',
    cs: 'DPI (Body Na Palec)',
    el: 'DPI (Κουκκίδες Ανά Ίντσα)',
  },
  ppi: {
    pl: 'PPI (Pixels Per Inch)',
    en: 'PPI (Pixels Per Inch)',
    de: 'PPI (Pixel pro Zoll)',
    es: 'PPI (Píxeles Por Pulgada)',
    fr: 'PPI (Pixels Par Pouce)',
    pt: 'PPI (Pixels Por Polegada)',
    it: 'PPI (Pixel Per Pollice)',
    cs: 'PPI (Pixely Na Palec)',
    el: 'PPI (Εικονοστοιχεία Ανά Ίντσα)',
  },
  tailwindSpacing: {
    pl: 'Tailwind CSS spacing',
    en: 'Tailwind CSS spacing',
    de: 'Tailwind CSS Abstand',
    es: 'Espaciado Tailwind CSS',
    fr: 'Espacement Tailwind CSS',
    pt: 'Espaçamento Tailwind CSS',
    it: 'Spaziatura Tailwind CSS',
    cs: 'Tailwind CSS mezery',
    el: 'Tailwind CSS απόσταση',
  },
  unixTimestamp: {
    pl: 'Unix Timestamp',
    en: 'Unix Timestamp',
    de: 'Unix-Zeitstempel',
    es: 'Marca de tiempo Unix',
    fr: 'Horodatage Unix',
    pt: 'Timestamp Unix',
    it: 'Timestamp Unix',
    cs: 'Unix časové razítko',
    el: 'Unix Timestamp',
  },
  vw: {
    pl: 'vw (viewport width)',
    en: 'vw (viewport width)',
    de: 'vw (Viewport-Breite)',
    es: 'vw (ancho viewport)',
    fr: 'vw (largeur viewport)',
    pt: 'vw (largura viewport)',
    it: 'vw (larghezza viewport)',
    cs: 'vw (šířka viewportu)',
    el: 'vw (πλάτος viewport)',
  },
  rem: {
    pl: 'rem',
    en: 'rem',
    de: 'rem',
    es: 'rem',
    fr: 'rem',
    pt: 'rem',
    it: 'rem',
    cs: 'rem',
    el: 'rem',
  },
  em: {
    pl: 'em',
    en: 'em',
    de: 'em',
    es: 'em',
    fr: 'em',
    pt: 'em',
    it: 'em',
    cs: 'em',
    el: 'em',
  },
  hex: {
    pl: 'HEX',
    en: 'HEX',
    de: 'HEX',
    es: 'HEX',
    fr: 'HEX',
    pt: 'HEX',
    it: 'HEX',
    cs: 'HEX',
    el: 'HEX',
  },
  rgb: {
    pl: 'RGB',
    en: 'RGB',
    de: 'RGB',
    es: 'RGB',
    fr: 'RGB',
    pt: 'RGB',
    it: 'RGB',
    cs: 'RGB',
    el: 'RGB',
  },
  hsl: {
    pl: 'HSL',
    en: 'HSL',
    de: 'HSL',
    es: 'HSL',
    fr: 'HSL',
    pt: 'HSL',
    it: 'HSL',
    cs: 'HSL',
    el: 'HSL',
  },
  cmyk: {
    pl: 'CMYK',
    en: 'CMYK',
    de: 'CMYK',
    es: 'CMYK',
    fr: 'CMYK',
    pt: 'CMYK',
    it: 'CMYK',
    cs: 'CMYK',
    el: 'CMYK',
  },
  // Popular value labels
  macOsClassic: {
    pl: 'macOS klasyczny',
    en: 'macOS classic',
    de: 'macOS klassisch',
    es: 'macOS clásico',
    fr: 'macOS classique',
    pt: 'macOS clássico',
    it: 'macOS classico',
    cs: 'macOS klasický',
    el: 'macOS κλασικό',
  },
  windowsDefault: {
    pl: 'Windows domyślnie',
    en: 'Windows default',
    de: 'Windows Standard',
    es: 'Windows predeterminado',
    fr: 'Windows par défaut',
    pt: 'Windows padrão',
    it: 'Windows predefinito',
    cs: 'Windows výchozí',
    el: 'Windows προεπιλογή',
  },
  economyPrint: {
    pl: 'Druk ekonomiczny',
    en: 'Economy print',
    de: 'Spardruck',
    es: 'Impresión económica',
    fr: 'Impression économique',
    pt: 'Impressão econômica',
    it: 'Stampa economica',
    cs: 'Úsporný tisk',
    el: 'Οικονομική εκτύπωση',
  },
  photoPrint: {
    pl: 'Druk fotograficzny',
    en: 'Photo print',
    de: 'Fotodruck',
    es: 'Impresión fotográfica',
    fr: 'Impression photo',
    pt: 'Impressão fotográfica',
    it: 'Stampa fotografica',
    cs: 'Fotografický tisk',
    el: 'Φωτογραφική εκτύπωση',
  },
  black: {
    pl: 'Czarny',
    en: 'Black',
    de: 'Schwarz',
    es: 'Negro',
    fr: 'Noir',
    pt: 'Preto',
    it: 'Nero',
    cs: 'Černá',
    el: 'Μαύρο',
  },
  white: {
    pl: 'Biały',
    en: 'White',
    de: 'Weiß',
    es: 'Blanco',
    fr: 'Blanc',
    pt: 'Branco',
    it: 'Bianco',
    cs: 'Bílá',
    el: 'Λευκό',
  },
  red: {
    pl: 'Czerwony',
    en: 'Red',
    de: 'Rot',
    es: 'Rojo',
    fr: 'Rouge',
    pt: 'Vermelho',
    it: 'Rosso',
    cs: 'Červená',
    el: 'Κόκκινο',
  },
  green: {
    pl: 'Zielony',
    en: 'Green',
    de: 'Grün',
    es: 'Verde',
    fr: 'Vert',
    pt: 'Verde',
    it: 'Verde',
    cs: 'Zelená',
    el: 'Πράσινο',
  },
  blue: {
    pl: 'Niebieski',
    en: 'Blue',
    de: 'Blau',
    es: 'Azul',
    fr: 'Bleu',
    pt: 'Azul',
    it: 'Blu',
    cs: 'Modrá',
    el: 'Μπλε',
  },
  unixEpoch: {
    pl: 'Epoka Unix',
    en: 'Unix Epoch',
    de: 'Unix-Epoche',
    es: 'Época Unix',
    fr: 'Époque Unix',
    pt: 'Época Unix',
    it: 'Epoca Unix',
    cs: 'Unix epocha',
    el: 'Εποχή Unix',
  },
  oneBillion: {
    pl: '1 miliard',
    en: '1 billion',
    de: '1 Milliarde',
    es: '1 mil millones',
    fr: '1 milliard',
    pt: '1 bilhão',
    it: '1 miliardo',
    cs: '1 miliarda',
    el: '1 δισεκατομμύριο',
  },
  twoBillion: {
    pl: '2 miliardy',
    en: '2 billion',
    de: '2 Milliarden',
    es: '2 mil millones',
    fr: '2 milliards',
    pt: '2 bilhões',
    it: '2 miliardi',
    cs: '2 miliardy',
    el: '2 δισεκατομμύρια',
  },
  newYear2025: {
    pl: 'Nowy Rok 2025',
    en: 'New Year 2025',
    de: 'Neujahr 2025',
    es: 'Año Nuevo 2025',
    fr: 'Nouvel An 2025',
    pt: 'Ano Novo 2025',
    it: 'Capodanno 2025',
    cs: 'Nový rok 2025',
    el: 'Πρωτοχρονιά 2025',
  },
  maxByte: {
    pl: 'Maks. bajt',
    en: 'Max byte',
    de: 'Max. Byte',
    es: 'Byte máx.',
    fr: 'Octet max.',
    pt: 'Byte máx.',
    it: 'Byte max.',
    cs: 'Max. bajt',
    el: 'Μέγ. byte',
  },
  whiteRgb: {
    pl: 'Biały (RGB)',
    en: 'White (RGB)',
    de: 'Weiß (RGB)',
    es: 'Blanco (RGB)',
    fr: 'Blanc (RGB)',
    pt: 'Branco (RGB)',
    it: 'Bianco (RGB)',
    cs: 'Bílá (RGB)',
    el: 'Λευκό (RGB)',
  },
  fiber100: {
    pl: 'Światłowód 100',
    en: 'Fiber 100',
    de: 'Glasfaser 100',
    es: 'Fibra 100',
    fr: 'Fibre 100',
    pt: 'Fibra 100',
    it: 'Fibra 100',
    cs: 'Optika 100',
    el: 'Οπτική ίνα 100',
  },
  fiber300: {
    pl: 'Światłowód 300',
    en: 'Fiber 300',
    de: 'Glasfaser 300',
    es: 'Fibra 300',
    fr: 'Fibre 300',
    pt: 'Fibra 300',
    it: 'Fibra 300',
    cs: 'Optika 300',
    el: 'Οπτική ίνα 300',
  },
  fiber500: {
    pl: 'Światłowód 500',
    en: 'Fiber 500',
    de: 'Glasfaser 500',
    es: 'Fibra 500',
    fr: 'Fibre 500',
    pt: 'Fibra 500',
    it: 'Fibra 500',
    cs: 'Optika 500',
    el: 'Οπτική ίνα 500',
  },
  fullWidth: {
    pl: 'Pełna szerokość',
    en: 'Full width',
    de: 'Volle Breite',
    es: 'Ancho completo',
    fr: 'Pleine largeur',
    pt: 'Largura total',
    it: 'Larghezza piena',
    cs: 'Plná šířka',
    el: 'Πλήρες πλάτος',
  },
  a4Width96dpi: {
    pl: 'A4 szerokość @ 96 DPI',
    en: 'A4 width @ 96 DPI',
    de: 'A4 Breite @ 96 DPI',
    es: 'Ancho A4 @ 96 DPI',
    fr: 'Largeur A4 @ 96 DPI',
    pt: 'Largura A4 @ 96 DPI',
    it: 'Larghezza A4 @ 96 DPI',
    cs: 'Šířka A4 @ 96 DPI',
    el: 'Πλάτος A4 @ 96 DPI',
  },
  a4Height96dpi: {
    pl: 'A4 wysokość @ 96 DPI',
    en: 'A4 height @ 96 DPI',
    de: 'A4 Höhe @ 96 DPI',
    es: 'Alto A4 @ 96 DPI',
    fr: 'Hauteur A4 @ 96 DPI',
    pt: 'Altura A4 @ 96 DPI',
    it: 'Altezza A4 @ 96 DPI',
    cs: 'Výška A4 @ 96 DPI',
    el: 'Ύψος A4 @ 96 DPI',
  },
  oneInch96dpi: {
    pl: '1 cal @ 96 DPI',
    en: '1 inch @ 96 DPI',
    de: '1 Zoll @ 96 DPI',
    es: '1 pulgada @ 96 DPI',
    fr: '1 pouce @ 96 DPI',
    pt: '1 polegada @ 96 DPI',
    it: '1 pollice @ 96 DPI',
    cs: '1 palec @ 96 DPI',
    el: '1 ίντσα @ 96 DPI',
  },
  print300dpi: {
    pl: '300 DPI (druk)',
    en: '300 DPI (print)',
    de: '300 DPI (Druck)',
    es: '300 DPI (impresión)',
    fr: '300 DPI (impression)',
    pt: '300 DPI (impressão)',
    it: '300 DPI (stampa)',
    cs: '300 DPI (tisk)',
    el: '300 DPI (εκτύπωση)',
  },
} as const;

// Helper function to get unit label for a locale
export function getUnitLabel(key: string, locale: string): string {
  const labels = UNIT_LABELS[key];
  if (!labels) return key;
  return labels[locale] || labels.en || key;
}

// Helper function to get category label for a locale
export function getCategoryLabel(
  category: FormatCategory,
  locale: string,
): string {
  const labels = CATEGORY_LABELS[category];
  return labels[locale] || labels.en || category;
}
